### ISSUE TITLE
Zip .arff files?

### ISSUE THREAD

**Issue by mfeurer** [openml/openml-python#1007]
The Python API accesses .arff files only a single time, namely when downloading and the caching it. Therefore, access speed to the zip file is not crucial and the overhead of reading a zipped file would be fine (as it is done rarely). This would allow us to zip the arff files in the cache directory to save quite some space, for example dataset 41990 goes down from 99MB to 12MB after zipping.

**Comment by PGijsbers** [comment]
One could ask if we would even need to keep the arff file around, provided a conversion to dataframe format already succeeded. But I think either change is unnecessary, as hopefully within the next half year we are looking into using parquet instead.

**Comment by mfeurer** [comment]
Makes sense. Let's hope that moving to Parquet goes ahead quick :)
