### ISSUE TITLE
Give possibility to not download the dataset qualities

### ISSUE THREAD

**Issue by mfeurer** [openml/openml-python#1009]
#### Description

When downloading a lot of datasets from OpenML in order to get detailed information about the individual features it is not necessary to also download the `qualities.xml` file, and one could therefore save one call to the server per dataset (and also avoid errors in case a dataset wasn't processed).

**Comment by a-moadel** [comment]
Hi @mfeurer,
Can I pick this feature up?

**Comment by mfeurer** [comment]
Sure, please go ahead. Do you need any further pointers?

**Comment by mfeurer** [comment]
Added via #1017. Thanks @a-moadel!
