### ISSUE TITLE
Overflow error when uploading dataset size > 2GB

### ISSUE THREAD

**Issue by sahithyaravi1493** [openml/openml-python#1010]
#### Description
OverflowError: string longer than 2147483647 bytes" when trying to upload a dataset larger than 2GB

#### Steps/Code to Reproduce
```
import openml
from openml.datasets.functions import create_dataset
import pandas as pd
# Downloaded https://archive.ics.uci.edu/ml/datasets/HIGGS 
df = pd.read_csv("~/Downloads/HIGGS.csv", header=None)
cols = ['target', 'lepton pT', 'lepton eta', 'lepton phi', 'missing energy magnitude', 'missing energy phi', 'jet 1 pt', 'jet 1 eta', 'jet 1 phi', 'jet 1 b-tag', 'jet 2 pt', 'jet 2 eta', 'jet 2 phi', 'jet 2 b-tag', 'jet 3 pt', 'jet 3 eta', 'jet 3 phi', 'jet 3 b-tag', 'jet 4 pt', 'jet 4 eta', 'jet 4 phi', 'jet 4 b-tag', 'm_jj', 'm_jjj', 'm_lv', 'm_jlv', 'm_bb', 'm_wbb', 'm_wwbb']
cols = list(map(lambda x: x.replace(' ','_'), cols))
df.columns = cols
df.target = df.target.astype('int').astype('str').astype('category')
# Get the description
d = openml.datasets.get_dataset(23512)
oml_dataset = create_dataset(
    name = 'Higgs',
    description = d.description,
    creator=d.creator,
    contributor=d.contributor,
    collection_date=d.collection_date,
    language='English',
    licence= d.licence,
    default_target_attribute= df.columns[0],
    row_id_attribute = d.row_id_attribute,
    ignore_attribute = d.ignore_attribute,
    citation = d.citation,
    attributes='auto',
    data=df,    
    original_data_url = d.original_data_url
)
oml_dataset.publish()
print(f"URL for dataset: {oml_dataset.openml_url}")
```

#### Expected Results
No error is thrown

#### Actual Results
"OverflowError: string longer than 2147483647 bytes"

**Comment by sahithyaravi1493** [comment]
I looked into it, Its not a limit imposed by openml, It is a problem with [requests.post ](https://github.com/psf/requests/issues/2717)(which we use for post requests from openml-python). The same issue has been asked on the requests bug tracker; their suggestion is to use streaming upload. We have to look if there are better solutions.  I am currently looking into multipart encoder : https://toolbelt.readthedocs.io/en/latest/uploading-data.html to solve this (hence self-assigned this issue).

**Comment by mfeurer** [comment]
Could you please check whether this is the same as #746?

**Comment by sahithyaravi1493** [comment]
> Could you please check whether this is the same as #746?

@mfeurer yes, It is the same...Are we going to wait to change to parquet then? If that is the case I will stop looking into the multipart encoder

**Comment by mfeurer** [comment]
I don't have an opinion on that, so if you want to work on that I'd be fine merging this. This could also be helpful in the future if Parquet-files are getting larger than 2G. However, please check with Joaquin whether he thinks it's better to wait for Parquet.

**Comment by sahithyaravi1493** [comment]
> I don't have an opinion on that, so if you want to work on that I'd be fine merging this. This could also be helpful in the future if Parquet-files are getting larger than 2G. However, please check with Joaquin whether he thinks it's better to wait for Parquet.

We are planning to wait for Parquet, as it is already in progress.

**Comment by mfeurer** [comment]
Okay, then I'm closing this.
