### ISSUE TITLE
openml.datasets.list_datasets() fails with KeyError: 'oml:data'

### ISSUE THREAD

**Issue by kazeevn** [openml/openml-python#102]
Hi!

I've tried the today's version 20f029227ed584f07830fe941568ffc94c8b0b5a on Python 3 and have
`KeyError                                  Traceback (most recent call last)
<ipython-input-4-88796dc42429> in <module>()
----> 1 datasets = openml.datasets.list_datasets()
      2 
      3 data = pd.DataFrame(datasets)
      4 print("First 10 of %s datasets..." % len(datasets))
      5 print(data[:10][['did','name','NumberOfInstances','NumberOfFeatures']])

/opt/conda/envs/open-ml/lib/python3.5/site-packages/openml/datasets/functions.py in list_datasets()
    117         these are also returned.
    118     """
--> 119     return _list_datasets("data/list")
    120 
    121 

/opt/conda/envs/open-ml/lib/python3.5/site-packages/openml/datasets/functions.py in _list_datasets(api_call)
    141 
    142     # Minimalistic check if the XML is useful
--> 143     assert type(datasets_dict['oml:data']['oml:dataset']) == list, \
    144         type(datasets_dict['oml:data'])
    145     assert datasets_dict['oml:data']['@xmlns:oml'] == \

KeyError: 'oml:data'
`

**Comment by amueller** [comment]
should be fixed.

**Comment by kazeevn** [comment]
Fixed.
