### ISSUE TITLE
Public `delete` methods

### ISSUE THREAD

**Issue by PGijsbers** [openml/openml-python#1028]
Currently `openml-python` only allows for the deletion of `studies` but the rest API (and our internal `openml.utils._delete_entity`) support the deletion of other entities as well (dataset, flow, task, run, user). ~I don't know if this was deliberate, but if it wasn't, they should be added.~

**Comment by mfeurer** [comment]
This was a decision made by me in the early days of OpenML-Python. I think that decision should be reverted and these functions should be implemented.

**Comment by Mirkazemi** [comment]
I'm working on the issue but I could not assign it to myself.
