### ISSUE TITLE
Can't get dataset 61 (iris)

### ISSUE THREAD

**Issue by kazeevn** [openml/openml-python#103]
On version 20f029227ed584f07830fe941568ffc94c8b0b5a
`
dataset = openml.datasets.get_dataset(61)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-16-8756286212b8> in <module>()
----> 1 dataset = openml.datasets.get_dataset(61)
      2 
      3 print("This is dataset '%s', the target feature is called '%s'" % (dataset.name, dataset.default_target_attribute))
      4 print("URL: %s" % dataset.url)
      5 print(dataset.description[:500])

/opt/conda/envs/open-ml/lib/python3.5/site-packages/openml/datasets/functions.py in get_dataset(did)
    237                          "cast to an Integer.")
    238 
--> 239     description = get_dataset_description(did)
    240     arff_file = _get_dataset_arff(did, description=description)
    241 

/opt/conda/envs/open-ml/lib/python3.5/site-packages/openml/datasets/functions.py in get_dataset_description(did)
    253 
    254     try:
--> 255         return _get_cached_dataset_description(did)
    256     except (OpenMLCacheException):
    257         try:

/opt/conda/envs/open-ml/lib/python3.5/site-packages/openml/datasets/functions.py in _get_cached_dataset_description(did)
     82             continue
     83 
---> 84         return xmltodict.parse(dataset_xml)["oml:data_set_description"]
     85 
     86     raise OpenMLCacheException("Dataset description for did %d not "

KeyError: 'oml:data_set_description'
`
Iris v. 3 (http://www.openml.org/d/969) works fine,

**Comment by kazeevn** [comment]
I've just tried it again and succeeded.

**Comment by mfeurer** [comment]
Okay, so I'll close this.
