### ISSUE TITLE
Two unit tests fail on Windows

### ISSUE THREAD

**Issue by PGijsbers** [openml/openml-python#1033]
The following tests fail on Windows:
```
tests/test_openml/test_config.py::TestConfig::test_non_writable_home - AssertionError: 0 != 2
tests/test_utils/test_utils.py::OpenMLTaskTest::test__create_cache_directory - AssertionError: OpenMLCacheException not raised
```

**Comment by PGijsbers** [comment]
@mfeurer 

As far as I can tell these permissions can't be set by Python built-in modules on Windows but need an additional dependency, e.g. [pywin32](https://pypi.org/project/pywin32/) [[1](https://superuser.com/questions/1247843/why-can-i-write-files-into-a-folder-that-is-read-only), [2](https://stackoverflow.com/questions/12168110/setting-folder-permissions-in-windows-using-python), [3](http://timgolden.me.uk/python/win32_how_do_i/add-security-to-a-file.html)]. I did do manual tests.

`test_non_writable_home `:
 - before `_setup` deny write permissions manually (through Securities tab of the directory properties)
 - after `_setup`, before exiting the temporary file context, adding back write permissions (to allow for clean up of the temp dir)
 

`test_non_writable_home `:
 - before the `openml.utils._create_cache_directory("ghi")` call, deny write permission on `"def"`
 - before the end of the temp dir context manager, reinstate write permissions (to allow for clean up of the temp dir)

With this manual intervention, both tests pass.

Because it looks like the behavior works as intended on Windows, but requires an additional dependency to test automatically, I propose to only test this behavior in UNIX systems. Should at some point in the future the Windows functionality be broken _and_ a user actually be affected by it, we'll deal with it then. Sounds good?

**Comment by mfeurer** [comment]
Thanks for investigating this. I created a PR at https://github.com/openml/openml-python/pull/1040 to fix this so we can commence with a release.

**Comment by PGijsbers** [comment]
I'm sorry, I had already made the changes locally 😓 but I forgot to set up the PR.
