### ISSUE TITLE
Dataset functions are missing from documentation again

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#1035]
#### Description
When checking the docs for the OpenMLDataset object, only the constructor is documented - none of the operations:
https://openml.github.io/openml-python/develop/generated/openml.OpenMLDataset.html#openml.OpenMLDataset

E.g. dataset.get_data should be fully documented, and there are docstrings - they just don't show up in the docs:
https://github.com/openml/openml-python/blob/develop/openml/datasets/dataset.py#L653

#### Steps/Code to Reproduce
Check docs: https://openml.github.io/openml-python/develop/generated/openml.OpenMLDataset.html#openml.OpenMLDataset

(same problem for both master and develop)

#### Expected Results
Documentation on all operations.

#### Actual Results
Only the constructor is documented.

**Comment by PGijsbers** [comment]
Agreed, with the remark that only public methods should be included (i.e. not those that are prefixed with an underscore).

**Comment by PGijsbers** [comment]
OpenML classes derive some functionality from the `OpenMLBase` class, e.g. `push_tag`  and `remove_tag`, `publish` and so on. These should also be included in the API documentation.

**Comment by PGijsbers** [comment]
Fixed in #1044
