### ISSUE TITLE
Should we really retry on HashException and ExpatError?

### ISSUE THREAD

**Issue by PGijsbers** [openml/openml-python#1072]
Sometimes when we encounter an error, we will wait a while before contacting the server again with the same query. This is done [here](https://github.com/openml/openml-python/blob/6e8a9db03fd1af9d3eb0623970101413b531cc69/openml/_api_calls.py#L222-L265). In particular for `ExpatError` (XML can't be parsed) and `HashException` (file does not hash to expected value), I wonder if we should attempt to retry.
I assume these errors are only raised when the server sends dirty data, since general dropped information should be prevented through the transfer protocol. So I think retrying in these cases only makes sense if you assume the server sends data non-deterministically. Minus extraordinarily rare events (e.g. corrupted memory), I don't think this should occur. Are there more common reasons I'm not aware of?
If not, I would propose to remove retries from these errors altogether, or limit them to one retry.

**Comment by mfeurer** [comment]
> In particular for ExpatError (XML can't be parsed) and HashException (file does not hash to expected value), I wonder if we should attempt to retry.

The server sometimes sends nonsense when under high load and we were unable to debug on the python side. Adding a retry on these two has made the unit test somewhat stable at all. I'm hugely in favour of keeping them.

**Comment by PGijsbers** [comment]
I figured it could happen, but I didn't realize it was frequent to mess up unit tests. In that case I agree.
