### ISSUE TITLE
Make downloading dataset features optional

### ISSUE THREAD

**Issue by PGijsbers** [openml/openml-python#1081]
Currently the data features file is always downloaded [here](https://github.com/openml/openml-python/blob/3aee2e05186f2151e45c9ddc5bdd0709459bfce3/openml/datasets/functions.py#L412). I propose we make it optional, similar to `qualities` and the dataset itself. If not downloaded, it should follow the same lazy loading behavior that `qualities` does.

Having `features` immediately available is often not necessary. E.g. automated runs don't use them and when users download the data much of `features` info is already available in the built dataframe. But it does bring the usual downsides of longer user wait times, especially when downloading `features`  with high cardinality categorical features, e.g. [albert](https://www.openml.org/api/v1/xml/data/features/41147), and the additional server strain.

**Comment by PGijsbers** [comment]
Should also update the [dataset `repr` method](https://github.com/openml/openml-python/blob/3aee2e05186f2151e45c9ddc5bdd0709459bfce3/openml/datasets/dataset.py#L251) so that it can obtain `#features` from `qualities` if that is available and `features` is not.

**Comment by LennartPurucker** [comment]
We introduced lazy loading in #1260 and made it optional from 0.15.0 onwards.
