### ISSUE TITLE
Datasets versions

### ISSUE THREAD

**Issue by learsi1911** [openml/openml-python#1094]
#### Description

I am new to OpenML and I would like to know what are the criteria that OpenML has to store a new dataset, that is, taking the example of the documentation if I want to upload a dataset called "zoo", is considered only the order in which it was uploaded or OpenML can take into account the metadata to organize the datasets with the same name?

**Comment by PGijsbers** [comment]
You can store any dataset on OpenML. If the name matches that of an existing dataset, it is automatically labelled as a new version for that dataset, _irrespective of the similarity to the old dataset_.

@joaquinvanschoren I think we really should consider this behavior. If a user uploads a completely different dataset but with the name of an existing one, I would rather point this out to the user so they can reconsider giving the dataset a unique name. Ideally we could do some basic check to see if the datasets are 'similar' enough that it's likely they're different versions of the same data.

**Comment by learsi1911** [comment]
Ok, I understand.
Yeah, I was thinking it would be kind of awesome to upload a dataset and
through openML you could also find similar datasets based on the meta data.
Thank you very much for your help

**Comment by PGijsbers** [comment]
If you just want to have an overview of datasets with the same name then you can always use:

```python
import openml
openml.datasets.list_datasets(data_name="zoo", output_format="dataframe")
```

**Comment by PGijsbers** [comment]
Sahithya is also working on topic modeling to automatically label datasets based on their description (iirc). This will later be accessible through tags (I think), but that's not live yet.

**Comment by learsi1911** [comment]
That's awesome. Hopefully soon that improvement will be available, I thank
you.

**Comment by PGijsbers** [comment]
You're welcome! As far as I can tell there is no more open issue for `openml-python` so I'm closing this.
