### ISSUE TITLE
make publish store id (and other stuff) in object

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#110]
currently publish returns XML. it really shouldn't. It should return `self` or nothing, and should store the result from the server.

**Comment by PGijsbers** [comment]
This has been fixed at some point in time for [datasets](https://github.com/openml/openml-python/blob/develop/openml/datasets/dataset.py#L439), [flows](https://github.com/openml/openml-python/blob/develop/openml/flows/flow.py#L356) and [runs](https://github.com/openml/openml-python/blob/develop/openml/runs/run.py#L240). Publishing tasks has not been implemented yet.
