### ISSUE TITLE
`list_tasks` docstring outdated.

### ISSUE THREAD

**Issue by mfeurer** [openml/openml-python#1104]
Task Type IDs have been replaced by a task type enum. This should be reflected in the docstring:
![image](https://user-images.githubusercontent.com/5320498/127492939-9feec34f-aab2-4adf-b0c8-fec8f5323ba3.png)

**Comment by kadatatlukishore** [comment]
Hey @PGijsbers, Can I take this up ?

**Comment by PGijsbers** [comment]
That'd be great! Let us know if you have any questions.

**Comment by kadatatlukishore** [comment]
Hey @PGijsbers , If I change the `ID` to `Enum` that makes sense or I have to change the sentence accordingly

**Comment by PGijsbers** [comment]
I think simplifying the sentence structure altogether because we can now reference the `TaskType` documentation directly is better. That way we can avoid enumerating all task types each time it's an expected parameter.

**Comment by PGijsbers** [comment]
Hi @kadatatlukishore, I hope you're doing well :)
Do you still plan to work on this issue soon? If not, I will remove you as an assignee. 
Should you want to take it up after all at a later time (and its still unresolved), you can just indicate you want to start again.
