### ISSUE TITLE
Make optional arguments to `create_study` actually optional

### ISSUE THREAD

**Issue by PGijsbers** [openml/openml-python#1110]
From the docs [`create_study`](https://openml.github.io/openml-python/main/generated/openml.study.create_study.html#openml.study.create_study) and `create_benchmark_suite` contain some optional parameters, e.g. `alias`, which don't have defaults which actually makes them required.

1. For the `alias` parameter a `None` default seems sensible.
2. For a `study` the `suite`'s id is also optional, is it by design that we want studies without suites?
3. I would argue that for a `study`, the `run_ids` should also be optional as they could be created later (e.g. in a setup where you define a study, and upload results to it as they come in).

**Comment by joaquinvanschoren** [comment]
1. None is a good default indeed
2. Yes, we can create a collection of runs that is not directly tied to a suite. E.g. one could create a collection containing all runs of a specific algorithm/flow.
3. Agreed!

**Comment by PGijsbers** [comment]
I [made some progress](https://github.com/openml/openml-python/tree/fix/1110) but ran into the following two "issues", which makes me want to double check before making the changes (in particular with @mfeurer for the first issue).

First, downloading studies (and suites) without any attached data is currently [explicitly not possible](https://github.com/openml/openml-python/blob/6717e66a1e967a131a6ca7feb96f6d166017bed7/openml/study/functions.py#L109-L137). I think we should adapt the code, as the server should decide what is and is not acceptable. Wdyt?

Second, uploading an explicitly empty study (i.e. having a data field but only with an empty sequence) is not allowed ([xsd](https://github.com/openml/OpenML/blob/develop/openml_OS/views/pages/api_new/v1/xsd/openml.study.upload.xsd)). This is not necessarily an issue (we can deal with this in `openml-python` internally), but perhaps we should make it also explicit on the server side.

XML for an implicitly empty study (uploads fine):
```xml
<oml:study xmlns:oml="http://openml.org/openml">
	<oml:main_entity_type>run</oml:main_entity_type>
	<oml:name>empty-study-implicit</oml:name>
	<oml:description>a study with no runs attached implicitly</oml:description>
</oml:study>
```

XML for an explicity empty study:
```xml
<oml:study xmlns:oml="http://openml.org/openml">
	<oml:main_entity_type>run</oml:main_entity_type>
	<oml:name>empty-study-explicit</oml:name>
	<oml:description>a study with no runs attached explicitly</oml:description>
	<oml:runs>
	</oml:runs>
</oml:study>
```
returns the following error:
```xml
<oml:error xmlns:oml="http://openml.org/openml">
	<oml:code>1032</oml:code>
	<oml:message>Description file does not correspond to XSD schema</oml:message>
	<oml:additional_information>
	    XML does not correspond to XSD schema. Error Element '{http://openml.org/openml}runs': 
            Missing child element(s). Expected is ( {http://openml.org/openml}run_id ). on line 5 column 0. 
        </oml:additional_information>
</oml:error>

```

If we are not adding allowing explicitly empty studies server-side, I will just make sure they get created implicitly (first xml). But if we do change this, then I can immediately make sure both are supported.

**Comment by mfeurer** [comment]
This all sound reasonable and I agree with the proposed changes. I just don't see what I can say about the XSD not allowing empty studies
