### ISSUE TITLE
can't download flow

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#112]
there is no function lol

**Comment by mfeurer** [comment]
Added in 0ff6ed2. Next commit is adding an upload method for flow, which has components. Commit after that (and after https://github.com/openml/OpenML/issues/14 is fixed) will add building a scikit-learn model from such an uploaded flow with get_flow().

**Comment by mfeurer** [comment]
See #77

**Comment by mfeurer** [comment]
Now in PR #167

**Comment by mfeurer** [comment]
Just merged in #167, so this is finally done :)
