### ISSUE TITLE
Provide clear naming for the inconsistent ways to get the cache directory

### ISSUE THREAD

**Issue by PGijsbers** [openml/openml-python#1124]
```python
import openml
openml.config.get_cache_directory()   # is:   '~\\.openml\\org\\openml\\www'
openml.config.cache_directory         # is:   '~\\.openml'
``` 

`get_cache_directory`  gets the cache for the currently configured server, while `cache_directory` gets the root of the cache directory.
`set_cache_directory(str)` configures the root.

If we plan to maintain an external interface for both types, I propose we:
 - we make them both functions so they are accessed in the same way (and using a function will make a get\set pattern easier where a set can be optionally for the session or saved to the configuration file)
 - make it clear in the name what (part of) the cache directory is returned

**Comment by mfeurer** [comment]
I agree on both, we should provide getters and setters for stuff from the config, and we should make the naming clearer.
