### ISSUE TITLE
OSError when importing salary dataset from openml

### ISSUE THREAD

**Issue by Gansie2** [openml/openml-python#1130]
#### Actual Results
 491                 data = pd.read_parquet(data_file)
    492             except Exception as e:

~\Anaconda3\lib\site-packages\pandas\io\parquet.py in read_parquet(path, engine, columns, storage_options, use_nullable_dtypes, **kwargs)
    494 
--> 495     return impl.read(
    496         path,

~\Anaconda3\lib\site-packages\pandas\io\parquet.py in read(self, path, columns, use_nullable_dtypes, storage_options, **kwargs)
    238         try:
--> 239             result = self.api.parquet.read_table(
    240                 path_or_handle, columns=columns, **kwargs

~\Anaconda3\lib\site-packages\pyarrow\parquet.py in read_table(source, columns, use_threads, metadata, use_pandas_metadata, memory_map, read_dictionary, filesystem, filters, buffer_size, partitioning, use_legacy_dataset, ignore_prefixes)
   1730 
-> 1731         return dataset.read(columns=columns, use_threads=use_threads,
   1732                             use_pandas_metadata=use_pandas_metadata)

~\Anaconda3\lib\site-packages\pyarrow\parquet.py in read(self, columns, use_threads, use_pandas_metadata)
   1607 
-> 1608         table = self._dataset.to_table(
   1609             columns=columns, filter=self._filter_expression,

~\Anaconda3\lib\site-packages\pyarrow\_dataset.pyx in pyarrow._dataset.Dataset.to_table()

~\Anaconda3\lib\site-packages\pyarrow\_dataset.pyx in pyarrow._dataset.Scanner.to_table()

~\Anaconda3\lib\site-packages\pyarrow\error.pxi in pyarrow.lib.pyarrow_internal_check_status()

~\Anaconda3\lib\site-packages\pyarrow\error.pxi in pyarrow.lib.check_status()

OSError: NotImplemented: Support for codec 'snappy' not built

The above exception was the direct cause of the following exception:

Exception                                 Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_18816/499319625.py in <module>
      2 # Note that X is a pandas dataframe
      3 salary = openml.datasets.get_dataset(42125)
----> 4 X, y, _, feat_names = salary.get_data(target=salary.default_target_attribute)

~\Anaconda3\lib\site-packages\openml\datasets\dataset.py in get_data(self, target, include_row_id, include_ignore_attribute, dataset_format)
    696             List of attribute names.
    697         """
--> 698         data, categorical, attribute_names = self._load_data()
    699 
    700         to_exclude = []

~\Anaconda3\lib\site-packages\openml\datasets\dataset.py in _load_data(self)
    529 
    530             file_to_load = self.data_file if self.parquet_file is None else self.parquet_file
--> 531             return self._cache_compressed_file_from_file(file_to_load)
    532 
    533         # helper variable to help identify where errors occur

~\Anaconda3\lib\site-packages\openml\datasets\dataset.py in _cache_compressed_file_from_file(self, data_file)
    491                 data = pd.read_parquet(data_file)
    492             except Exception as e:
--> 493                 raise Exception(f"File: {data_file}") from e
    494 
    495             categorical = [data[c].dtype.name == "category" for c in data.columns]

Exception: File: C:\Users\20175775\.openml\org\openml\www\datasets\42125\dataset.pq-->

**Comment by PGijsbers** [comment]
Hi, thanks for taking the time to open an issue, but for further troubleshooting, please do provide the additional information that we request in the template, including:
 - (a minimal working example of) code that produces this error
 - information about your installed packages and OS
 
At first glance it looks like this is not an issue with `openml-python`  itself but rather one of its dependencies. It looks like conda installs of pyarrow may no longer come prepackaged with the ' snappy'  codec. If you are using conda, try uninstalling the package and then re-installing with pip. See also:

 - https://github.com/int-brain-lab/iblenv/issues/212
 - https://stackoverflow.com/questions/66017811/python-error-using-pyarrow-arrownotimplementederror-support-for-codec-snappy
