### ISSUE TITLE
Update download dataset parser for change of `minio_url` to `parquet_url`

### ISSUE THREAD

**Issue by PGijsbers** [openml/openml-python#1142]
The `minio_url` field in the dataset description URL is deprecated and will be fully replaced by `parquet_url` in the future (in the mean time, both are available).

**Comment by varshneydevansh** [comment]
I learned about the `minio_url` and `parquet_url` both are different ways of accessing or storing data. The minio_url typically refers to the URL used to access data stored in a `MinIO` object storage system, while the `parquet_url` is usually the URL used to access data stored in a Parquet file format. It ultimately depends on the specific use case and requirements of the system or application being used.

All I have to do is to carefully replace the `minio_url` with the `parquet_url`?

**Comment by PGijsbers** [comment]
Correct! minio_url will be removed in the future and we will need to use parquet_url before then.

**Comment by PGijsbers** [comment]
When we request a dataset from the server, we get an xml response (e.g., [iris](https://www.openml.org/api/v1/data/61)). As you can see, that contains both a `parquet_url` and `minio_url`. The relevant parsing for data download happens [here](https://github.com/openml/openml-python/blob/1d7fbda2bd58fa427277a12d6a4cacb431c9dcbe/openml/datasets/functions.py#L498). There are also a few other places where `minio_url` is referenced and they should also be updated accordingly. The corresponding field on the dataset [`_minio_url`](https://github.com/openml/openml-python/blob/1d7fbda2bd58fa427277a12d6a4cacb431c9dcbe/openml/datasets/dataset.py#L213) should also be updated with to reflect it points to a parquet file.
Any tests that specifically test for parquet files should be checked to see if they need updating.

**Comment by varshneydevansh** [comment]
I wanna know about this API method

- https://github.com/varshneydevansh/openml-python/blob/1d7fbda2bd58fa427277a12d6a4cacb431c9dcbe/openml/_api_calls.py#L112


- If we are completely shifting away from the MinIO then consider renaming this function to something more generic like `_download_file_from_url`
- If are still using MinIO but just emphasizing that we are downloading Parquet files, then just passing pass the correct source URL (now from the oml:parquet_url field).

**Comment by PGijsbers** [comment]
It’s the latter. There are currently no plans to move away from minio. On the contrary, we might eventually store _more_ than just the parquet file on minio. For that reason we want to use the parquet url, since it better matches semantically what we are after.
