### ISSUE TITLE
make sure flows are not duplicated on the server

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#115]
not sure if runs can be duplicate?
We should really check what we upload.

**Comment by janvanrijn** [comment]
In weka we have a config item that determines whether to check this before running. I will port this functionality to python too .

**Comment by janvanrijn** [comment]
misred the topic name, thought it was about duplicate runs. 

Flow duplication is checked on the server. 

Run duplication is now checked with a specific option (avoid_duplicate runs: https://github.com/openml/openml-python/tree/check_run_exists). I will make a pull request later.
