### ISSUE TITLE
Error in uploading a new dataset

### ISSUE THREAD

**Issue by MahmoudZamani** [openml/openml-python#1151]
Hello Freinds,

I am getting below error during the data-set uploading:

---------------------------------------------------------------------------
ExpatError                                Traceback (most recent call last)
<ipython-input-413-74b0163b7e4c> in <module>
----> 1 dataset.publish()
      2 print(f"URL for dataset: {dataset.openml_url}")

~/anaconda3/lib/python3.7/site-packages/openml/base.py in publish(self)
    131             call, "post", file_elements=file_elements
    132         )
--> 133         xml_response = xmltodict.parse(response_text)
    134 
    135         self._parse_publish_response(xml_response)

~/anaconda3/lib/python3.7/site-packages/xmltodict.py in parse(xml_input, encoding, expat, process_namespaces, namespace_separator, disable_entities, **kwargs)
    325         parser.ParseFile(xml_input)
    326     else:
--> 327         parser.Parse(xml_input, True)
    328     return handler.item
    329 

ExpatError: syntax error: line 1, column 0

Appreciate for any help!

**Comment by PGijsbers** [comment]
This is probably hard to reproduce without the original data file and upload script.
Could you provide us with the file you wanted to upload and the script with which you try to upload?

**Comment by mfeurer** [comment]
Closing this as the poster did not respond to the request for additional information. Please re-open if this issue persists and you can share further information.
