### ISSUE TITLE
Look into "depenabot" for pre-commit

### ISSUE THREAD

**Issue by PGijsbers** [openml/openml-python#1153]
See #1150, it might be useful to have some automation which can bump the versions for the pre-commit dependencies and automatically notify us of this. We should look at how easy this is to set up (`dependabot`might be helpful, since it serves a similar purpose), and if it's worth pursuing (caveats mentioned in the PR).

**Comment by eddiebergman** [comment]
Hi @PGijsbers CC @mfeurer,

I looked into it and there's 2 solutions, one automatic and one manual:
1. Use a [github workflow](https://github.com/marketplace/actions/pre-commit-autoupdate) that will run everyday and create a PR if it needs updating
2. Run [`pre-commit autoupdate`](https://pre-commit.com/#using-the-latest-version-for-a-repository) on your local code and it will check for updates and apply accordingly, at which point you can manually make a PR.

I [checked dependabot](https://github.com/dependabot/dependabot-core/issues/1524#issuecomment-750307910) and it doesn't seem supported or on their roadmap.

There's a PR for 1. at #1154 if you want, feel free to close if it's not :)

Best,
Eddie

**Comment by mfeurer** [comment]
This is now enabled, see 1250 as an example.
