### ISSUE TITLE
data_id filter for get_tasks function

### ISSUE THREAD

**Issue by ShathaSaad** [openml/openml-python#1163]
#### Description
Hi, I need to get all tasks for each dataset in my code. There is no way to do this filtering.

#### Steps/Code to Reproduce
```
import openml

dataset=openml.datasets.list_datasets(output_format="dataframe")
did=dataset.did
for x in did:
 print("dataset ID: ",x)
 print(openml.datasets.get_dataset(x, download_data=False, version=1))
```

#### Expected Results
I want to get all tasks for each dataset I get in my code

#### Versions
Please run the following snippet and paste the output below.
Darwin-21.2.0-x86_64-i386-64bit
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)]
NumPy 1.19.5
SciPy 1.5.4
Scikit-Learn 0.24.2
OpenML 0.12.2

**Comment by PGijsbers** [comment]
[This example](https://openml.github.io/openml-python/main/examples/30_extended/tasks_tutorial.html#sphx-glr-examples-30-extended-tasks-tutorial-py) for the documentation explains you how to find tasks for a specific dataset.
![image](https://user-images.githubusercontent.com/15890747/192731953-4f685ab7-1c6d-4ff2-9cd1-ff8829421068.png)
