### ISSUE TITLE
Tests fail due to test server state

### ISSUE THREAD

**Issue by PGijsbers** [openml/openml-python#1167]
Running `pytest tests/test_setups/test_setup_functions.py::TestSetupFunctions::test_setuplist_offset` results in:
```python
    def test_setuplist_offset(self):
        # TODO: remove after pull on live for better testing
        # openml.config.server = self.production_server
    
        size = 10
        setups = openml.setups.list_setups(offset=0, size=size)
>       self.assertEqual(len(setups), size)
E       AssertionError: 5 != 10

tests/test_setups/test_setup_functions.py:170: AssertionError
```
because the test server only has 5 total setups right now. Many other tests are affected similarly. Two questions @janvanrijn @mfeurer:
1. How was the test server repopulated before? Apparently the current version is not repopulated in the same way.
2. We can move some of the tests to the production environment (those that only use `list` functions). But there are also ones that currently require some server state ([example](https://github.com/openml/openml-python/issues/1167#issuecomment-1263610650)), but continue to upload to the server. In that scenario, what should we do? Using production is not really an option.  We could drop the server state requirement for those tests where reasonable.

**Comment by PGijsbers** [comment]
Run: `pytest tests/test_utils/test_utils.py::OpenMLTaskTest::test_list_all_for_runs  `
Result:
```python
self = <tests.test_utils.test_utils.OpenMLTaskTest testMethod=test_list_all_for_runs>

    def test_list_all_for_runs(self):
        required_size = 21
        runs = openml.runs.list_runs(batch_size=25, size=required_size)
    
        # might not be on test server after reset, please rerun test at least once if fails
>       self.assertEqual(len(runs), required_size)
E       AssertionError: 12 != 21

tests/test_utils/test_utils.py:77: AssertionError
```

**Comment by PGijsbers** [comment]
Run: ` pytest tests/test_utils/test_utils.py::OpenMLTaskTest::test_list_all_for_setups `
Result:
```python
self = <tests.test_utils.test_utils.OpenMLTaskTest testMethod=test_list_all_for_setups>

    def test_list_all_for_setups(self):
        required_size = 50
        # TODO apparently list_setups function does not support kwargs
        setups = openml.setups.list_setups(size=required_size)
    
        # might not be on test server after reset, please rerun test at least once if fails
>       self.assertEqual(len(setups), required_size)
E       AssertionError: 5 != 50

tests/test_utils/test_utils.py:70: AssertionError
```

**Comment by PGijsbers** [comment]
Run: `pytest tests/test_study/test_study_functions.py::TestStudyFunctions::test_publish_study`
Result:
```python
self = <tests.test_study.test_study_functions.TestStudyFunctions testMethod=test_publish_study>

    @pytest.mark.flaky()
    def test_publish_study(self):
        # get some random runs to attach
        run_list = openml.evaluations.list_evaluations("predictive_accuracy", size=10)
>       self.assertEqual(len(run_list), 10)
E       AssertionError: 0 != 10

tests/test_study/test_study_functions.py:121: AssertionError
```

**Comment by PGijsbers** [comment]
Additionally, either parts were not uploaded or the order of uploads wasn't identical. The test below was supposed to download iris from the test server but downloads a very large file `(1_000_000, 4)`.

Run:`test_get_dataset_cache_format_feather`
Result:
```

self = <tests.test_datasets.test_dataset_functions.TestOpenMLDataset testMethod=test_get_dataset_cache_format_feather>

    def test_get_dataset_cache_format_feather(self):
    
        dataset = openml.datasets.get_dataset(128, cache_format="feather")
        dataset.get_data()
    
        # Check if dataset is written to cache directory using feather
        cache_dir = openml.config.get_cache_directory()
        cache_dir_for_id = os.path.join(cache_dir, "datasets", "128")
        feather_file = os.path.join(cache_dir_for_id, "dataset.feather")
        pickle_file = os.path.join(cache_dir_for_id, "dataset.feather.attributes.pkl.py3")
        data = pd.read_feather(feather_file)
        self.assertTrue(os.path.isfile(feather_file), msg="Feather file is missing")
        self.assertTrue(os.path.isfile(pickle_file), msg="Attributes pickle file is missing")
>       self.assertEqual(data.shape, (150, 5))
E       AssertionError: Tuples differ: (1000000, 40) != (150, 5)
E       
E       First differing element 0:
E       1000000
E       150
E       
E       - (1000000, 40)
E       + (150, 5)

tests/test_datasets/test_dataset_functions.py:1415: AssertionError
```

**Comment by mfeurer** [comment]
1. I don't recall how the test server was populated. Probably we just ran the unit tests once or twice to populate the test server.
2.1 Definitely yes, there is no reason to depend the test server.
2.2 we could build a python population script that upload necessary things to the server, or add such uploads to the functions in case the upload fails?

**Comment by janvanrijn** [comment]
I know how the test server is populated. There is a script for this on the test server, living in my home dir. This is a super useful script, as every so many times it would be good to clean the test server, restart the ES engine and add some standard records to the DB. It relies on some SQL files that are in the git repo. 

If you want, I can dig it up for you (we should probably add it to some git repo, to ensure it doesn't get lost)

**Comment by PGijsbers** [comment]
I think that would be very helpful @janvanrijn! Then you and/or @joaquinvanschoren can restart the server fresh from the populated state that our servers build on. This way, we can get openml-python to pass all tests. After that, we can refactor the tests so that we remove the requirement of server statefulness where reasonable.

> we could build a python population script that upload necessary things to the server, or add such uploads to the functions in case the upload fails?

As long as the unit tests refer to specific IDs, we will need to populate the server immediately after a fresh start. The alternative is to have some online file that lists which IDs to use (I am not a fan of that, it means an internet connection is required even if the test otherwise would get by from using the cache, and it adds an extra step on all those tests). After tests pass, I can work to see which ID references may be replaced by either a quick upload in the same test, downloads from the production server, or a uniquely named upload (in the case of datasets). In time I hope to further separate the dependency of the server by testing against cached server responses.

**Comment by mfeurer** [comment]
>  think that would be very helpful @janvanrijn! Then you and/or @joaquinvanschoren can restart the server fresh from the populated state that our servers build on. This way, we can get openml-python to pass all tests. After that, we can refactor the tests so that we remove the requirement of server statefulness where reasonable.

Don't these only add datasets and tasks?

> After tests pass, I can work to see which ID references may be replaced by either a quick upload in the same test, downloads from the production server, or a uniquely named upload (in the case of datasets). In time I hope to further separate the dependency of the server by testing against cached server responses.

That would be amazing!

**Comment by janvanrijn** [comment]
I just found the test set reset script. It's in my home dir on the openml test server (at least, I believe this is the test server) and it's called `reset.sh`

I now realize why it's in no repository, as it contains passwords from the MySQL server. Pieter, I presume you have admin rights on the OpenML (test) server, so you should be able to retrieve it from my homedir, right?
