### ISSUE TITLE
get_dataset() is too slow on my computer

### ISSUE THREAD

**Issue by xieleo5** [openml/openml-python#1181]
#### Description

I tried the tutorial code in openml's official document, use `dataset = openml.datasets.get_dataset(1471)` to load the dataset. And it takes me about 10 minutes to finish. I think the dataset should be quite small and should not take such a long time. 
#### Steps/Code to Reproduce
```python
import openml
dataset = openml.datasets.get_dataset(1471)
```

#### Expected Results

Finish in a second or few seconds.
#### Actual Results

Take more than 10 minutes to finish. Is it the expected behavior?
#### Versions

Windows-10-10.0.22000-SP0
Python 3.9.15 (main, Nov  4 2022, 16:35:55) [MSC v.1916 64 bit (AMD64)]
NumPy 1.21.2
SciPy 1.9.3
Scikit-Learn 0.24.2
OpenML 0.12.2

I'm using openML in conda environment. Does this matter?

**Comment by LeoGrin** [comment]
I'm having the same kind of issues lately. Weirdly, this seems to be fine on my mac, but fails on Linux (for various version of python).

**Comment by PGijsbers** [comment]
As of Friday we are experiencing some server issues, they are being looked into. Sorry for the inconvenience.

**Comment by TheBarzani** [comment]
Does these issues apply to the test server as well or is it only the default server?

**Comment by PGijsbers** [comment]
We're still working on a fix. In the meantime, you can use this monkeypatch (it falls back on the old ARFF datafiles instead):

```python
import openml
openml.datasets.functions._get_dataset_parquet = lambda x: None 
dataset = openml.datasets.get_dataset(1471)
```
This should download without issue.

@TheBarzani The test server is unaffected. If you experience issues there, let us know, it should be unrelated to this issue.

**Comment by joaquinvanschoren** [comment]
Dataset download should be restored now.
