### ISSUE TITLE
get_task() function does not give any response

### ISSUE THREAD

**Issue by ayyildizmuhammed** [openml/openml-python#1182]
#### Description
get_task() function does not produce any output neither an error nor a result. 
Also, I tried to track execution path and I can reach the file named ".../lib/python3.10/site-packages/urllib3/connectionpool.py". Line 444 of this file, causes something weird and program cannot continue after this method execution, but it does not raise any error or something else.  Finally, if I run the get_task method with download_data parameter as 'False', I can get the task definition, but not dataset. Do you have any idea for solution?
Thanks.

Line 444 of {venv_path}/lib/python3.10/site-packages/urllib3/connectionpool.py is below:
<img width="598" alt="image" src="https://user-images.githubusercontent.com/109205742/203033679-fea9371c-9e87-4794-85ac-9437bcb0c306.png">

#### Steps/Code to Reproduce
import openml
openml.tasks.get_task(task_id=31)

#### Expected Results
Get the task.

#### Actual Results
Nothing

#### Versions
macOS-13.0-arm64-arm-64bit
Python 3.10.6 (main, Nov 21 2022, 10:58:59) [Clang 14.0.0 (clang-1400.0.29.202)]
NumPy 1.23.5
SciPy 1.9.3
Scikit-Learn 1.1.3
OpenML 0.12.2

**Comment by PGijsbers** [comment]
Hi @ayyildizmuhammed 👋 
You correctly identified the issue is with downloading the dataset, please see https://github.com/openml/openml-python/issues/1181 for a work-around. The root-cause is a server issue, which we are working to resolve. In the meantime, the linked issue provides a monkeypatch work-around which should let you download the data.

**Comment by ayyildizmuhammed** [comment]
Thanks for reply, it is working now with monkeypatch.
Good luck for issue.
