### ISSUE TITLE
Comment in main example is wrong

### ISSUE THREAD

**Issue by PGijsbers** [openml/openml-python#1229]
[The example at the front page](https://openml.github.io/openml-python/main/index.html) of our docs reads:
```python
# Download the OpenML task for the german credit card dataset with 10-fold
# cross-validation.
task = openml.tasks.get_task(32)
```
But [task 32](https://www.openml.org/search?type=task&sort=runs&id=32) is pendigits. Credit-g is [task 31](https://www.openml.org/search?type=task&id=31&source_data.data_id=31) (and [t/32](https://test.openml.org/t/32) on the test server is mfeat).

**Comment by v-parmar** [comment]
Hey @PGijsbers, can you tell me in detail, what the is the issue?

**Comment by PGijsbers** [comment]
It should say that it's loading the pendigits task. I think that's preferred to adapting the example to work with the credit-g task (because it would complicate the example by needing to encode its nominal values).
