### ISSUE TITLE
Wrong references in 'Creating Custom Flow' tutorial

### ISSUE THREAD

**Issue by ArturDev42** [openml/openml-python#1241]
#### Description
In section **2. Using the flow** of https://openml.github.io/openml-python/main/examples/30_extended/custom_flow_.html#sphx-glr-examples-30-extended-custom-flow-py the comment for `task_id=1965` references `# Iris Task` but 1965 is actually https://test.openml.org/t/1965 which uses the **anneal** dataset. 

Further below in the tutorial, predictions for the iris dataset are prepared.

```
# random class probabilities (Iris has 150 samples and 3 classes):
r = np.random.rand(150 * n_repeats, 3)
```

The iris dataset contains 4 classes. It's nothing major, just wanted to mention it.

**Comment by LennartPurucker** [comment]
Hi,

Thank you for reporting this. You are correct, the `task_id`  for the Iris task has changed on the test server. The correct ID should be: `1200`. I will add a PR shortly to fix this. 

However, I am a bit confused about your last comment. The iris dataset has only 3 classes (https://test.openml.org/d/128). The code crashes as it was not made for the `anneal` dataset.
