### ISSUE TITLE
better dataset interface

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#128]
I'd like to download all "small" datasets. I don't think that's currently possible with the API.
We should try to download the qualities of the data, but not the actual data, when fetching a dataset (I think).

**Comment by joaquinvanschoren** [comment]
This is what the list_datasets function already does.

You can do:

datalist = datasets.list_datasets()
data = pd.DataFrame(datalist)
small_data = data.loc[data['NumberOfInstances'] < 10000]

An then loop over:
datasets.get_dataset(did)

Would that work?
Joaquin

**Comment by amueller** [comment]
ah. yeah. I didn't realize list_datasets returns the number of instances. thanks.

**Comment by amueller** [comment]
(Oh I just realized the tasks actually had the features. never mind, I'm stupid)
