### ISSUE TITLE
[CI] Add `pyproject.toml` for `black`

### ISSUE THREAD

**Issue by eddiebergman** [openml/openml-python#1297]
When starting up my editor, `black` wanted to format to `88`. Upon looking, there's no specification anywhere. [Turns out it should be in a `pyproject.toml` file](https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-a-file).

In general, we can migrate most tools over to a `pyproject.toml` but not really important to do now

**Comment by PGijsbers** [comment]
I agree. This project pre-dates `pyproject.toml` (at least the support for it by various tools), but I would very much like to move as much of the different tool configurations in there, so everything is configured in an easily identifiable central place.
