### ISSUE TITLE
task.get_X_and_Y buggy

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#130]
there is a call to get_dataset that should be get_data.
Looks like we need more testing ^^

**Comment by mfeurer** [comment]
also, the method should be called `get_X_and_y` (as mentioned [here](https://github.com/openml/openml-python/pull/119/files#r61759908))

**Comment by mfeurer** [comment]
I just checked the respective method `task.get_X_and_y` and it correctly calls `get_data`. It seems like this got fixed a while ago and the person fixing this forgot to close this issue.
