### ISSUE TITLE
[Refactor] `openml/config`, switch from globals to just using a classes?

### ISSUE THREAD

**Issue by eddiebergman** [openml/openml-python#1300]
There's a lot of jumping around with `global` and it's hard to keep track of, why use globals here?

**Comment by PGijsbers** [comment]
I think because it was the least invasive change at the time. If we do change this, we need to give users warnings and time to accommodate (as with all breaking changes).

**Comment by eddiebergman** [comment]
I think that's too breaking and would add a lot of cruft to deal with. Will close as it's not worth it
