### ISSUE TITLE
Error while downloading a meta-album dataset, invalid bucket name.

### ISSUE THREAD

**Issue by AlejandroDopico2** [openml/openml-python#1330]
#### Description
I'm encountering an issue when attempting to download dataset files from OpenML. The error message indicates an invalid bucket name being used.

#### Steps/Code to Reproduce

I'm using the OpenML library in Python to download dataset files. Here's the code snippet I'm using:

```
dataset = openml.datasets.get_dataset(44314, download_data=True, download_all_files=True, download_features_meta_data=True, force_refresh_cache=True)
```

#### Expected Results

I expect the dataset files associated with dataset ID 44314 to be downloaded (including the images) successfully without any errors.

#### Actual Results

I encounter the following error message:
```
ValueError: invalid bucket name datasets/0004/44314
```
#### Versions

Windows-10-10.0.22621-SP0
Python 3.7.1 (default, Oct 28 2018, 08:39:03) [MSC v.1912 64 bit (AMD64)]
NumPy 1.21.6
SciPy 1.7.3
Scikit-Learn 1.0.2
OpenML 0.14.1

**Comment by PGijsbers** [comment]
Please update to openml 0.14.2 (the latest) and try again. That patch should solve this issue.
