### ISSUE TITLE
Maybe use dill to store functions and objects?

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#147]
An alternative to using pickle to store functions is to use dill, which also stores the code.
https://pypi.python.org/pypi/dill

**Comment by mfeurer** [comment]
Do you mean for the serialization in xml or to store the source of the algorithm?

**Comment by mfeurer** [comment]
Currently, I don't see a need to store the actual function object. Right now we store the module reference which should be sufficient to load most standard functions.
