### ISSUE TITLE
Allow submission of optimization trace

### ISSUE THREAD

**Issue by mfeurer** [openml/openml-python#170]
First version implemented in https://github.com/openml/openml-python/pull/133/commits/ef3620d49bfe4fb38fe9683aba1b628d614d7d02

Won't be merged and has to be re-done

**Comment by janvanrijn** [comment]
This works, right?

Basically, all you have to do is run a task with a subclass of "BaseSearchCV". In the _run_task_get_arffcontent (run) an arff trace is generated.

Please reopen if there is any problem with this.
