### ISSUE TITLE
Extract parameter and model description from scikit-learn docstrings

### ISSUE THREAD

**Issue by mfeurer** [openml/openml-python#175]
and store in the description of the flow or the description of the parameters.

**Comment by PGijsbers** [comment]
As far as I can tell this is not resolved yet, but most work has been done (?).
Parameter meta information can be passed to OpenMLFlow, so I think the goal is to pass this information correctly when creating a flow from a sklearn model. To me it looks like the right place to start this is [here](https://github.com/openml/openml-python/blob/develop/openml/flows/sklearn_converter.py#L360).

**Comment by Neeratyoy** [comment]
@mfeurer it seems that if the str length of a flow description is > 1024, we get an `OpenMLServerException: Problem validating uploaded description file`
Is that expected?

Steps to recreate:
`task = openml.tasks.get_task(403)`
`clf = sklearn.linear_model.SGDClassifier()`
` dummy_str = '-' * 1024`
`f.description = dummy_str`
`f = f.publish()    # this works`
`openml.utils._delete_entity('flow', f.flow_id)`
` dummy_str = '-' * 1025`
`f.description = dummy_str`
`f = f.publish()    # this does not work`

Now w.r.t. this feature request, will not the flow description become excessively large given that sklearn has a good 2-3 line description for each parameter (roughly on an average). This would also entail changing the `__repr__` for OpenMLFlow.

What do you suggest?

**Comment by mfeurer** [comment]
> Is that expected?
Unfortunately, yes.

I'd suggest to store the first 1024 characters of the docstring on OpenML (but always stopping before the "Read more here" or "Parameters"). I don't see a real issue with __repr__ for now. We can change that if this becomes a real issue for users?

**Comment by mfeurer** [comment]
Added via #756
