### ISSUE TITLE
Add useful information in the flow description

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#176]
Currently, no description of flows is added in the XML that is uploaded. Please add as much useful information as possible:
- Link to scikit-learn tutorial?
- Link to documentation of packages used?
- Short textual description of the learning algorithms
- List of involved preprocessing steps with links to further documentation?
- References for further reading?
- Code snippets on how to run the flow in scikit-learn?

You can use markdown (and even math), it will be rendered on the website:
https://github.com/gollum/gollum/wiki

**Comment by mfeurer** [comment]
Related to #175
