### ISSUE TITLE
Drop python2.7 support?

### ISSUE THREAD

**Issue by mfeurer** [openml/openml-python#184]
Python2.7 is already an issue with the liac-arff package, where the latest version on pypi doesn't support python2.7 completely (see #45). Dropping python2.7 probably wouldn't hurt anyone, but make maintenance for us easier. @amueller what do you think?

**Comment by amueller** [comment]
No, I think we should keep it.

**Comment by amueller** [comment]
Sorry I have so many meetings at my new job right now and I get nothing done :-/

**Comment by mfeurer** [comment]
No worries. But could you elaborate for which projects/whom it would be beneficial to keep python2 support?

**Comment by amueller** [comment]
unfortunately many many people are still working with python2.7

**Comment by mfeurer** [comment]
I agree about the second part. But is this also true in academia?

**Comment by amueller** [comment]
yes, totally!

**Comment by mfeurer** [comment]
Okay :(

**Comment by mfeurer** [comment]
@amueller given [your recent sckit-learn](https://github.com/scikit-learn/scikit-learn/issues/11115) issue on this, do you think we can drop python2.7 support now? This would make some pieces of code easier and potentially allow us to use type hints to improve code quality.

**Comment by mfeurer** [comment]
@amueller ping

**Comment by mfeurer** [comment]
Closed via #623
