### ISSUE TITLE
requirements.txt doesn't contain test dependencies

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#185]
we need jupyter_client and maybe nbconvert  I think.

**Comment by mfeurer** [comment]
Shouldn't these rather be added as test dependencies to setup.py?

**Comment by amueller** [comment]
yeah probably. I think the current setup is a bit strange. Maybe get rid of requirements.txt and just declare everything in setup.py?

**Comment by mfeurer** [comment]
requirements.txt is actually parsed by setup.py, so there is no duplication. Is this a weird setup? You've got more experience on how to install python packages properly, I'm usually happy when it somehow works ;) But I'm not opposed to learn how to do it better.

**Comment by amueller** [comment]
I think we don't need a requirements.txt and should encode everything in the setup.py.

**Comment by mfeurer** [comment]
From my experience, this would require the user to first install the dependencies of the dependencies prior to being able to install the package. Is that correct?

**Comment by amueller** [comment]
no. the existence of a ``requirements.txt`` doesn't change anything for dependency resolution.

**Comment by mfeurer** [comment]
True, but since a requirements.txt is installed via pip, it installs one package after the other. If the order is correct, this works out nicely. I wouldn't know how to do this with a setup.py.

**Comment by amueller** [comment]
pip entirely ignores requirements.txt, unless you do ``pip -r requirements.txt``.

**Comment by mfeurer** [comment]
Sorry for being too unspecific, that's what I actually meant. Does that somehow work with only a setup.py as well?
