### ISSUE TITLE
Downloading datasets error

### ISSUE THREAD

**Issue by walterjgsp** [openml/openml-python#190]
When following the documentation to download datasets i get the following erro on the line code _datasets.set_index('did', inplace=True)_ :

KeyError: 'did'

I'm using python 3.5 i don't know if this is an issue when using this version. How can i download the datasets in a different way but also filtering?

Greetings
Walter

**Comment by joaquinvanschoren** [comment]
Hi, 

Try the following:
```
datalist = datasets.list_datasets()
data = pd.DataFrame(datalist).transpose()
data.set_index('did', inplace=True) 
```

At the very least you should do the transpose because the did is not in the columns by default.

**Comment by walterjgsp** [comment]
Thanks, it worked.
