### ISSUE TITLE
Why do we need to transpose the dataset list after download?

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#191]
It seems counter-intuitive that the downloaded list of datasets does not have the dataset id's in the columns. Why don't we do the transpose in the API, before handing it to the user?

**Comment by mfeurer** [comment]
That is an excellent question, I don't know why the original example does not work any more. I can't find anything in the pandas changelog though. Also, I'm surprised that the doctest doesn't work. Anyway, this here seems to be the best solution:

    datasets = openml.datasets.list_datasets()
    datasets = pd.DataFrame.from_dict(datasets, orient='index')

**Comment by joaquinvanschoren** [comment]
Are we going to do anything about this, or leave it as it is?

**Comment by janvanrijn** [comment]
I suggest we discuss this tomorrow, as it seems I will have many time to
work on the Python API

2017-02-26 18:01 GMT+01:00 Joaquin Vanschoren <notifications@github.com>:

**Comment by mfeurer** [comment]
I just tried the following:
```
In [2]: d = {'a': {'c': 0, 'd': 1}, 'b': {'c': 2, 'd': 3}}

In [3]: pd.DataFrame(d)
Out[3]: 
   a  b
c  0  2
d  1  3
```
A potential solution would be:
```
In [4]: d = [{'c': 0, 'd': 1}, {'c': 2, 'd': 3}]

In [5]: pd.DataFrame(d)
Out[5]: 
   c  d
0  0  1
1  2  3
```
which has the drawback that the index column isn't set automatically and the method `list_tasks` would return a list, which cannot be easily accessed. 

Therefore, I propose to leave `pd.DataFrame.from_dict(datasets, orient='index')` in the docs for now until we have a better solution. If you guys find a better solution, please re-open this issue.
