### ISSUE TITLE
number of datasets assertion error 

### ISSUE THREAD

**Issue by omgteam** [openml/openml-python#198]
Due to re.match error in openml/datasets/functions.py line35, self.assertEqual(len(cached_datasets), 2) in openml-python/tests/test_datasets/test_dataset_functions.py will pop error when python setup.py test.

Error:
======================================================================
FAIL: test__list_cached_datasets (tests.test_datasets.test_dataset_functions.TestOpenMLDataset)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/install/openml-python/tests/test_datasets/test_dataset_functions.py", line 34, in test__list_cached_datasets
    self.assertEqual(len(cached_datasets), 2)
nose.proxy.AssertionError: 3 != 2

    '3 != 2' = '%s != %s' % _common_shorten_repr(3, 2)
    '3 != 2' = self._formatMessage('3 != 2', '3 != 2')
>>  raise self.failureException('3 != 2')

Fix: 
    old: 
        if not re.match(r"[0-9]*", directory_name):   ##openml/datasets/functions.py in line 35
     new:
        if re.match(r"[0-9]*", directory_name).group() == "":

**Comment by mfeurer** [comment]
This is fixed by PR #215.
