### ISSUE TITLE
Support for Tagging

### ISSUE THREAD

**Issue by janvanrijn** [openml/openml-python#214]
I will add this for runs and flows (as we need this for study 14), but we might later also need this for datasets and tasks

**Comment by janvanrijn** [comment]
Seems to work well for flows, I added (and updated) it for runs. 

TODO: Test datasets, tasks

**Comment by janvanrijn** [comment]
Added the possibility to tag flows when implicitly creating them. TODO: also add tag when flow already existed

**Comment by amueller** [comment]
Ok so the only thing that's missing is adding tags for existing flows / runs.

**Comment by mfeurer** [comment]
Was added in #355 and #356.
