### ISSUE TITLE
Add doctests to make sure that examples are correct.

### ISSUE THREAD

**Issue by mfeurer** [openml/openml-python#26]

**Comment by joaquinvanschoren** [comment]
Do I need to do something here (serverside)?

**Comment by mfeurer** [comment]
@joaquinvanschoren I just stumbled upon your jupyter example and thought it should be tested as well. These here seem to be the commands to run a notebook from a python script: https://nbconvert.readthedocs.org/en/latest/execute_api.html#module-nbconvert.preprocessors
I don't know how hard it is and I there is no hurry to it so we can try this at the workshop?

Also, could you please add your example to the manual which is located in the source directory?

**Comment by mfeurer** [comment]
The jupyter notebook is tested as well since the workshop. Nevertheless, testing the notebook is rather cumbersome compared to regular python documentation. Also, checking changes/differences in the git repository is hard due to the format. 

@joaquinvanschoren Would you be okay with moving the notebook to a different repository for now? This would be until we figure out how they can be properly tested and we decide how they can complement the documentation. Maybe they are best suited for larger examples?

**Comment by mfeurer** [comment]
Implemented by #321.
