### ISSUE TITLE
Clean up test server after running unit tests

### ISSUE THREAD

**Issue by mfeurer** [openml/openml-python#261]
If a unit test is successful, delete everything it saved on the server. Otherwise, it's hard to have a clean server that is useful for testing purposes. One way to achieve this: add a 'sentinel' string, i.e. a unique random string, to everything that is uploaded. At unit test shutdown time, search for everything with that string and remove it from the server via an API call.

**Comment by Neeratyoy** [comment]
On a successful publish, a new *entity_type/**entity_id*** is generated. On using `openml.utils._delete_entity(entity_type, entity_id)`, the *entity_type/**entity_id*** is no longer available on the test server. 
On re-publishing the same entity again, a new ID is generated, which is the previous ID+1. Is that an acceptable cleanup? Or is the expectation to not increase the file counter, i.e., on deletion, that ID's space will be re-used by subsequent uploads.

**Comment by mfeurer** [comment]
> Is that an acceptable cleanup?

Yes.

**Comment by mfeurer** [comment]
Added by #735.
