### ISSUE TITLE
Correctly handle sparse data

### ISSUE THREAD

**Issue by mfeurer** [openml/openml-python#27]
ATM liac-arff returns a dense `np.ndarray` if the user does not specify that a dataset is sparse.

**Comment by joaquinvanschoren** [comment]
There is an open issue requesting to detect this on the server:
https://github.com/openml/OpenML/issues/162

**Comment by mfeurer** [comment]
According to the unittests it works in branch https://github.com/openml/python/tree/feature/%2327 but I'm not sure whether the server already supports the new tag. Waiting with merge until this is confirmed.

**Comment by mfeurer** [comment]
Should be fixed by #150

**Comment by mfeurer** [comment]
Fixed by #156
