### ISSUE TITLE
Can not create run of same flow with different parameters

### ISSUE THREAD

**Issue by PG-TUe** [openml/openml-python#283]
I want to perform a benchmark of scikit-learn using the OpenML API, after rewriting my script with the newer API, I ran into a problem.
For the benchmark, I want to use the same algorithm multiple times but with different hyperparameter configurations.
I use `run_model_on_task` to have the OpenMLFlow created automatically. 
However, when I use different hyperparameters, it still finds that a run already exists anyway (this is always the same run, regardless of hyperparameters).
Below is a minimal example (in my original script I perform a grid search in a similar way).
```
import openml
from sklearn.naive_bayes import BernoulliNB

task = openml.tasks.get_task('125923')

for (alpha, fit_prior) in [(1.0, False), (10.0, True)]:
	clf = BernoulliNB()
	clf.set_params(alpha=alpha, fit_prior=fit_prior)

	try:
		run = openml.runs.run_model_on_task(task, clf)
		run.publish()
	except Exception as e:
		print(str(e))
```
Which for me gives the output:
```
Run already exists in server. Run id(s): {6023736}
Run already exists in server. Run id(s): {6023736}
```
Depending on your OpenML/sklearn version, the actual output might differ, but in all cases I think it the current behaviour would be that the second run does not get completed because it already exists (because of the first run done). I think that either in the Flow or the Run, the hyperparameters should be considered when creating an identifier (I do not know which way the design would go).

Also, a quick question if I may, is there a way to execute the run without first uploading the flow? I would like to save all files (flows and runs) locally first, and upload them later.

**Comment by janvanrijn** [comment]
This should work:
'''
run = openml.runs.run_model_on_task(task, clf, avoid_duplicate_runs=False)
'''
Let's close the issue when it's documented.

**Comment by PG-TUe** [comment]
Thanks, it does! However do you think it is correct that the same flow with different hyperparameters should be considered a 'duplicate'? I think it would make sense if they would be integrated so I can look up if the exact experiment (including hyperparameters) was done before?

**Comment by janvanrijn** [comment]
It is strange behaviour, this check should take into account the hyperparameters of a classifier. Don't know why it doesn't.

**Comment by PG-TUe** [comment]
That's clear. You may close this issue if you want to document it elsewhere, or leave it open for later reference until it is fixed.

**Comment by janvanrijn** [comment]
I think I have a fix ready. Let's await the unit tests and @mfeurer 's opinion

**Comment by PG-TUe** [comment]
I had a (quick?) question that I hope would be okay to ask here, I can open a new issue if that is preferred.

I was able to perform the runs and locally saw the data_content attribute had information about the CV experiment. However, I now tried to retrieve the run results from the OpenML server, and I can't seem to figure that out. One of the specific runs is [/r/6027977](https://www.openml.org/r/6027977), on the site itself it does not seem to have any evaluations, and when I download the run through the API (using `get_run`), there seems no information about results of the run, just the hyperparameters, there is also no data_content. Is this intended? How should I retrieve the run results properly?

**Comment by janvanrijn** [comment]
data_content contains (part of) the arff information containing predictions
that are being send to the server, and for that reason most users would not
be interested in it.

each run is associated with certain files (predictions.arff,
description.arff) you can retrieve those and get the individual predictions
again.
In one of my latest PR's (get_local_evaluations) I did something similar if
you need an example.




2017-07-21 12:30 GMT+02:00 PG-TUe <notifications@github.com>:

**Comment by PG-TUe** [comment]
Thanks! This allowed me to download the results through the API after all.
