### ISSUE TITLE
Add function to retrieve the types of datasets

### ISSUE THREAD

**Issue by mfeurer** [openml/openml-python#285]
Which can currently only be done via the function `get_data`, which is potentially costly.

**Comment by mfeurer** [comment]
or `get_features_by_type`, but there is no dedicated function to access this data.

**Comment by DieHumbleX** [comment]
Hi, I would like to work on this issue. I am new to OpenML so any extra insight on this issue would be appreciated.

**Comment by joaquinvanschoren** [comment]
@mfeurer: Do you want the data types of the features?
Does that mean just making this function public? Or wrap it in a dedicated function?
https://github.com/openml/openml-python/blob/master/openml/datasets/functions.py#L386

**Comment by mfeurer** [comment]
I think we actually have this functionality [here](https://github.com/openml/openml-python/blob/master/openml/datasets/dataset.py#L79). Sorry for having had this still open? Would you like to work on a different issue?
