### ISSUE TITLE
Feature to run a local model, without the intention to upload it to openml

### ISSUE THREAD

**Issue by janvanrijn** [openml/openml-python#301]
Use case: I want to run my model on the OpenML splits, but have not a single intention of uploading it.

Of course, there is the run_model_on_task function, which party does this, but it always attempts to make a flow. This could be a problem, if some very exotic features are used (e.g.: scipy distributions)

Would be cool to be able to bypass this feature.

**Comment by janvanrijn** [comment]
Current solution:
```
res = openml.runs.functions._run_task_get_arffcontent(optimizer, task, task.class_labels)
run = openml.runs.OpenMLRun(task_id=task.task_id, dataset_id=None, flow_id=None, model=optimizer)
run.data_content, run.trace_content, run.trace_attributes, run.fold_evaluations, _ = res
```
But we should probably make a hard blocking mechanism when some fields are not present, and provide a convenience function that makes this a one-liner.

To be continued.

**Comment by mfeurer** [comment]
I agree this is a use case we want to cover. However, scipy distributions should work. If not, this is a different bug that needs to be addressed.

**Comment by mfeurer** [comment]
Added in #516.
