### ISSUE TITLE
cache mechanism can become corrupt

### ISSUE THREAD

**Issue by janvanrijn** [openml/openml-python#302]
Today, I had the following problem. When loading a task it kept on showing errors. Further inspection led me to the conclusion that this was due to the fact that the task arrived corrupt in the cache. 

We should try to fix this a little bit better, as this is hard to reproduce and due to the error message almost impossible to debug.

**Comment by mfeurer** [comment]
This is somewhat [better handled in the dataset](https://github.com/openml/openml-python/blob/master/openml/datasets/functions.py#L257) and I agree we should add this functionality to all downloads from the web.
