### ISSUE TITLE
runs.list_runs(offset=OFFSET, size=SIZE) raises OpenMLServerException

### ISSUE THREAD

**Issue by minoriinoue** [openml/openml-python#306]
Hi,

As described in the title, runs.list_runs raises an OpenMLServerException error from Sep. 5.
Is there a reason? (I made sure size <= 10000)

![screen shot 2017-09-06 at 17 25 36](https://user-images.githubusercontent.com/16272787/30120242-953d699c-9328-11e7-81b2-118efcb5e798.png)

![screen shot 2017-09-06 at 17 25 18](https://user-images.githubusercontent.com/16272787/30120232-8fe86190-9328-11e7-8895-2ccefaed8e60.png)

Thank you,
Minori

**Comment by mfeurer** [comment]
Thanks for reporting this issue. It appears to be a general openml issue as the server does not return any runs and not an issue of the python API (although I cannot check it because I don't have my password with me). @joaquinvanschoren @janvanrijn could you please have a look at this?

**Comment by janvanrijn** [comment]
Strange, this seems to happen when there are no filters applied. Will look
into this after the AAAI deadline.

2017-09-07 2:55 GMT+02:00 Matthias Feurer <notifications@github.com>:

**Comment by janvanrijn** [comment]
FYI, if you apply filters (e.g., run/list/task/3/limit/100) you can still
obtain results.

2017-09-07 8:30 GMT+02:00 Jan van Rijn <janvanrijn@gmail.com>:

**Comment by minoriinoue** [comment]
Hi @janvanrijn,
Do you know any updates on this issue?

**Comment by janvanrijn** [comment]
I found the problem.

Will be fixed in the course of the day.

2017-09-13 9:37 GMT+02:00 Minori Inoue <notifications@github.com>:

**Comment by minoriinoue** [comment]
@janvanrijn Thanks a lot. Just curious - what was it about?

**Comment by janvanrijn** [comment]
It's a scalability issues of one of the queries.

2017-09-14 11:27 GMT+02:00 Minori Inoue <notifications@github.com>:

**Comment by janvanrijn** [comment]
I just merged the PR. As far as I am concerned, this issue is solved. Please reopen if you think otherwise.

**Comment by minoriinoue** [comment]
Thanks a lot! The api works :)
