### ISSUE TITLE
OpenML based random search

### ISSUE THREAD

**Issue by janvanrijn** [openml/openml-python#307]
It would be good to make an OpenML based random search, storing individual runs on OpenML and obtaining them from OpenML if already performed.

**Comment by mfeurer** [comment]
Agreed, but in my opinion it should live in some other repository, as this isn't core OpenML-python functionality.

**Comment by mfeurer** [comment]
We now the extension interface which makes it possible to do so in an external project.

Also, I'm not sure how up-to-data scikit-optimize still is: https://twitter.com/betatim/status/1118751873035591680

Therefore, I'm closing this for now.

**Comment by mfeurer** [comment]
Please reopen if you disagree.
