### ISSUE TITLE
tasks.get_task(103) raises FileNotFoundError

### ISSUE THREAD

**Issue by minoriinoue** [openml/openml-python#308]
Hi,

I got FileNotFoundError followed by multiple errors on openml.tasks.get_task(103).
task_id = 103 is a result from fetching runs, so it must be a valid task_id.

Looking at an error, it seems I cannot fetch the associated dataset (dataset_id = 45).
openml.datasets.get_dataset(45) raises an error after all as well.

Am I doing something wrong?

![screen shot 2017-09-18 at 14 29 51](https://user-images.githubusercontent.com/16272787/30542349-5be11ecc-9c7f-11e7-8819-538b0ced956a.png)
![screen shot 2017-09-18 at 14 30 16](https://user-images.githubusercontent.com/16272787/30542356-5fce35ec-9c7f-11e7-8440-b3a18df533f1.png)

Thank you,
Minori

**Comment by janvanrijn** [comment]
I would conjecture that this is related to a cache error (see also #302)

Could you erase your cache and check whether it works? We will make a fix
for this ASAP (probably during OpenML 2017 @ Lorentz).

2017-09-18 14:42 GMT+02:00 Minori Inoue <notifications@github.com>:

**Comment by minoriinoue** [comment]
Thanks for quick reply!

I deleted the cache, but I got the same error.

**Comment by janvanrijn** [comment]
Just making sure.. did you delete All the cache? What happened in my case
was that the task cache was fine and the dataset cache that should be
linked was broken.

**Comment by minoriinoue** [comment]
Sorry I was ambiguous. 

I deleted the entire ~/.openml/cache directory since when I just deleted ~/.openml/cache/tasks I got the error. However (even if I deleted the entire ~/.openml/cache directory and thus had only config directory under .openml directory), I got the same error.

**Comment by mfeurer** [comment]
I opened issue #324 with a more general description of the problem.
