### ISSUE TITLE
Dataset_id required on dataset creation

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#311]
When I want to upload a new dataset, I can create an OpenMLDataset and then publish it.
However, the creation of an OpenMLDataset requires a dataset_id.

This does not make sense when uploading a new dataset. I could just add dataset_id='1', but that is still confusing since it will be entirely ignored.

**Comment by joaquinvanschoren** [comment]
My code. Remove dataset_id from the list of parameters to see the error.

```
oml.config.server = 'https://test.openml.org/api/v1'
my_data = oml.datasets.OpenMLDataset(data_file='data/ram_price.arff', name='RAM_Price', description='This is a test.', version='1', tag='test', format='ARFF', licence='Public', visibility='public', dataset_id='1')
response = my_data.publish()
```

**Comment by mfeurer** [comment]
@ArlindKadra could you please check whether this is solved by #440?

**Comment by ArlindKadra** [comment]
@mfeurer https://github.com/openml/openml-python/blob/46033459b0a3491273fa819cf9e882b250f49063/openml/datasets/dataset.py#L35

**Comment by mfeurer** [comment]
Thanks @ArlindKadra
