### ISSUE TITLE
api call contains file reading

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#339]
I don't think we need to read files for doing any API calls. I think right now it's only used in the dataset upload, I'm not sure if that's actually good.
Do we want to store arffs on disk for uploading a dataset?

**Comment by ArlindKadra** [comment]
I have opened issue #442 regarding this topic. Currently the dataset class contains a path to the arff file and when a call is made to upload, the file is read from the path and then uploaded.
To tackle this, we already opened #440 and an upload_dataset function was added which does not read the files from a path but instead uploads the file directly.
The implementation in the dataset class is still intact until we figure out how we want to progress with @mfeurer .

**Comment by ArlindKadra** [comment]
Solved in #440
