### ISSUE TITLE
be lazy in downloading datasets and splits

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#346]
I think the get_dataset and get_task functions should not download any big items. That allows you to inspect the attributes of the data without having to download possibly large amounts of data.

We can just download the data in the ``get_data`` method - similarly, in ``get_task`` we shouldn't download the splits, but only download them later when they are needed.

**Comment by mfeurer** [comment]
Functionality for lazy downloading of datasets added in #644, `get_task` still needs a download flag.

**Comment by mfeurer** [comment]
Functionality for lazy downloading of tasks added in #659.
