### ISSUE TITLE
Best way to load arff data?

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#35]
I downloaded a dataset from OpenML and wanted to load it in pandas. What is the best way to do this?
If I use the get_arff() function, for some reason the class values are not included, even though they are in the arff file stored in disk. Maybe I have the wrong arff reader installed?

```
dataset = openml.download_dataset(61)
iris = dataset.get_arff()
iris = pd.DataFrame(iris['data'], columns=[attribute[0] for attribute in iris['attributes']])
print(iris[:10])
   sepallength  sepalwidth  petallength  petalwidth  class
0          5.1         3.5          1.4         0.2      0
1          4.9         3.0          1.4         0.2      0
2          4.7         3.2          1.3         0.2      0
3          4.6         3.1          1.5         0.2      0
4          5.0         3.6          1.4         0.2      0
```

**Comment by joaquinvanschoren** [comment]
Ok, I should use get_dataset().
```
X, y = dataset.get_dataset(target=dataset.default_target_attribute)
```

To load it in pandas I can do something like:
```
X, y, attribute_names = dataset.get_dataset(target=dataset.default_target_attribute, return_attribute_names=True)
iris = pd.DataFrame(X, columns=attribute_names)
iris['class'] = y
```

This does seem to replace the class names with an index (0,1,...). How can I get the class labels efficiently?

**Comment by zardaloop** [comment]
I don't know much about it but the quick fix for this would be to replace 
`iris['class'] = y`
to
`iris['class'] = [attribute_names[index] for index in y]`  :smile:

**Comment by joaquinvanschoren** [comment]
Attribute_names has the feature names, not the class labels. There is a
separate function in API connector that gets the class labels, but it seems
to download the dataset and load the arff from disk again...

**Comment by mfeurer** [comment]
The reason for this is that the arff loader either encodes all nominals as integers or no nominals as integers. Because I did not see a reason why one would need the actual names of the class labels, it encodes all nominals, see [here](https://github.com/openml/python/blob/master/openml/entities/dataset.py#L115). What's actually the reason why you want the labels?

The functionality you mention was  build in by because we did not see another way of obtaining the labels I think. It came to my mind now that we could not only pickle the actual dataset, but also the attribute description of the arff loader, which would allow you to query the labels. Would that help?

**Comment by joaquinvanschoren** [comment]
One simple use case is data visualization in Python. You may want to show
the labels there. Or maybe I want to compute some statistics on class
distribution and show the results with the labels. Moreover, if I build a
decision tree I may want the class labels to show up in tree if I visualize
it.

Your suggestion sounds good. I would ideally just like to ask the dataset
object to give me the class labels.

**Comment by mfeurer** [comment]
The reason why I don't really like querying the dataset object is because it shouldn't know whether it is a classification dataset or not...But I think there is no other way...I can work on this earliest on Monday.

**Comment by mfeurer** [comment]
I've added a potential solution which allows the user to query the attribute labels. Does this help?

**Comment by mfeurer** [comment]
I'm closing this now as the requested functionality is available and there has been no new posts for more than a year.
