### ISSUE TITLE
datasets only read single tag

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#354]
there can be multiple tags, right now we only read the first.

**Comment by Bilgecelik** [comment]
Hey, this should work.
![capture](https://user-images.githubusercontent.com/38037323/38309082-e9bcafae-3810-11e8-9fae-85bf464f37a2.JPG)

**Comment by mfeurer** [comment]
Can confirm this:
```python
import openml as oml
dataset = oml.datasets.get_dataset(2)
print(dataset.tag)
```
results in 
```
['study_1', 'study_14', 'study_34', 'study_37', 'study_41', 'study_70', 'study_76', 'uci']
```
Thanks @Bilgecelik for checking this.
