### ISSUE TITLE
benchmark analysis pipeline

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#360]
Analyzing multiple runs or evaluations takes a long time, even if they have been cached.
I'm not sure if it's the caching or the xml parsing or what's happening.

Example:
```python
import numpy as np
import openml
openml100_tasks = openml.tasks.list_tasks(tag="openml100")
res = []

for task in openml100_tasks:
    evaluations = openml.evaluations.list_evaluations("area_under_roc_curve", task=[task], size=10000)
    best_auc = np.median([ev.value for ev in evaluations.values()])

    print(task, best_auc)
    res.append([task, best_auc])
```

**Comment by amueller** [comment]
actually there's no caching for ``list_evaluations` so this doesn't actually work....

**Comment by mfeurer** [comment]
You could run this stuff in parallel with joblib?

**Comment by amueller** [comment]
better: I could cache it with joblib :) well maybe both!
