### ISSUE TITLE
Return tables as dataframes

### ISSUE THREAD

**Issue by mfeurer** [openml/openml-python#364]
#363 adds pandas as a dependency and in the tutorials we convert dicts of dicts to dataframes anyway, therefore we could simply return some properties as dataframes. @amueller @janvanrijn what's your opinion on this?

**Comment by PGijsbers** [comment]
Should we close this issue as this is possible because of #548, or after the release of 0.9 when dataframes are returned by default?

**Comment by mfeurer** [comment]
Nope, this is for function like `list_dataset` which could naturally be represented as dataframes. Check [this example](https://openml.github.io/openml-python/master/examples/datasets_tutorial.html#sphx-glr-examples-datasets-tutorial-py) to see which lines could be saved by returning dataframes by default. 

However, I should not decide this by myself. @janvanrijn @joaquinvanschoren @amueller @PGijsbers @ArlindKadra any comments/agreements/disagreements?

**Comment by joaquinvanschoren** [comment]
I would like to have the option to get a dataframe directly. It makes some code a lot shorter and cleaner.

**Comment by PGijsbers** [comment]
I'm also in favor of (adding the option of) returning a dataframe. I am probably in favor of making it the new default behavior. With pandas becoming the main format of representing (data of the) datasets, it makes sense to also represent the different views with a dataframe.

**Comment by janvanrijn** [comment]
Agreed.
