### ISSUE TITLE
add list_dataset filters

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#369]
The OpenML list_datasets call allows to filter datasets by number or instances, features, classes, and missing values, but this is not yet supported by the python API.
https://www.openml.org/api_docs/#!/data/get_data_list_filters

Can we please add this?
Also see openml/OpenML#496

**Comment by ArlindKadra** [comment]
@joaquinvanschoren are there any other filters following the ones mentioned above ? @mfeurer should we control the filters names and their values ?  In case there are only the filters above, I can use regex to not allow illegal values.

**Comment by mfeurer** [comment]
Could you try whether the server returns a helpful error message in case the filter is illegal? If yes, there is no need to handle this in python code.

**Comment by janvanrijn** [comment]
The server does, right? 

See, e.g., https://www.openml.org/api/v1/data/list/illegal/123

**Comment by mfeurer** [comment]
Awesome, now @ArlindKadra only needs to figure out whether it prints nicely in python.

**Comment by ArlindKadra** [comment]
@janvanrijn @mfeurer The reply from the server is descriptive and nice. In the case of illegal filter values though on the production server you get a no results error and on the test server you get a database error. Do we want this outcome ?
https://www.openml.org/api/v1/data/list/number_features/ta
https://test.openml.org/api/v1/data/list/number_features/ta

**Comment by mfeurer** [comment]
I think it should be something like illegal argument error. Could you please post an image @ArlindKadra ?

**Comment by ArlindKadra** [comment]
![openml](https://user-images.githubusercontent.com/24679211/37487787-e7f291b2-2892-11e8-994d-21275fd2169e.png)
![openmltest](https://user-images.githubusercontent.com/24679211/37487791-eb16ab30-2892-11e8-98ed-1bccbfd26945.png)

**Comment by mfeurer** [comment]
Added in #424 .
