### ISSUE TITLE
Different behaviour among users in tasks.get_task(TASKID)

### ISSUE THREAD

**Issue by minoriinoue** [openml/openml-python#370]
Hi,

I have a friend who is using OpenML, and he got this KeyError although I don't get this error (Error screenshot attached).
1. Why are there difference in the behaviour?
2. How can he get the data properly?

Just to clarify - he tried deleting his cache in ~/.openml and also tried making an API call multiple times when the initial call failed.

Best,
Minori
![screen shot 2017-10-20 at 10 41 41](https://user-images.githubusercontent.com/16272787/31812523-8f0aea40-b583-11e7-8c26-e72c69835e21.png)

**Comment by joaquinvanschoren** [comment]
I wonder whether this is a server bug; we do return some qualities without values:
https://www.openml.org/api/v1/data/qualities/50

Let me do a quick fix

**Comment by mfeurer** [comment]
That might be one part of the issue, the other part might be that your fried uses a newer release (0.6.0). He/She could copy the changes from [this commit](https://github.com/openml/openml-python/commit/9e7f812f130cf6821ba9a798d7444a99561687e4) to temporarily solve the issue.

**Comment by joaquinvanschoren** [comment]
I now made sure we don't return qualities without a value.
Please clear your cache and try again. If it doesn't work, it's probably not the server, and you should try @mfeurer's solution

**Comment by PGijsbers** [comment]
Closing this as it seems solved in the recent version and this issue has been stale.
