### ISSUE TITLE
supported types in runs/function.py, tuple as supported type missing

### ISSUE THREAD

**Issue by bstrang** [openml/openml-python#373]
# model dependent attributes for trace arff
    for key in model.cv_results_:
        if key.startswith('param_'):
            # supported types should include all types, including bool, int float
            supported_types = (bool, int, float, six.string_types)
            if all(isinstance(i, supported_types) or i is None for i in model.cv_results_[key]):
                type = 'STRING'
            else:
                raise TypeError('Unsupported param type in param grid')

            # we renamed the attribute param to parameter, as this is a required
            # OpenML convention
            attribute = ("parameter_" + key[6:], type)
            trace_attributes.append(attribute)
    return trace_attributes

**Comment by janvanrijn** [comment]
@bstrang please be informed that the PR is merged. Still tuple values are not allowed, but you can insert them as list of integers (and they will be treated as tuples)

**Comment by mfeurer** [comment]
@bstrang @janvanrijn can this be closed?

**Comment by janvanrijn** [comment]
Please leave it open for one more week, I'll try to think of the suggested unit test that we both couldn't remember anymore
