### ISSUE TITLE
python 2.7, openml 0.6.0, UnicodeError, tasks/functions.py

### ISSUE THREAD

**Issue by bstrang** [openml/openml-python#378]
While trying to get task with tid 34536 - a Unicode Error occure. ascii codec (of python 2.7) cannot encode character u'\xae'. 
python 3.6 OK.
[unicode-ascii-34536.zip](https://github.com/openml/openml-python/files/1485331/unicode-ascii-34536.zip)

**Comment by mfeurer** [comment]
@bstrang should be fixed. Please reopen if it's still broken.
