### ISSUE TITLE
Unicode Error Occurs in Python 3

### ISSUE THREAD

**Issue by chengrunyang** [openml/openml-python#381]
I am having some trouble reading OpenML datasets due to UnicodeDecodeError in a newly installed Python 3 environment. 

The code is:
`dataset=openml.datasets.get_dataset(5)`
`data_numeric,data_labels,categorical = dataset.get_data(target=dataset.default_target_attribute,return_categorical_indicator=True)`
The error information is:
![unicode error](https://user-images.githubusercontent.com/8860197/33235856-93515658-d210-11e7-9605-a306fcf0374e.png)

Thanks!

**Comment by mfeurer** [comment]
I cannot reproduce this. Did you use the OpenML connector with a different python version before?

**Comment by chengrunyang** [comment]
Yes. There was no such problem in Python 2.x.

**Comment by mfeurer** [comment]
I still cannot reproduce this. Could you please give some details on your OS? Also, is the pickle file maybe a leftover from your python2.x installation? There might be an issue opening it in python3.

**Comment by chengrunyang** [comment]
It is MacOS Sierra v10.12.6. Do you have any hints on the path of the pickle file OpenML is using? I am using Anaconda3 Python, though, thus if it loads the pickle file from my Python3 installation, then this might not be the cause of the problem.

**Comment by mfeurer** [comment]
They should be in a directory called `.openml` in your home directory. If you previously created the pickle files with python 2.7 and are now loading them with python 3 that can cause an issue.

**Comment by joaquinvanschoren** [comment]
You can also just delete the .openml directory. It will be recreated.

**Comment by chengrunyang** [comment]
Deleting the cache directory works. Thanks!
