### ISSUE TITLE
Job is waiting/stucked after task 3567 (collins)

### ISSUE THREAD

**Issue by vchouksey** [openml/openml-python#387]
Guys,

My jobs have been waiting quite long time for next task after completing task 3561, does task 3567 takes long time to run or this is file lock issue or i am doing something wrong?

Task which have finished/ completed:
vishalnayanshi@ubuntu:~/.openml/cache/tasks$ ls
11  15  20    21   23  29    3022  3481  3493  3512  3560  3573  41  49  6
12  16  2074  219  24  3     31    3485  3494  3543  3561  36    43  53
14  18  2079  22   28  3021  32    3492  3510  3549  3567  37    45  58
 
Task already finished: 3561 (/home/vishalnayanshi/experiments/defaults/random_forest/vanilla/3/random_forest/vanilla/6/random_forest/vanilla/11/random_forest/vanilla/12/random_forest/vanilla/14/random_forest/vanilla/15/random_forest/vanilla/16/random_forest/vanilla/18/random_forest/vanilla/20/random_forest/vanilla/21/random_forest/vanilla/22/random_forest/vanilla/23/random_forest/vanilla/24/random_forest/vanilla/28/random_forest/vanilla/29/random_forest/vanilla/31/random_forest/vanilla/32/random_forest/vanilla/36/random_forest/vanilla/37/random_forest/vanilla/41/random_forest/vanilla/43/random_forest/vanilla/45/random_forest/vanilla/49/random_forest/vanilla/53/random_forest/vanilla/58/random_forest/vanilla/219/random_forest/vanilla/2074/random_forest/vanilla/2079/random_forest/vanilla/3021/random_forest/vanilla/3022/random_forest/vanilla/3481/random_forest/vanilla/3485/random_forest/vanilla/3492/random_forest/vanilla/3493/random_forest/vanilla/3494/random_forest/vanilla/3510/random_forest/vanilla/3512/random_forest/vanilla/3543/random_forest/vanilla/3549/random_forest/vanilla/3560/random_forest/vanilla/3561/run.xml)
[2017-12-21 15:40:20] Obtained task 3567 (collins); 24.0 attributes; 500.0 observations
Pipeline(steps=[('imputation', ConditionalImputer(axis=0, categorical_features=[19, 20], copy=True,
          fill_empty=0, missing_values='NaN', strategy='median',
          strategy_nominal='most_frequent', verbose=0)), ('hotencoding', OneHotEncoder(categorical_features=[19, 20], dtype=<class 'numpy.float6...estimators=10, n_jobs=1, oob_score=False, random_state=1,
            verbose=0, warm_start=False))])
{}
**Task already finished: 3567 (/home/vishalnayanshi/experiments/defaults/random_forest/vanilla/3/random_forest/vanilla/6/random_forest/vanilla/11/random_forest/vanilla/12/random_forest/vanilla/14/random_forest/vanilla/15/random_forest/vanilla/16/random_forest/vanilla/18/random_forest/vanilla/20/random_forest/vanilla/21/random_forest/vanilla/22/random_forest/vanilla/23/random_forest/vanilla/24/random_forest/vanilla/28/random_forest/vanilla/29/random_forest/vanilla/31/random_forest/vanilla/32/random_forest/vanilla/36/random_forest/vanilla/37/random_forest/vanilla/41/random_forest/vanilla/43/random_forest/vanilla/45/random_forest/vanilla/49/random_forest/vanilla/53/random_forest/vanilla/58/random_forest/vanilla/219/random_forest/vanilla/2074/random_forest/vanilla/2079/random_forest/vanilla/3021/random_forest/vanilla/3022/random_forest/vanilla/3481/random_forest/vanilla/3485/random_forest/vanilla/3492/random_forest/vanilla/3493/random_forest/vanilla/3494/random_forest/vanilla/3510/random_forest/vanilla/3512/random_forest/vanilla/3543/random_forest/vanilla/3549/random_forest/vanilla/3560/random_forest/vanilla/3561/random_forest/vanilla/3567/run.xml)**

**Comment by joaquinvanschoren** [comment]
@janvanrijn @mfeurer There is definitely something wrong with those run.xml paths, right?
@vchouksey You can speed up experiments by setting n_jobs=-1 but I'm more worried about those paths.

**Comment by janvanrijn** [comment]
Can you give a MWE of your code?

**Comment by vchouksey** [comment]
path have been creating with below **for loop**:
output_dir=os.path.expanduser('~') + '/experiments/defaults'
output_save_folder_suffix = '/vanilla'

for task_id in study.tasks:
    task = openml.tasks.get_task(task_id)
    output_dir = output_dir + '/' + classifier + output_save_folder_suffix + '/' + str(task_id)

I am still following similar steps of your openmlpimp library program https://github.com/janvanrijn/openml-pimp/blob/master/openmlpimp/generatedata/run_default.py 

only difference is i am made code in jupyter notebook each line in new cell and setting up below values rather args parser.

all_classifiers = ['random_forest']
output_dir=os.path.expanduser('~') + '/experiments/defaults'
study_id=14
openml_apikey='6beed8d7f35c545f51ba389ba80c24d3'
classifier='random_forest'
fixed_parameters = None

**Comment by mfeurer** [comment]
@vchouksey what OS are you using?

**Comment by vchouksey** [comment]
ubuntu 16.04 LTS

**Comment by vchouksey** [comment]
same issue still happening is that big task id 3481
<img width="1283" alt="screen shot 2018-01-05 at 13 27 45" src="https://user-images.githubusercontent.com/6507341/34609292-69d9a07e-f21c-11e7-896c-be09dc4b382d.png">

**Comment by vchouksey** [comment]
My job has been getting killed automatically, see screenprint
<img width="1282" alt="screen shot 2018-01-05 at 13 32 48" src="https://user-images.githubusercontent.com/6507341/34609660-d5826508-f21d-11e7-92c6-e548a74435c5.png">

**Comment by vchouksey** [comment]
This issue can be close, This issue was happening because of small RAM(1 GB) of my virtual environment when I increase to 6 GB it perfectly runs without any issue.

**Comment by joaquinvanschoren** [comment]
Good. 
But what about those weird paths? Is that a bug in openmlpimp?

**Comment by mfeurer** [comment]
@joaquinvanschoren please open an issue in the [OpenML PIMP issue tracker](https://github.com/janvanrijn/openml-pimp/issues) to discuss paths in OpenML PIMP.

**Comment by joaquinvanschoren** [comment]
OK, if you're sure it's not a openml-python bug :)

**Comment by mfeurer** [comment]
openml-python does not store runs if that's actually the issue.
