### ISSUE TITLE
Documentation organization

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#389]
I've been looking into how to integrate the OpenML documentation.
I see two issues with the current documentation of openml-python:

* It has a lot of top-level menus. I cannot show this top navigation bar if I would pull this into the main OpenML website. I can solve this with CSS (basically force the navigation bar to show up as an extra left menu), but I'm not sure whether that's ideal. Would it make sense to merge the Start, UserGuide, and Progress pages into one large page? The API can remain separate.

* The API docs don't navigate nicely. Whenever you click on a specific function, e.g.:
http://openml.github.io/openml-python/dev/generated/openml.datasets.get_dataset.html#openml.datasets.get_dataset

you loose the structured left menu with the other functions. You have to start all the way from the top by clicking 'API' again. Is there a way to fix that with sphinx? 

Actually, the API navigation seems broken: openml.datasets is listed under Top-level Classes, while openml.runs is under Functions, and openml.evaluations is under a second Functions header??

**Comment by mfeurer** [comment]
I'm not sure if I can give a satisfactory answer here because I don't have any clue how the HTML/CSS behind the documentation works. If you plan to integrate this into OpenML, maybe we can create a design and navigation free version which you can include? This raises the overall question: How do you want to implement this? Also, the API navigation is fine, the line breaking is broken.

**Comment by joaquinvanschoren** [comment]
Implemented now. See https://test.openml.org/guide
I'm only pulling in the API docs and User Guide sections. If you can organize everything in those two sections, that would be great.

To me, the API sidebar navigation is still broken. Are you seeing the same thing as me?

<img width="278" alt="screen shot 2018-02-07 at 00 37 42" src="https://user-images.githubusercontent.com/1724503/35890251-3ca705d2-0b9f-11e8-8be5-9bf7d06692d6.png">

**Comment by joaquinvanschoren** [comment]
Never mind that navigation issue.
Merging the installation and user guide would still be great!
