### ISSUE TITLE
Allow to list tasks by dataset

### ISSUE THREAD

**Issue by mfeurer** [openml/openml-python#393]
That's the API call we need to invoke: https://github.com/openml/OpenML/issues/759

**Comment by ArlindKadra** [comment]
Already in there.
https://github.com/openml/openml-python/blob/bd85d5e5fc86d6293ff34397acbda3b6cd904e1a/openml/tasks/functions.py#L113

https://github.com/openml/openml-python/blob/bd85d5e5fc86d6293ff34397acbda3b6cd904e1a/openml/tasks/functions.py#L143

**Comment by mfeurer** [comment]
Fixed in #533
