### ISSUE TITLE
caching (server dependent)

### ISSUE THREAD

**Issue by janvanrijn** [openml/openml-python#397]
How about prefixing the caching directories with the inversed URL of the server? Many problems have occurred because we are confusing cache items from the test server with live cache items. This could easily be fixed 

In the java connector this is fixed by prefixing the cache directory with the inversed server url, e.g. .openml/cache/org/openml/www/datasets, etc

**Comment by mfeurer** [comment]
Great idea!

**Comment by mfeurer** [comment]
After rethinking this a bit, could you please comment on this @janvanrijn ?

The different toolboxes should store the same information (i.e. xml files). If they don't, that might be a bug.

**Comment by janvanrijn** [comment]
Can you elaborate? I don't see why that is a strict requirement.

Ideally, yes, but this requires a big effort.
I wouldn't mind making several changes to the java lib if that unifies matters, would be best to do when we're all together (including representative of mlr)

**Comment by mfeurer** [comment]
It isn't, we just decided to that once upon a time. Still, how can the files differ if only xml files are stored?

**Comment by janvanrijn** [comment]
it's about the directory structure. This one is different in java (I actually prefer the Python directory structure). Also, the pickled files can of course not be red in java and R. 

However, let's discuss that in a different topic. The issue that is raised in this one is that 99% of our (the devs) cache problems come from using cache across servers (test and production). This is something that can be solved fairly easy (in fact, I already did so in the Java lib).

**Comment by mfeurer** [comment]
Sorry for getting side-tracked and talking about something completely different. We should actually check back with the R guys whether they think this is a good idea (I definitely do!) and then also update the docs/Wiki.

@giuseppec @berndbischl

**Comment by giuseppec** [comment]
Good point, I also ran into that problem several times...

**Comment by berndbischl** [comment]
i think if we plan and communicate that change properly, we can easily do that

**Comment by mfeurer** [comment]
As long as we use the solution proposed by @janvanrijn the two approaches won't interfere with each other so we would gradually update the different packages?

**Comment by mfeurer** [comment]
I just added a PR in #432.
