### ISSUE TITLE
Document "how to work with tasks"

### ISSUE THREAD

**Issue by mfeurer** [openml/openml-python#4]
Add an example similar to http://openml.readthedocs.org/en/latest/#working-with-datasets

**Comment by mfeurer** [comment]
@joaquinvanschoren will this be done by your jupyter notebook?

**Comment by joaquinvanschoren** [comment]
It is. There is an example in that notebook that lists tasks, downloads a
task, and runs a scikit learner on it. I even extended the package to make
this work nicer (although it can still be improved a lot).

**Comment by mfeurer** [comment]
Okay, so I could change the documentation to point to the jupyter notebook which demonstrates its use and then close this issue? Or is the notebook still work in progress and we should wait with that?

**Comment by joaquinvanschoren** [comment]
It is OK to close this issue. The notebook is definitely a work in progress
but we can add stuff to it as we implement more features :).

**Comment by mfeurer** [comment]
Then I'll close it once I updated the documentation.

**Comment by mfeurer** [comment]
Progress can be watched in new branch [docs/usage](https://github.com/openml/openml-python/tree/docs/usage)

**Comment by PGijsbers** [comment]
It seems this issue is resolved by now, as the [Python Guide](https://openml.github.io/OpenML/Python-guide/) covers listing tasks, downloading tasks and running a scikit-learn algorithm on it.
