### ISSUE TITLE
models

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#406]
Why are we calling the input here a 'model'?
https://github.com/openml/openml-python/blob/develop/openml/runs/functions.py#L43

Is it not an estimator? Am I confused? :)

**Comment by mfeurer** [comment]
It should be `estimator` in scikit-learn speech.

**Comment by PGijsbers** [comment]
Especially with the new general extension updates, I think `model` should stay preferred over `estimator`. Feel free to re-open if it needs to be discussed.
