### ISSUE TITLE
Getting non-encoded dataset

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#408]
If I import, for instance, the adult dataset: https://www.openml.org/d/1590
`get_data` automatically encodes categorical features:
```
dataset = oml.datasets.get_dataset(1590) # Adult dataset
X, y, attribute_names = dataset.get_data(target=dataset.default_target_attribute, 
    return_attribute_names=True)
data = pd.DataFrame(X, columns=attribute_names)
display(data.head())
```
->'education' is encoded as numbers

Is there a way to get the original non-encoded features, so I can look at them with pandas?

Thanks!

**Comment by mfeurer** [comment]
No, there isn't. I wrote that part before knowing how nicely pandas could do the job here. That would be a great feature! Related to #364 and #257.

**Comment by mfeurer** [comment]
Should be possible with the latest merge of #548. Please reopen if this is not the case.
