### ISSUE TITLE
Example: restrict dataset and tasks

### ISSUE THREAD

**Issue by mfeurer** [openml/openml-python#41]
RST example which shows how to get a list of dataset and task IDs with specific properties.

**Comment by mfeurer** [comment]
Progress can be watched in new branch [docs/usage](https://github.com/openml/openml-python/tree/docs/usage)

**Comment by CatarinaAmaral** [comment]
Hey @mfeurer! Can you explain better what you mean by specific properties?

**Comment by mfeurer** [comment]
This is actually documented by now.
