### ISSUE TITLE
get_dataset crashes if the dataset does not have all qualities computed

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#415]
Here's a screenshot of this happening: https://ibb.co/nppTYS

It should be reproducible using any dataset that has data qualities with NULL values, e.g.:

```
oml.datasets.get_dataset(3)
```
On my system this doesn't occur, maybe it is a windows-specific issue.

PS. You can't use dataset 512 to reproduce this since I'm using it for an assignment. I had to manually remove the NULL qualities, and will put them back when this is fixed.

**Comment by janvanrijn** [comment]
Can you please check and confirm if the "empty" value tag fixes this problem? It should be on production server

**Comment by mfeurer** [comment]
I have observed this issue, too, but only when using the Master branch and not the development branch.

**Comment by PGijsbers** [comment]
Can confirm that right now it is reproducible in master but not develop.
This should be fixed in [3dcc087](https://github.com/openml/openml-python/commit/3dcc0874a61f53001ea76e878a893597807f3958#diff-ba5e66c898a59d9f8fca4a850f601196) as far as I can tell.
