### ISSUE TITLE
arfftrace_attributes / unsupported param type in param grid

### ISSUE THREAD

**Issue by bstrang** [openml/openml-python#416]
cf. also issue 373: 
tuple as parametertype is missing. 
list of integer has been added to branch fix373, but tuple has been removed.

    # model dependent attributes for trace arff
    for key in model.cv_results_:
        if key.startswith('param_'):
            # supported types should include all types, including bool, int float
            supported_types = (**bool, int, float, six.string_types**)
            if all(isinstance(i, supported_types) or i is None for i in model.cv_results_[key]):
                type = 'STRING'
            else:
                raise TypeError('Unsupported param type in param grid')

**Comment by janvanrijn** [comment]
One of the conclusions was that for the neural network layer specification, instead of a tuple you can also specify a list of integers

There was one question from @mfeurer that I have to follow up on, before we merge the PR fixing #373 . Will investigate today. I will close this one for now
