### ISSUE TITLE
Store run to disk fn

### ISSUE THREAD

**Issue by janvanrijn** [openml/openml-python#422]
Stores a version of the OpenMLRun object to disk (either pickle or using the run.xml, predictions.arff and trace.arff. The later is probably better but requires engineering when extending the supported task types )

**Comment by mfeurer** [comment]
Do you want runs to be cached when a user downloads them or should they be saved to disk when a user locally creates a run by calling `run_model_on_task`? The outcome of the latter one can be stored by the user manually and I'm not sure if openml-python should automatically do this.

**Comment by janvanrijn** [comment]
I am talking about the latter. I agree that openml-python should not automatically do this, but we could offer a convenience function, as this is something that I do in many of my projects (and it makes more sense to have this someplace central)

**Comment by mfeurer** [comment]
@janvanrijn can this be closed due to #459?

**Comment by janvanrijn** [comment]
No. #459 actually introduced a bug (due to a bug in liac arff) and a new pr (waiting for review) intends to kind of solve this

**Comment by mfeurer** [comment]
Closing this as it appears to be added. Please reopen @janvanrijn if that's not correct.

**Comment by janvanrijn** [comment]
You are correct.
