### ISSUE TITLE
no pypi package?

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#425]
I didn't realize there is no pypi package... Is there a particular reason? Just not really stable enough? I feel like we could probably do one now.

**Comment by mfeurer** [comment]
That's actually a milestone and there are only a few issue missing before I think we can go for this: https://github.com/openml/openml-python/issues?q=is%3Aopen+is%3Aissue+milestone%3Apip-release

**Comment by mfeurer** [comment]
Here we go: https://pypi.org/project/openml/

I see this rather as a soft launch release because the readme and documentation aren't good enough yet, but at least its on pypi now.

**Comment by janvanrijn** [comment]
Awesome! 

Installing works for me

**Comment by joaquinvanschoren** [comment]
Oh my god, this makes me so happy 😄

**Comment by joaquinvanschoren** [comment]
Did a PR for updating the installation instructions:
https://github.com/openml/openml-python/pull/456
