### ISSUE TITLE
Add simple instruction / snipet to openml python interface website

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#43]
I think the python api here:
http://www.openml.org/guide/#!python

should have the pip command to install the package form github, and like 5 lines to train a scikit-learn classifier on a specific data set.
I guess we should do that after the API is solid, but I think it's very important for adoption.

**Comment by joaquinvanschoren** [comment]
Completely agree

**Comment by mfeurer** [comment]
We just added the usage snipet in #434. The installation and developer friendliness is now issue #443.
