### ISSUE TITLE
Why do we copy Flow fields instead of using retrieved Flow?

### ISSUE THREAD

**Issue by PGijsbers** [openml/openml-python#437]
When automatically performing a Flow on a Task, we need to get information about the Flow from the server, if it exists there already. If it exists, we retrieve this information from the server and copy it to our local flow object [here](https://github.com/openml/openml-python/blob/master/openml/runs/functions.py#L88).

Why do we not use the Flow we get from `get_flow`, but rather copy its information?

Pinging @mfeurer since it looks like he added it [here](https://github.com/openml/openml-python/commit/8fadddc94b9f9fd67ea762669ba2f8ff19357873#diff-c3572202d96b5ba039ed83b96041cb44).

**Comment by mfeurer** [comment]
That's the PR which introduced this behavior: https://github.com/openml/openml-python/pull/253/files

And that's part of the reasoning behind it: https://github.com/openml/openml-python/pull/253#discussion_r116740318

If you could do a PR which explains the reasoning here in form of a comment, that would be appreciated.

**Comment by mfeurer** [comment]
For me it's fine if you add it to the regression PR.

**Comment by PGijsbers** [comment]
Alright, I'll do that.
