### ISSUE TITLE
Uploading datasets

### ISSUE THREAD

**Issue by ArlindKadra** [openml/openml-python#442]
Hey all, 
I am working with dataset uploading and I stumbled upon something. 

https://github.com/openml/openml-python/blob/f618d816d540b033368453a50a13b76423e43adc/openml/datasets/dataset.py#L373-L397

The function publish() in the OpenMLDataset makes use of the xml description of a dataset and an arff file to upload a dataset at OpenML. However in the way that the class is implemented right now, **self.data_file** is a string containing the path to the dataset file.

In my opinion we should have a method that takes the description and the arff file as an argument at openml.datasets at the functions module.

Something like:
`publish_dataset(description, file)`

What is your opinion regarding this?

**Comment by janvanrijn** [comment]
Short version of the answer (from phone) I agree. 

Slightly longer: dataset class is a little complicated ATM and contains many things that it shouldn't have imo, e.g. reference to features, qualities, maybe even splits? Ideally this should all be decoupled (might be a bit hard, I never wanted to start this)

**Comment by mfeurer** [comment]
I agree that the class is a bit complicated, but I disagree on that it shouldn't contain the features and qualities. This makes it easy for a user to access all kinds of things related to datasets. It does not contain the splits, these are in the task.

**Comment by mfeurer** [comment]
I believe this is now implemented in #440.
