### ISSUE TITLE
Do not leave files after running unit tests

### ISSUE THREAD

**Issue by mfeurer** [openml/openml-python#447]
Currently, the unit tests leave a few files. This clutters the development directory and makes it harder to keep an overview in git.

**Comment by rth** [comment]
That would be fairly straightforward with pytest https://github.com/openml/openml-python/issues/327

**Comment by Neeratyoy** [comment]
Hi,
On taking a preliminary look at `openml/testing.py`, the `setUp()` and `tearDown()` does a neat job of creating a temp directory and cleaning it up. It works.
However, all the excess files which show up untracked for git, are in the directory `test/files/`.
In that case, can I use `os.walk()` before and after the testing, to look for new files that were not there in this directory and get them cleaned? If not, can someone just nudge me to see where and how `test/files` is getting updated? 

I do need to take a deeper look but pytest still seems to have a related open [issue](https://github.com/pytest-dev/pytest/issues/1120), so this might need some book-keeping and forced deletions.

**Comment by mfeurer** [comment]
@Neeratyoy I'm afraid that the current implementation does not work, i.e. it changes the working directory before running the tests, executing the 2nd `git status` outside of the git repository. Could you please create a new PR fixing this?

**Comment by Neeratyoy** [comment]
Sure, I'll take a look at this.

**Comment by Neeratyoy** [comment]
@mfeurer could you please guide me as to how I can test this locally?
When I execute `bash ci_scripts/test.sh`, or even check `echo $TEST_DIR` at the beginning of `run_tests()`, it gives a `mkdir: missing operand` error. The result of `echo $TEST_DIR` is blank.
How can I recreate locally how CI runs this?

>  executing the 2nd `git status` outside of the git repository.

Can I in that case store the current directory `` curr_dir=`pwd` `` and before the second `git status` execute `cd $curr_dir` ?

**Comment by mfeurer** [comment]
> How can I recreate locally how CI runs this?

That's tricky. The easiest solution would be to do `export TEST_DIR=/tmp/test/` prior to running bash ci_scripts/test.sh.

> Can I in that case store the current directory curr_dir=`pwd` and before the second git status execute cd $curr_dir ?

That sounds like a good solution.

**Comment by mfeurer** [comment]
Added in #721.
