### ISSUE TITLE
make repo pip-installable.

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#45]
Currently I can't install this repo with pip because of the dependency liac-arff>=2.1.1dev.
I think that can be fixed by pointing to the repo.

**Comment by mfeurer** [comment]
The solution is to add the flag `--process-dependency-links` as explained [here](http://stackoverflow.com/a/38043585). Not sure about the solution, maybe I should put my for of liac-arff on pypi? Or dropping python2.7 support?

**Comment by mfeurer** [comment]
Sorry for realizing this only now, but this is actually fixed. This one works:

    pip install git+https://github.com/openml/openml-python@develop

Next stop: dropping the link!
