### ISSUE TITLE
add read-only api key for testing

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#47]

**Comment by amueller** [comment]
It seems really weird to me that running tests upload something to the website. It will also mean that there will be infinitely many iris runs very soon.
So either we should have a read-only public api key for the tests, or users should get a read-only api key they can use for testing.

**Comment by mfeurer** [comment]
travis-ci now uses a read-only key.

**Comment by joaquinvanschoren** [comment]
Can this be closed now?

**Comment by PGijsbers** [comment]
Yes (after consulting @mfeurer).
