### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by LishengSun** [openml/openml-python#472]
Hello,

I just tried to install openml following the instructions here: https://openml.github.io/openml-python/stable/index.html#how-to-get-openml-for-python.
1) I clone github repo : ok
2) I got a new directory 'openml-python' (no 'python' as mentioned), I enter 'python setup.py install' but I got this error:

> Processing dependencies for openml==0.7.0
Searching for oslo.utils>=3.33.0
Reading https://pypi.python.org/simple/oslo.utils/
Downloading https://files.pythonhosted.org/packages/69/21/bde1fb98e77a0b4d82585c3808e13bfeff28917fb4f7af2f8a0e56530355/oslo.utils-3.36.2.tar.gz#sha256=9900be2bc8bf14c187731393dea672ea9579312d6f31b862e527999fde63f2c6
Best match: oslo.utils 3.36.2
Processing oslo.utils-3.36.2.tar.gz
Writing /var/folders/l2/7nm8thsj2kz3cwsrl9njdz6r0000gn/T/easy_install-vhf3GQ/oslo.utils-3.36.2/setup.cfg
Running oslo.utils-3.36.2/setup.py -q bdist_egg --dist-dir /var/folders/l2/7nm8thsj2kz3cwsrl9njdz6r0000gn/T/easy_install-vhf3GQ/oslo.utils-3.36.2/egg-dist-tmp-0BJdI4
creating /Users/lishengsun/anaconda/lib/python2.7/site-packages/oslo.utils-3.36.2-py2.7.egg
Extracting oslo.utils-3.36.2-py2.7.egg to /Users/lishengsun/anaconda/lib/python2.7/site-packages
Adding oslo.utils 3.36.2 to easy-install.pth file

> Installed /Users/lishengsun/anaconda/lib/python2.7/site-packages/oslo.utils-3.36.2-py2.7.egg
Searching for oslo.i18n>=3.15.3
Reading https://pypi.python.org/simple/oslo.i18n/
Downloading https://files.pythonhosted.org/packages/cc/8d/9514c0f979c858fcbf3c8300769f8323d5c69c20cffe3543059e978329cd/oslo.i18n-3.20.0.tar.gz#sha256=c3cf63c01fa3ff1b5ae7d6445d805c6bf5390ac010725cf126b18eb9086f4c4e
Best match: oslo.i18n 3.20.0
Processing oslo.i18n-3.20.0.tar.gz
Writing /var/folders/l2/7nm8thsj2kz3cwsrl9njdz6r0000gn/T/easy_install-fHztqT/oslo.i18n-3.20.0/setup.cfg
Running oslo.i18n-3.20.0/setup.py -q bdist_egg --dist-dir /var/folders/l2/7nm8thsj2kz3cwsrl9njdz6r0000gn/T/easy_install-fHztqT/oslo.i18n-3.20.0/egg-dist-tmp-0dEetP
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/Users/lishengsun/anaconda/lib/python2.7/site-packages/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/Users/lishengsun/anaconda/lib/python2.7/site-packages/pbr/util.py", line 251, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config, script_args)
  File "/Users/lishengsun/anaconda/lib/python2.7/site-packages/pbr/util.py", line 385, in setup_cfg_to_setup_kwargs
    cmd = cls(dist)
  File "/Users/lishengsun/anaconda/lib/python2.7/site-packages/setuptools-27.2.0-py2.7.egg/setuptools/__init__.py", line 137, in __init__
    _Command.__init__(self, dist)
  File "/Users/lishengsun/anaconda/lib/python2.7/distutils/cmd.py", line 59, in __init__
    raise TypeError, "dist must be a Distribution instance"
TypeError: dist must be a Distribution instance
error: Setup script exited with error in setup command: Error parsing /private/var/folders/l2/7nm8thsj2kz3cwsrl9njdz6r0000gn/T/easy_install-fHztqT/oslo.i18n-3.20.0/setup.cfg: TypeError: dist must be a Distribution instance

Thank you in advance for your help!

**Comment by joaquinvanschoren** [comment]
Hi Lisheng, 

We recently created a release on pypi, could you try 'pip install openml' instead?

**Comment by LishengSun** [comment]
Yes it works now! Thank you very much Joaquin!

**Comment by mfeurer** [comment]
We'll update the installation instructions soon. Keep tuned!
