### ISSUE TITLE
Liac-arff: Sparse ARFF / ARFF stored in same way

### ISSUE THREAD

**Issue by janvanrijn** [openml/openml-python#487]
The following [line of code](https://github.com/openml/openml-python/blob/master/openml/datasets/dataset.py#L113) attempts to distinguish sparse arff from regular arff. 
(FFR, the openml-python code)
```
if isinstance(data['data'], tuple):
  X = data['data']
  X_shape = (max(X[1]) + 1, max(X[2]) + 1)
  X = scipy.sparse.coo_matrix((X[0], (X[1], X[2])), shape=X_shape, dtype=np.float32)
  X = X.tocsr()
elif isinstance(data['data'], list):
  X = np.array(data['data'], dtype=np.float32)
```

However, when executing the [following test](https://github.com/renatopp/liac-arff/blob/master/tests/test_loads.py) from the liac-arff reader, the sparse arff and regular arff are internally represented the same. 

Am I missing something or does this deprecate the line of code that checks for tuples, and stores them as csr matrices? 

@amueller relevant for sklearn openml loader

**Comment by mfeurer** [comment]
Are you referencing `test_sparse_input`? The arff reader is not tasked to return a format for sparse data and therefore returns a simple list of lists. Check out the signature of the decode function: `def decode(self, s, encode_nominal=False, return_type=DENSE):`. By changing the `return_type` you can change the format returned by liac-arff.

To answer your other question: The code is somewhat confusing, so I created a PR in #489. Also, the decoding happens in the following piece of code where you can see the differences:
```
        if format.lower() == 'arff':
            return_type = arff.DENSE
        elif format.lower() == 'sparse_arff':
            return_type = arff.COO
        else:
            raise ValueError('Unknown data format %s' % format)

        def decode_arff(fh):
            decoder = arff.ArffDecoder()
            return decoder.decode(fh, encode_nominal=True,
                                  return_type=return_type)

        if filename[-3:] == ".gz":
            with gzip.open(filename) as fh:
                return decode_arff(fh)
        else:
            with io.open(filename, encoding='utf8') as fh:
                return decode_arff(fh)
```

**Comment by janvanrijn** [comment]
makes sense now, thanks!

**Comment by ArlindKadra** [comment]
Adding a minimal example:
```
SPARSE_ARFF = '''% XOR Dataset
@RELATION XOR
@ATTRIBUTE input1 REAL
@ATTRIBUTE input2 REAL
@ATTRIBUTE y REAL
@DATA
{0 0}
{1 1.0, 2 1.0}
{0 1.0, 2 1.0}
{0 1.0, 1 1.0}
'''

import arff
from pprint import pprint

decoder = arff.ArffDecoder()
d = decoder.decode(SPARSE_ARFF, encode_nominal=True, return_type=arff.DENSE)
pprint(d)
d = decoder.decode(SPARSE_ARFF, encode_nominal=True, return_type=arff.COO)
pprint(d)
```
Output:
```
{'attributes': [('input1', 'REAL'), ('input2', 'REAL'), ('y', 'REAL')],
 'data': [[0.0, 0.0, 0.0], [0.0, 1.0, 1.0], [1.0, 0.0, 1.0], [1.0, 1.0, 0.0]],
 'description': 'XOR Dataset',
 'relation': 'XOR'}
{'attributes': [('input1', 'REAL'), ('input2', 'REAL'), ('y', 'REAL')],
 'data': ([0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
          [0, 1, 1, 2, 2, 3, 3],
          [0, 1, 2, 0, 2, 0, 1]),
 'description': 'XOR Dataset',
 'relation': 'XOR'}
```
