### ISSUE TITLE
How to extract/pull OpenML Dataset MetaFeatures like skewness, kurtosis, class entropy

### ISSUE THREAD

**Issue by vchouksey** [openml/openml-python#495]
#### Description
Example: How to extract/pull OpenML Dataset MetaFeatures like skewness, kurtosis, class entropy 

#### Steps/Code to Reproduce
status_type = 'active'
openml_list = oml.datasets.list_datasets(status=status_type) # Returns a dict
datalist = pd.DataFrame.from_dict(openml_list, orient='index') # Transform to pandas
datalist = datalist[datalist.name.str.contains('diabetes')]
datalist

#### Expected Results
Example: Skewness, kurtosis, class entropy

#### Actual Results
Please paste or specifically describe the actual output or traceback.

did | name | format | status | MajorityClassSize | MaxNominalAttDistinctValues | MinorityClassSize | NumberOfClasses | NumberOfFeatures | NumberOfInstances | NumberOfInstancesWithMissingValues | NumberOfMissingValues | NumberOfNumericFeatures | NumberOfSymbolicFeatures
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
37 | diabetes | ARFF | active | 500 | -1.0 | 268 | 2 | 9 | 768 | 0 | 0 | 8 | 1

#### Versions
Linux-3.13.0-153-generic-x86_64-with-debian-jessie-sid
Python 3.6.2 |Anaconda custom (64-bit)| (default, Jul 20 2017, 13:51:32) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
NumPy 1.13.3.10
SciPy 1.0.0.0
Scikit-Learn 0.19.0
OpenML 0.7.0

**Comment by joaquinvanschoren** [comment]
The metafeatures are called qualities in OpenML and they are included in the dataset description:
```
import openml
d = openml.datasets.get_dataset(2)
d.qualities
```
```
{'AutoCorrelation': 0.6064659977703456,
 'CfsSubsetEval_DecisionStumpAUC': 0.9067742570970945,
 'CfsSubsetEval_DecisionStumpErrRate': 0.13251670378619154,
 'CfsSubsetEval_DecisionStumpKappa': 0.6191022730108037,
 'CfsSubsetEval_NaiveBayesAUC': 0.9067742570970945,
 'CfsSubsetEval_NaiveBayesErrRate': 0.13251670378619154,
...}
```

Next, just select the ones you need:
```
qs = d.qualities
[(key, value) for key, value in qs.items() if 'Kurtosis' in key]
```
```
[('MaxKurtosisOfNumericAtts', 13.215477213878724),
 ('MeanKurtosisOfNumericAtts', 4.6480244352098286),
 ('MinKurtosisOfNumericAtts', -0.9723842038435437),
 ('Quartile1KurtosisOfNumericAtts', -0.40305022089010156),
 ('Quartile2KurtosisOfNumericAtts', 1.6372437439142264),
 ('Quartile3KurtosisOfNumericAtts', 12.741748058445403)]
```

**Comment by PGijsbers** [comment]
I am closing this because it seems that no further help is required.
