### ISSUE TITLE
Unclear function documentation and warning

### ISSUE THREAD

**Issue by ArlindKadra** [openml/openml-python#498]
https://github.com/openml/openml-python/blob/5a1048d9087677b6a2d62d9e044a6c00d37795f0/openml/runs/functions.py#L52-L94

I was checking out this function and it confused me. 
https://github.com/openml/openml-python/blob/5a1048d9087677b6a2d62d9e044a6c00d37795f0/openml/runs/functions.py#L62
There is no model parameter, there is a flow and it is an OpenMLFlow.
https://github.com/openml/openml-python/blob/5a1048d9087677b6a2d62d9e044a6c00d37795f0/openml/runs/functions.py#L67
I am guessing it should be changed from second to first argument, as this is the second one ?
https://github.com/openml/openml-python/blob/5a1048d9087677b6a2d62d9e044a6c00d37795f0/openml/runs/functions.py#L93-L94
It seems wrong. It was OpenMLTask and OpenMLFlow, now it is reversed. The warning should display "It should be (flow, task) and not (task, flow) "?

If I understood things clearly, I can make a pull request with the minor changes.

**Comment by ArlindKadra** [comment]
On a further note, I will also update the examples tutorial following the Deprecation.

**Comment by mfeurer** [comment]
Yes, the parameter documentation is wrong. Line 67 can be removed in the future. Your note on the warning is correct, too.

**Comment by mfeurer** [comment]
Added via #516.
