### ISSUE TITLE
Nominal features values

### ISSUE THREAD

**Issue by PidgeyUsedGust** [openml/openml-python#507]
#### Description
The `nominal_values` field of a feature is left unpopulated, see [here](https://github.com/openml/openml-python/blob/7a612eaece2fd28315d99dda3e2393ada2f27478/openml/datasets/dataset.py#L84). The data seems to be available trough [REST](https://www.openml.org/api/v1/json/data/features/2?api_key=).

#### Steps/Code to Reproduce
Example:
```python
import openml
dataset = openml.datasets.get_dataset(2)
print(dataset.features[0].nominal_values)
```

#### Expected Results
`["GB","GK","GS","TN","ZA","ZF","ZH","ZM","ZS"]`

#### Actual Results
`None`

#### Versions
```
Darwin-17.7.0-x86_64-i386-64bit
Python 3.6.5 (default, Apr  5 2018, 10:39:42) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
NumPy 1.14.2
SciPy 1.0.1
Scikit-Learn 0.19.2
OpenML 0.7.0
```
-

**Comment by janvanrijn** [comment]
I recently added this field to the database. Any PR should also check whether there is an error in the dataset record (also newly displayed) as this can mean that the nominal features were not correctly retrieved

**Comment by maxcopeland** [comment]
hi @janvanrijn, mind if I work on this?

**Comment by mfeurer** [comment]
Functionality added in #644.
