### ISSUE TITLE
Looking for the definition of a Run

### ISSUE THREAD

**Issue by dmartinez05** [openml/openml-python#509]
#### Description
I have involved in another project about AutoML (https://gitlab.com/datadrivendiscovery/d3m), and I have been trying to find a reference for how the run is created (schema), so we can try to find a way to translate our pipeline(https://gitlab.com/datadrivendiscovery/d3m/blob/devel/d3m/metadata/schemas/v0/pipeline.json) language to the run one.

Also, I am not sure whether or not is possible to create a run that does not follow a straight line.

**Comment by mfeurer** [comment]
A run is created by instantiating a [run object](https://github.com/openml/openml-python/blob/master/openml/runs/run.py). Currently, only a [helper function](https://github.com/openml/openml-python/blob/master/openml/runs/functions.py) is able to do this.

However, I think you're talking about a flow (implementation of an algorithm). A flow can be created by instantiating a [flow object](https://github.com/openml/openml-python/blob/master/openml/flows/flow.py). You can find the schema in [this xsd file](https://github.com/openml/OpenML/blob/master/openml_OS/views/pages/api_new/v1/xsd/openml.implementation.upload.xsd). The current status on this can be found [here](https://github.com/openml/OpenML/wiki/Flow-Serialization).

I hope this helps.

**Comment by PGijsbers** [comment]
Closing this as it seems no further assistance is required.
