### ISSUE TITLE
No way to see splits for tasks in web interface

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#513]
Looking at the website it's impossible to see what the validation strategy for a given task is, from what I can tell.

**Comment by mfeurer** [comment]
I assume you wanted to post this in the main issue tracker?

Nevertheless, I think you're looking for information on the [submit subpage](https://www.openml.org/t/31#!submit).

**Comment by amueller** [comment]
Yes I did. What's the submit subpage?

**Comment by mfeurer** [comment]
If you look at the task page, you can see that it has multiple subpages (different tabs are on the right hand side). The link I posted brings you to a subpage which contains the information you asked for.
