### ISSUE TITLE
run_model_on_task has no docs, run_flow_on_tasks docs are wrong

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#515]
See [here](https://github.com/openml/openml-python/blob/7a612eaece2fd28315d99dda3e2393ada2f27478/openml/runs/functions.py#L37) and [here](https://github.com/openml/openml-python/blob/7a612eaece2fd28315d99dda3e2393ada2f27478/openml/runs/functions.py#L58).

The ``run_flow_on_task`` actually needs a flow, not a model, from what I can see.

**Comment by ArlindKadra** [comment]
I referenced the second part here #498 and I have not done a commit yet as there is also some additional functionality to be added into the function.

**Comment by mfeurer** [comment]
Added via #516.
