### ISSUE TITLE
sklearn tests connect to live server

### ISSUE THREAD

**Issue by janvanrijn** [openml/openml-python#520]
when running the test in flow/test_sklearn.py, it automatically connects to the server that is configured in the config file. This seems like a mistake

**Comment by janvanrijn** [comment]
I think correct behavior is: test cases connect to test server, unless the test case opts to connect to the live server. 

config file should play no factor in the unit tests, right?

**Comment by mfeurer** [comment]
`test_sklearn` should not connect to the server in the first place. However, I cannot reproduce such behavior locally. Which test are you talking about exactly?

**Comment by janvanrijn** [comment]
Agreed, I (unnecessarily) added a get task to the code. 

Still, it seems weird that default behavior is connecting to the server depicted in the config file?

**Comment by PGijsbers** [comment]
Oudated. Right now the [default behavior](https://github.com/openml/openml-python/blob/develop/openml/testing.py#L78) is to connect to the test server, unless explicitly specified.
