### ISSUE TITLE
Running tests requires matplotlib

### ISSUE THREAD

**Issue by rth** [openml/openml-python#530]
As part of pytest migration in https://github.com/openml/openml-python/pull/527, it looks like matplotlib is hard dependency for running tests, despite what `setup.py` requirements, and `CONTRIBUTING.md` says. 

It is imported in https://github.com/openml/openml-python/blob/7a612eaece2fd28315d99dda3e2393ada2f27478/tests/test_examples/test_OpenMLDemo.py#L5 but doesn't seem to be used (added in https://github.com/openml/openml-python/pull/430).

Is it required by nbformat?

An alternative could be to skip corresponding tests.

**Comment by mfeurer** [comment]
We used to have a jupyter notebook as an example which used matplotlib. In the last few weeks, we replaced it by multiple small python examples and removed the plotting for the moment. The notebook was unit tested, and I guess we can remove that unit test for now. Do you want to create a PR for this?

**Comment by PGijsbers** [comment]
With many issues open on the same topic, I decided to close this one. All further discussion can be had in #596.
