### ISSUE TITLE
No unit test for create_dataset

### ISSUE THREAD

**Issue by ArlindKadra** [openml/openml-python#537]
#### Description
https://github.com/openml/openml-python/blob/8786457531e2aefd41e49b73a76d0869089bdbd8/openml/datasets/functions.py#L356
Function does not have a unit test. Although an example usage is located into the develop docs.

**Comment by mfeurer** [comment]
Fixed by #539.

**Comment by mfeurer** [comment]
No, it's actually not...

**Comment by mfeurer** [comment]
but I really don't think we need one as this is simply one function call.

**Comment by ArlindKadra** [comment]
> but I really don't think we need one as this is simply one function call.

@mfeurer yes, but since we thought it would be the main way that a user would choose to create a dataset, I think it should be tested.

**Comment by ArlindKadra** [comment]
@mfeurer sorry, I put a missleading title and function line.
