### ISSUE TITLE
Improve dataset uploading

### ISSUE THREAD

**Issue by mfeurer** [openml/openml-python#540]
Reviewing PR #539 which tests dataset uploading, I found four things which we could improve to make dataset uploading nicer for the user:

1. There should be no necessity to provide the format as this will always be `'arff'`.
2. The current example encodes the class label as a `REAL`, although it should actually be a categorical.
3. We could add an example for uploading a list of lists, which could then also contain strings and categories.
4. The function `create_dataset` should be imported into the `openml.datasets` namespace.

@ArlindKadra @glemaitre

**Comment by mfeurer** [comment]
After discussion with @ArlindKadra @joaquinvanschoren there are some more open points:

1. we need to check if the data is sparse and change the data format accordingly.
2. we need an example regarding the upload of sparse data
3. we need a unit test regarding the upload of sparse data

**Comment by glemaitre** [comment]
> we need to check if the data is sparse and change the data format accordingly.

Do you want to change the format depending if the user pass an array (dataframe) or a sparse array (dataframe)?

**Comment by glemaitre** [comment]
I think this is OK. It is what I did in the loading stage https://github.com/openml/openml-python/pull/548

**Comment by amueller** [comment]
is ``create_datasets`` listed in the api docs? I can't see any docs on uploading datasets at all :-/

**Comment by ArlindKadra** [comment]
There is a tutorial at the docs -> user guide section. Check the docs at
/develop/ instead of dev. We have to remove the old dev folder as the
documentation is being deployed differently.

**Comment by amueller** [comment]
ah, I was looking at /develop/

**Comment by amueller** [comment]
even more off-topic: is there a reason the example gallery is not in the top level menu and that progress and changelog link to the same thing?

**Comment by amueller** [comment]
the create_dataset is still missing from the API docs

**Comment by amueller** [comment]
#553 #554 #556

**Comment by mfeurer** [comment]
This was fixed by #547
