### ISSUE TITLE
Contrast code snippet on website

### ISSUE THREAD

**Issue by glemaitre** [openml/openml-python#551]
I don't know if you had some user already mentioning it but IMO the color contrast (background/code) of the code snippet on the website is pretty low. It makes it difficult to distinguish the code from the comments. Am I the only one having trouble?

**Comment by mfeurer** [comment]
Thank you for bringing this up. So far no one has mentioned this, but I can see how this is problematic. Unfortunately, I am not familiar with sphinx and the sphinx_bootstrap_theme package which reformats the website to look more modern. It would be great if someone with with knowledge of these packages (and knowledge of color usage and design) could look into this.

**Comment by mfeurer** [comment]
Thanks to @PGijsbers we'll have more contrast in a few minutes (once travis finishes the next few builds). Please re-open if it is still hard to read.

**Comment by PGijsbers** [comment]
Make sure to check out the `develop` pages: https://openml.github.io/openml-python/develop/

**Comment by glemaitre** [comment]
Thanks guys for taking about that. This really readable now.
