### ISSUE TITLE
make develop default branch?

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#555]
I think the default branch should be develop since people shouldn't do PRs against master, right?

![image](https://user-images.githubusercontent.com/449558/46107022-4b7dc400-c1a8-11e8-8a4a-836a83b6f7f0.png)

**Comment by glemaitre** [comment]
+1 :)

**Comment by janvanrijn** [comment]
I agree as well. Can't count the number of times I created the PR against the wrong branch.

**Comment by PGijsbers** [comment]
![image](https://user-images.githubusercontent.com/15890747/56144570-50229200-5fab-11e9-9f7f-1dfc54725037.png)
Done!
