### ISSUE TITLE
OpenML Parameter to Sklearn Parameter and vice versa

### ISSUE THREAD

**Issue by janvanrijn** [openml/openml-python#564]
Currently missing functions, I would like to add them and I think they would belong in this library

**Comment by mfeurer** [comment]
Could you please be a bit more specific? I don't really understand this issue.

**Comment by janvanrijn** [comment]
Hyperparameters in our eco-system have generally three names. Take for example a pipeline with a decision tree (called: tree). Let's consider the `min_samples_leaf` hyperparameter.

The parameter name is `min_samples_leaf`
The scikit-learn name is `tree__min_samples_leaf`
The openml name is `sklearn.trees.DecisionTree(1)_min_samples_leaf` (or, one could argue that this hyperparameter can be uniquely identified by a flow id and a hyperparameter name)

I want to make a function that maps the openml hyperparameter name to a scikit-learn hyperparameter name (just realized the other way around is a little bit more complicated, because of version numbers)

**Comment by mfeurer** [comment]
Added via #564 by @janvanrijn
