### ISSUE TITLE
unexpected result of get_task_list

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#57]
It gets all of the classification tasks. If we want to rate limit, maybe getting all of one type is not good. If we don't care about server load, I think we should get all tasks.

**Comment by mfeurer** [comment]
Sorry, I don't get this issue. @janvanrijn changed the get_task_list function such that you can pass different arguments, see [here](https://github.com/openml/openml-python/blob/develop/openml/tasks/functions.py#L92). Does this fix this issue?

**Comment by mfeurer** [comment]
To my understanding this issue is solved and I will close it now because it stalled for more than half a year. @amueller if you disagree, please reopen.
