### ISSUE TITLE
Rename X,y to features, labels

### ISSUE THREAD

**Issue by mfeurer** [openml/openml-python#570]
As suggested here: https://github.com/openml/openml-python/pull/547#discussion_r225066702

**Comment by mfeurer** [comment]
Hey, that sounds great. We'll hopefully get #547 merged today or tomorrow, @glemaitre do you think we can get #545 merged quickly afterwards? Then the two biggest PRs would be done and his should be feasible without too many breaking changes. Also, I totally agree that you should strive to rename all variables and not just the public ones.

**Comment by glemaitre** [comment]
>  @glemaitre do you think we can get #545 merged quickly afterwards

Yes right after #547. I just need to address the missing point and merge conflict. I actually need the PR to upload some dataset :)

**Comment by PGijsbers** [comment]
Cool! :) I'll try to keep an eye on it, but a ping here after the merges is appreciated!

**Comment by PGijsbers** [comment]
I noticed both PRs have been merged, so I will start working on it now.

**Comment by mfeurer** [comment]
Hey, yes, the development branch currently has one failing unit test. @janvanrijn promised to fix this throughout the next days (as this requires quite a lot of work). However, it should be safe to ignore this unit test for renaming the attributes.

**Comment by PGijsbers** [comment]
I'm unassigning myself. I'll happily still do it (when I have time, e.g. in the hackathon), but I figured if someone else (new) wants to pick this up, that is fine too. The idea of me picking this up was so I could get myself familiar with the code again, but that point is moot as I had to get into things for last week's PRs.

**Comment by skubatur** [comment]
Can I be assigned to this one?

**Comment by PGijsbers** [comment]
Thanks for wanting to contribute! We wrote contribution guidelines [here](https://github.com/openml/openml-python/blob/master/CONTRIBUTING.md) and if you have any other questions feel free to ask :) Looking forward to your PR.

**Comment by skubatur** [comment]
> Thanks for wanting to contribute! We wrote contribution guidelines [here](https://github.com/openml/openml-python/blob/master/CONTRIBUTING.md) and if you have any other questions feel free to ask :) Looking forward to your PR.

So, to re-iterate what needs to be done. We are renaming X to features, and y to labels. 
In the following cases:

-  local variables in examples 
-  function names
-  local variables in functions
-  docstrings of said functions

Correct?

**Comment by PGijsbers** [comment]
@mfeurer Where do you stand on this nowadays? I don't have a preference (as long as its all lower-case ;) )

**Comment by mfeurer** [comment]
Thanks @skubatur for picking this up.

I don't have a strong preference. I'm wondering what a good name for `X` would be, though. I wouldn't call it features as this doesn't imply we're talking about data. I'm also not 100% sure about calling it data as the observations y is also data. @amueller @PGijsbers @glemaitre

**Comment by PGijsbers** [comment]
The selection of which feature is the target is in some sense also arbitrary. I don't really care as long as it is consistent and lower case.

**Comment by PGijsbers** [comment]
We have decided that for now we do not want to rename the variables anymore.
