### ISSUE TITLE
create_dataset function is absent from openml.datasets.functions in OpenML 0.7.0

### ISSUE THREAD

**Issue by Motorrat** [openml/openml-python#578]
#### Description
`create_dataset` function is absent from `openml.datasets.functions` in OpenML 0.7.0
yet it is referenced in the tutorial https://openml.github.io/openml-python/develop/_downloads/cfed637ede9071636ff8da65fe73607a/create_upload_tutorial.py
https://openml.github.io/openml-python/develop/examples/create_upload_tutorial.html

#### Steps/Code to Reproduce
`pip install openml`
or 
```
git clone https://github.com/openml/openml-python.git
python setup.py install
```

```
python
import openml
from openml.datasets.functions import create_dataset
```

#### Expected Results
No error is thrown. 

#### Actual Results

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: cannot import name 'create_dataset'

`dir(openml.datasets.functions)`

> ['DATASETS_CACHE_DIR_NAME', 'OpenMLCacheException', 'OpenMLDataset', 'OpenMLHashException', 'OpenMLServerException', 'OrderedDict', 'PrivateDatasetError', '__builtins__', '__cached__', '__doc__', '__file__', '__list_datasets', '__loader__', '__name__', '__package__', '__spec__', '_create_cache_directory', '_create_cache_directory_for_id', '_create_dataset_from_description', '_create_lockfiles_dir', '_get_cached_dataset', '_get_cached_dataset_arff', '_get_cached_dataset_description', '_get_cached_dataset_features', '_get_cached_dataset_qualities', '_get_cached_datasets', '_get_dataset_arff', '_get_dataset_description', '_get_dataset_features', '_get_dataset_qualities', '_list_cached_datasets', '_list_datasets', '_remove_cache_dir_for_id', 'check_datasets_active', 'get_dataset', 'get_datasets', 'hashlib', 'io', 'list_datasets', 'lockutils', 'openml', 'os', 're', 'shutil', 'six', 'xmltodict']

#### Versions

> Python 3.6.6 (default, Sep 12 2018, 18:26:19) 
> [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import platform; print(platform.platform())
> Linux-4.15.0-36-generic-x86_64-with-Ubuntu-18.04-bionic
> >>> import sys; print("Python", sys.version)
> Python 3.6.6 (default, Sep 12 2018, 18:26:19) 
> [GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
> >>> import numpy; print("NumPy", numpy.__version__)
> NumPy 1.15.2
> >>> import scipy; print("SciPy", scipy.__version__)
> SciPy 1.1.0
> >>> import sklearn; print("Scikit-Learn", sklearn.__version__)
> Scikit-Learn 0.20.0
> >>> import openml; print("OpenML", openml.__version__)
> OpenML 0.7.0
>

**Comment by AndriyMulyar** [comment]
For anyone else coming across this:
`pip install git+https://github.com/openml/openml-python.git@develop`

**Comment by PGijsbers** [comment]
Closing this issue as `create_dataset` is present in the 0.8 release.
