### ISSUE TITLE
Refactoring: Use Enums for task types

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#585]
#### Description
We currently handle task-type specific logic in if-else statements using the task type ID's, like:

```
    if task.task_type_id == 3:
        do_something()
    else:
        do_something_else()
```

This is very hard to read/maintain and likely to lead to unexpected behavior. 
It would be a lot nicer to replace this by enums, so that we can write:
```
if task.task_type_id == TaskTypeEnum.LEARNING_CURVE:
       do_something()
``` 

One question is where to put the enum definition. Maybe in utils or otherwise in task.py and then imported wherever it is needed.

#### Steps/Code to Reproduce
This happens throughout the codebase, mainly in tasks and runs.
Example:
https://github.com/openml/openml-python/blob/master/openml/runs/functions.py#L115

#### Versions
All versions.

Note that Enums are native in python 3.4+, but have been backported into python 2.7:
https://stackoverflow.com/questions/36932/how-can-i-represent-an-enum-in-python

IIUC, we would need an extra dependency (enum34) as long as we support python 2.7.

**Comment by PGijsbers** [comment]
It looks like the current code base makes uses of enums (or the class hierarchy), rather than 'magic numbers'. Please re-open if I am mistaken.
