### ISSUE TITLE
Documentation is somehow ambiguos.

### ISSUE THREAD

**Issue by dmartinez05** [openml/openml-python#590]
#### Description
You can see here:
 https://github.com/openml/openml-python/blob/master/openml/runs/functions.py#L920

It is not very clear what kind of arguments the function is expecting, even that it is a list for the `flow` part, it is not clear whether or not is expecting a list of flows, or a list of flows_id.

#### Expected Results
It would be even better if typing could be added.

**Comment by mfeurer** [comment]
Thanks for reporting this. Would you like to contribute an improved documentation of this function (and maybe other ambiguously documented functions)?

> It would be even better if typing could be added.

We'll add typing information gradually after our next release (more specifically, we'll do one more python2 compatible release and then move to python3 only, which support type annotations).

**Comment by dmartinez05** [comment]
Sure, I can work on that.

**Comment by dmartinez05** [comment]
Also, which is the devel branch? or which one should I use?

**Comment by joaquinvanschoren** [comment]
It's called 'develop' :)
We usually start a new subbranch of develop for every change, and then do a PR into the develop branch.

**Comment by PGijsbers** [comment]
I removed @dmartinez05 due to inactivity on this issue. If you are still working on this, or would like to start working on this, please re-assign yourself :)

**Comment by mfeurer** [comment]
This appears to be fixed as we use type annotations everywhere. Also, the actual docstrings of the listings calls are improved and say that the arguments should be passed as a list.

Please reopen if this is incorrect.
