### ISSUE TITLE
Cannot run example code for adding dataset

### ISSUE THREAD

**Issue by AndriyMulyar** [openml/openml-python#593]
#### Description
API returns this error to openml-python:
`openml.exceptions.OpenMLServerException: https://www.openml.org/api/v1/xml/data/ returned code 131: Problem validating uploaded description file`

When running create_dataset with 'develop' branch installed. I am running the example code found at https://openml.github.io/openml-python/develop/examples/create_upload_tutorial.html. My goal is to do a bulk upload of data benchmarks from python that I have pre-loaded into pandas dataframes.

#### Expected Results
Should upload data-set

#### Actual Results
Throws exception from server side:
openml.exceptions.OpenMLServerException: https://www.openml.org/api/v1/xml/data/ returned code 131: Problem validating uploaded description file

#### Versions
NumPy 1.15.2
SciPy 1.1.0
Scikit-Learn 0.20.dev0
Backend TkAgg is interactive backend. Turning interactive mode on.
OpenML 0.8.0dev

**Comment by janvanrijn** [comment]
Thanks for reporting this. Can you please copy the code snippet that creates this error?

**Comment by AndriyMulyar** [comment]
`citation = (
    """
    J. Alcalá-Fdez, A. Fernandez, J. Luengo, J. Derrac, S. García, L. Sánchez, F. Herrera. KEEL Data-Mining Software Tool: Data Set Repository, Integration of Algorithms and Experimental Analysis Framework. Journal of Multiple-Valued Logic and Soft Computing 17:2-3 (2011) 255-287.
    """
)

description = (
    'The weather problem is a tiny dataset that we will use repeatedly'
    ' to illustrate machine learning methods. Entirely fictitious, it '
    'supposedly concerns the conditions that are suitable for playing '
    'some unspecified game. In general, instances in a dataset are '
    'characterized by the values of features, or attributes, that measure '
    'different aspects of the instance. In this case there are four '
    'attributes: outlook, temperature, humidity, and windy. '
    'The outcome is whether to play or not.'
)

for metadata, data in query:
    print(metadata)


    for X,y in data:
        X['class'] = y
        print(X.info())
        print(metadata['Description'])

        dataset = create_dataset(
            name = metadata['name'],
            description='test',
            creator='KEEL',
            contributor='Andriy Mulyar',
            collection_date='09-10-2018',
            language='English',
            licence=None,
            default_target_attribute='class',
            row_id_attribute=None,
            ignore_attribute=None,
            citation=citation,
            attributes='auto',
            data=X,
            version_label='v1_unprocessed',
        )
        upload_did = dataset.publish()
        print('URL for dataset: %s/data/%d' % (openml.config.server, upload_did))`

**Comment by joaquinvanschoren** [comment]
Hi Andriy, I bet this happens because the citation has to be basic latin:
https://www.openml.org/api_docs#!/data/post_data
<xs:element name="citation" minOccurs="0" type="oml:basic_latin1024"/>

Possible solutions:
- Update the server XSD to allow accents in the citation
- Auto-convert such strings in the python API
- Return a better error message

For now you can just remove the accents, but I agree that we need to handle this better.

**Comment by mfeurer** [comment]
Closing this as this is a problem with the main server error message.
