### ISSUE TITLE
Systematically Adding Tasks to Benchmarks in a Study

### ISSUE THREAD

**Issue by AndriyMulyar** [openml/openml-python#595]
#### Description
I have a [study](https://www.openml.org/s/184) full of uploaded data benchmarks. I would like to create associated supervised classification tasks for each benchmark automatically; however, I have not been able to find any applicable functions for creating tasks in the Python API.

The online form on the web-application for manual task creation appears to not be working at the current moment - the most recent relevant issue I have found on the main page is [issue](https://github.com/openml/OpenML/issues/761).

What can be done to associate tasks to given benchmarks at the current state. At the python package level, where would be an applicable location to include utility functions that interface the main API for task creation. I would be happy to contribute.

**Comment by PGijsbers** [comment]
For developers wanting to work on this; this should be easy once #607 is merged, I think?

**Comment by mfeurer** [comment]
Hey @AndriyMulyar is this still an issue for you? We do by now have task creation in Python, so I guess we can close this?
