### ISSUE TITLE
Handle 404 responses separately

### ISSUE THREAD

**Issue by mfeurer** [openml/openml-python#597]
Currently, the python connector cannot parse the error message because it is html. If the error code is 404, it should simply print a different error message instead of trying to parse it.

@janvanrijn is this correct? Maybe there shouldn't be an html response by the server if there's a 404?

**Comment by janvanrijn** [comment]
Servers (almost) always give html output on a 404, see for example: 
https://www.facebook.com/matthias.feurer.freiburg (fancy way of saying 404)

Most important thing is that the server sends a 404 header (I assume it does, let me know otherwise) and agree that the connectors should report this otherwise.

**Comment by mfeurer** [comment]
I think it sends a 404 header (the travis logs suggest that). Then the issue is simply that this isn't parsed properly.

**Comment by janvanrijn** [comment]
If you refer to the failing unit tests, yes it sends a 404 header. 

However, as OpenML is a complex system, there are various ways to trigger a 404 error (by wrong api call, setting wrong api url, or in this case by trying to access a file that seems internally lost). Please report if a situation occurs where not a 404 is send.

**Comment by nok** [comment]
I think that the body of the request should match the type of the request header `Accept`, e.g. `Accept: application/json`, `text/html` and `text/xml`. In the current status the server ignores the request headers and uses the route (specific controller) to return data with a fixed representation.

Examples:

1. Request website, get HTML (correct):
```bash
curl -I -X GET "https://www.openml.org/hello" -H "Accept: text/html"
```
```
HTTP/1.1 200 OK
Status: 404 Not Found
Content-Type: text/html; charset=UTF-8
```

2.1. Request to API (JSON), get JSON (correct):
```bash
curl -I -X GET "https://www.openml.org/api/v1/json/data/1" -H "Accept: application/json"
```
```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
```

2.2. Request to API (JSON), get XML (wrong):
```bash
curl -I -X GET "https://www.openml.org/api/v1/json/hello?apikey=..." -H "Accept: application/json"
```
**This is wrong, isn't it?**
```
HTTP/1.1 412 Precondition Failed
Content-Type: text/xml; charset=utf-8  <--- mismatch
```

3.1. Request to API (XML), get XML (correct, but mismatch):
```bash
curl -I -X GET "https://www.openml.org/api/v1/data/1" -H "Accept: application/json"  <-- header ignored
```
```
HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
```

3.2. Request to API (XML), get XML (correct, but mismatch):
```bash
curl -I -X GET "https://www.openml.org/api/v1/hello?apikey=..." -H "Accept: application/json"  <-- header ignored
```
```
HTTP/1.1 412 Precondition Failed
Content-Type: text/xml; charset=utf-8
```

**Comment by nok** [comment]
(@janvanrijn What do you think about [Laravel/Lumen](https://lumen.laravel.com/docs/5.7/responses#other-response-types)? It's the successor of CodeIgniter and provides various features, like dynamic routing, different responses and more that could improve the development, maintainability and security of the backend.)

**Comment by janvanrijn** [comment]
At first look, it seems pretty cool. 

How big / involved is the community around it?

**Comment by mfeurer** [comment]
I think we actually already fixed this, see https://github.com/openml/openml-python/blob/8f99ff6a05d8701098e776826ae78c36e8194782/openml/_api_calls.py#L218

Closing this for now, please comment or re-open if the issue is not resolved yet.
