### ISSUE TITLE
dataset_id referenced before assignment

### ISSUE THREAD

**Issue by ArlindKadra** [openml/openml-python#608]
#### Description

While trying to get the run with id 186276, the error dataset_id referenced before assignment was raised. 

The error is happening here:

https://github.com/openml/openml-python/blob/7c0a77d232a64da76be18bbce76e4bb8aeb4155b/openml/runs/functions.py#L883

Taking a quick look into the function throwing it, this seems to be the problem:
https://github.com/openml/openml-python/blob/7c0a77d232a64da76be18bbce76e4bb8aeb4155b/openml/runs/functions.py#L804-L807

The run at https://www.openml.org/api/v1/run/186276 does not seem to have a dataset field at all. 

Should this run be removed ? @mfeurer  @janvanrijn 
#### Steps/Code to Reproduce
```
import openml

run = openml.runs.get_run(186276)
```

**Comment by mfeurer** [comment]
I assume that there's an else statement missing?

**Comment by ArlindKadra** [comment]
That would be the easy hack yes, but do we really want to have runs without
datasets ?It seems to me the code is correctly trying to enforce having a
dataset id if the run is from the server.

**Comment by janvanrijn** [comment]
I think it's a problem with the run (will check why it's invalidated later)

Although not enforced by design, all current task types work on a dataset.

Op donderdag 13 december 2018 heeft Arlind Kadra <notifications@github.com>
het volgende geschreven:

**Comment by PGijsbers** [comment]
To clarify; is there a valid reason that a run on the server should not have a linked dataset?
If not, adding an else clause [here](https://github.com/openml/openml-python/blob/7c0a77d232a64da76be18bbce76e4bb8aeb4155b/openml/runs/functions.py#L804-L807) here which raises an error is proper and not hacky imo.

**Comment by janvanrijn** [comment]
> To clarify; is there a valid reason that a run on the server should not have a linked dataset?

You mean task. No valid reason, bad design.

**Comment by ArlindKadra** [comment]
> To clarify; is there a valid reason that a run on the server should not have a linked dataset?
> If not, adding an else clause [here](https://github.com/openml/openml-python/blob/7c0a77d232a64da76be18bbce76e4bb8aeb4155b/openml/runs/functions.py#L804-L807) here which raises an error is proper and not hacky imo.

I meant having an else statement and returning the run would be hacky, in case the `dataset_id` is not needed further in the function code. Adding an else and raising a more detailed error is proper.

**Comment by ArlindKadra** [comment]
> > To clarify; is there a valid reason that a run on the server should not have a linked dataset?
> 
> You mean task. No valid reason, bad design.

The task that the run is on has a `dataset_id`.
https://www.openml.org/api/v1/task/3513

**Comment by PGijsbers** [comment]
So it looks like we have some bad data to sort out server-side.

In terms of this package, we should raise an error we notice this happening.

**Comment by Neeratyoy** [comment]
Shall this be closed?

**Comment by PGijsbers** [comment]
Yes, I forgot to do that when merging, my bad.
