### ISSUE TITLE
duplicate functions tags

### ISSUE THREAD

**Issue by janvanrijn** [openml/openml-python#619]
all entities (`data`, `flow`, etc) have a `push_tag` and `remove_tag` function, but this functionality is also implemented in `utils.py` with the function `_tag_entity` (tags and untags). Let's drop either of these functionalities (or at least make the `push_tag` and `remove_tag` functions use `_tag_entity` as backend)

**Comment by sahithyaravi1493** [comment]
@janvanrijn  if dropping one of them is better, I think we could drop `_tag_entity` from utils.py. 
It seems to be used only in `test_tag_untag_dataset` which can be replaced by `push_tag` and `remove_tag.` 
Do you agree with dropping  `_tag_entity` ?

**Comment by janvanrijn** [comment]
@sahithyaravi1493 welcome on the team :)

I think that the various `push_tag` and `remove_tag` have similar structure and therefore code-duplications, which I think we should try to avoid. Therefore, my proposal would be to make the various  `push_tag` and `remove_tag` functions call to `utils. _tag_entity`, making all these functions a one liner with specific values set as parameters.

**Comment by sahithyaravi1493** [comment]
Thank you :)

Then I will proceed with the proposed approach (`tag_entity` as backend for the other two).

**Comment by mfeurer** [comment]
Fixed via #667.
