### ISSUE TITLE
Better error messages on listing queries

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#621]
#### Description
When you want to list items using the listing calls, you have to provide lists (e.g. a list of tasks). If you don't know this you get a cryptic error message 'TypeError: 'int' object is not iterable'

#### Steps/Code to Reproduce

```python
import openml as oml
runs = oml.runs.list_runs(task=2)
```

#### Expected Results
Either detect that it is an integer instead of a list and handle internally, or provide a clearer error message that a list must be provided.

#### Actual Results
```python

/usr/local/lib/python3.6/dist-packages/openml/runs/functions.py in _list_runs(id, task, setup, flow, uploader, display_errors, **kwargs)
   1002         api_call += "/run/%s" % ','.join([str(int(i)) for i in id])
   1003     if task is not None:
-> 1004         api_call += "/task/%s" % ','.join([str(int(i)) for i in task])
   1005     if setup is not None:
   1006         api_call += "/setup/%s" % ','.join([str(int(i)) for i in setup])

TypeError: 'int' object is not iterable
```

#### Versions
openml 0.8.0 (fresh pip install)

**Comment by mfeurer** [comment]
Fixed via #666.
