### ISSUE TITLE
upload time and error message missing from list_runs

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#622]
#### Description
When you list runs, upload time and error message are not shown, even though they are returned by the OpenML API. It would be very handy if these can be added.

#### Steps/Code to Reproduce
```python
import openml as oml
runs = oml.runs.list_runs(task=[2])
runs
```

#### Expected Results
```python
{110: {'flow_id': 76,
          'run_id': 110,
          'setup_id': 17,
          'task_id': 2,
          'uploader': 1,
          'upload_time': '2016-04-06 23:30:40',
          'error_message': []
}
```
#### Actual Results
```python
{110: {'flow_id': 76,
  'run_id': 110,
  'setup_id': 17,
  'task_id': 2,
  'uploader': 1},
```

#### Versions
Linux-4.14.79+-x86_64-with-Ubuntu-18.04-bionic
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0]
NumPy 1.14.6
SciPy 1.1.0
Scikit-Learn 0.20.2
OpenML 0.8.0

**Comment by mfeurer** [comment]
Added via #661.
