### ISSUE TITLE
docs not updated

### ISSUE THREAD

**Issue by janvanrijn** [openml/openml-python#640]
The github docs still say it's version 0.7.0, although 0.8.0 has been released.
https://openml.github.io/openml-python/stable/index.html

Anything we can do?

**Comment by joaquinvanschoren** [comment]
For some reason there is a difference between stable and master. Not sure
why. Master is at 0.8.0.

**Comment by mfeurer** [comment]
Stable should no longer be used, only the branch name. Where did the link come from?

To make sure this doesn't happen any more in the future, we should also remove the stable docs (stable directory in the gh-pages branch).

**Comment by mfeurer** [comment]
Okay, the page is gone.
