### ISSUE TITLE
Current dev branch fails on appveyor

### ISSUE THREAD

**Issue by PGijsbers** [openml/openml-python#643]
See [here](https://ci.appveyor.com/project/PGijsbers/openml-python-gqsnv/builds/23134996#L120). Not sure why this happens, though there seems to be an update 2 days ago ([here](https://anaconda.org/anaconda/nbconvert/files?version=5.4.1&channel=main&type=conda)), and I imagine this is the cause.

**Comment by mfeurer** [comment]
That's annoying. However, all tests in that test script are currently skipped. Therefore, we could remove the failing script. Would you like to do so?

**Comment by PGijsbers** [comment]
> However, all tests in that test script are currently skipped. 

Which tests are you referring to? I was under the impression that before the AppVeyor tests worked as intended?

**Comment by PGijsbers** [comment]
Turns out setuptools v23 is no longer required, and as long as we update conda, we can use the latest version. It is fixed in #644.

**Comment by mfeurer** [comment]
Fixed via #644.
