### ISSUE TITLE
build-time dependency on numpy

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#652]
#### Description
openml installation requires that numpy is already installed. This is tricky, for instance when you want to automatically set up an environment with a list of requirements.

Is there any way that 'pip install openml' will install numpy if it is not yet installed?

#### Steps/Code to Reproduce
```python
pip install openml
```
in any environment without numpy
-->

#### Expected Results
it will automaticall install numpy

#### Actual Results
Error: numpy is required during installation

**Comment by mfeurer** [comment]
Someone contributed this to Auto-sklearn a while ago. You could try to port the code to the openml package.

**Comment by PGijsbers** [comment]
It looks like this was done with the `setup_requires` parameter of setuptools, which seems to be added in version 39.0 (released 17 Mar 2018). Is it ok to require users to have setuptools >= 39.0 to be able to install this package?

**Comment by mfeurer** [comment]
I would be fine with this. As I was surprised that this is a rather new feature I briefly googled and stumbled upon this PEP: https://www.python.org/dev/peps/pep-0518/ Maybe we should implement this instead of the solution based on setuptools.

**Comment by PGijsbers** [comment]
I'll give that a go 👍

**Comment by PGijsbers** [comment]
So I tried it and it seems to work well 😄 I can install the package locally with `pip install -e .` without prior numpy/scipy installation. Now apparently the `pyproject.toml` file allows [metadata](https://flit.readthedocs.io/en/latest/pyproject_toml.html#metadata-section). Do we move the metadata from `setup.py` to `pyproject.toml`? And shall I add some additional metadata e.g. github url, documentation url. I would be in favor of moving all metadata to `pyproject.toml` where possible.

**Comment by mfeurer** [comment]
> Do we move the metadata from setup.py to pyproject.toml

Sounds like a good idea.

However, it would be great to see the whole thing in action first. Would you mind pushing this so we can have a look?
