### ISSUE TITLE
Duplicate information in task object

### ISSUE THREAD

**Issue by ArlindKadra** [openml/openml-python#656]
https://github.com/openml/openml-python/blob/7839225aefc6882777478794a4c996b6534635b2/openml/tasks/task.py#L204-L205

Line 205 adds duplicate information to the task object. The estimation procedure parameters are already stored in line 204. 
Do we create a property on estimation_parameters and issue a future deprecation warning, so we can deprecate at a later time?

**Comment by mfeurer** [comment]
Yes, please go ahead and do so.

**Comment by ArlindKadra** [comment]
Addressed in #607
