### ISSUE TITLE
Estimation procedure in tasks

### ISSUE THREAD

**Issue by ArlindKadra** [openml/openml-python#657]
https://github.com/openml/openml-python/blob/7839225aefc6882777478794a4c996b6534635b2/openml/tasks/task.py#L253-L254

Should we change the `estimation_procedure_type` and `estimation_parameters` to be optional? 
When uploading a task, only an `estimation_procedure_id` is required, the other parameters are generated by the server.

**Comment by mfeurer** [comment]
Fine by me. The user should actually never use the constructor anyway.

**Comment by ArlindKadra** [comment]
Addressed in #607
