### ISSUE TITLE
Status attribute in dataset

### ISSUE THREAD

**Issue by ArlindKadra** [openml/openml-python#660]
The docstring shows a `status` attribute in the dataset constructor, however the attribute itself is missing from the constructor. 

https://github.com/openml/openml-python/blob/7ec429e4054b28630562401036ee829963b79f35/openml/datasets/dataset.py#L83

**Comment by ArlindKadra** [comment]
@janvanrijn @mfeurer How do we want to deal with the above. On the xsd it is written that it is ignored on upload time
https://github.com/openml/OpenML/blob/develop/openml_OS/views/pages/api_new/v1/xsd/openml.data.upload.xsd

Do we remove it from the docs, or are there any plans on incorporating it into the dataset object.

**Comment by mfeurer** [comment]
I think the `status` should be removed from documentation because it cannot be cached and needs to be retrieved from the server (as the status can be changed).

We do have a function which can be used to check if a given set of datasets is active (`check_datasets_active`).

**Comment by mfeurer** [comment]
Fixed via #962.
