### ISSUE TITLE
Re-enable `test_get_runs_list_by_tag`

### ISSUE THREAD

**Issue by PGijsbers** [openml/openml-python#674]
[This test](https://github.com/openml/openml-python/blob/develop/tests/test_runs/test_run_functions.py#L1207) was disabled due to [this issue](https://github.com/openml/OpenML/issues/948). It turns out that the functionality _does_ work, just not with the `curves` tag. So the test needs to be re-enabled with a different run tag.

**Comment by mfeurer** [comment]
@prabhant will take on this issue.

**Comment by prabhant** [comment]
It's working with 'curves' tag now, fixed in PR #817
