### ISSUE TITLE
Listing of evaluation measures is missing.

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#687]
#### Description
You can't download the list of evaluation measures run by OpenML via the Python API.
There is an API call for that, though:
https://www.openml.org/api_docs#!/estimationmeasure/get_estimationmeasure_list

#### Steps/Code to Reproduce
No function exists for listing the evaluation measures

#### Expected Results
A function exists that lists the evaluation measures

#### Actual Results
No function exists for listing the evaluation measures

#### Versions
All

**Comment by Neeratyoy** [comment]
Hello,
A GET request to [estimationmeasure/list](https://www.openml.org/api/v1/xml/estimationmeasure/list) returns _Function not valid_.
I believe we instead should be getting something similar to [estimationprocedure/list](https://www.openml.org/api/v1/xml/estimationprocedure/list).
(Both cases hold for both the servers)

Does it mean that the API call mentioned [here](https://www.openml.org/api_docs#!/estimationmeasure/get_estimationmeasure_list) is not valid/doesn't exist? Is there some other way to retrieve all the evaluation measures from the server?

**Comment by janvanrijn** [comment]
Seems like a docu mistake. Should be
https://www.openml.org/api/v1/evaluationmeasure/list

@joaquinvanschoren

**Comment by PGijsbers** [comment]
Added in #713.
