### ISSUE TITLE
Get list of data qualities in python API

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#695]

**Comment by Neeratyoy** [comment]
Hello,
Is the goal to get a `list_data_qualities(dataset_id=x)` function that returns an array/dict/dataframe with the qualities for that dataset?

**Comment by janvanrijn** [comment]
Seems like you need this URL:
https://www.openml.org/api/v1/data/qualities/list

docu seems missing. cc @joaquinvanschoren

**Comment by PGijsbers** [comment]
Added in #711.
