### ISSUE TITLE
Python 2 support

### ISSUE THREAD

**Issue by glemaitre** [openml/openml-python#696]
scikit-learn 0.21 has been released. The support for Python 2 has been dropped. Therefore, some of the code in openml-python using some fixes need to be backported or the support for python 2 needs to be dropped.

Just open this issue to know the feeling about this subject.

**Comment by mfeurer** [comment]
Thanks for bringing this up. We actually dropped Python2 support with #623, but did not yet create a new release. Therefore, this is only visible in the development branch. Also, we might have missed some places. Do you have any concrete examples or suggestions?

**Comment by glemaitre** [comment]
OK it explains why. I was using the last version from PyPi. So then it should be fine. I will try with the development branch. Thanks Matthias.
