### ISSUE TITLE
Issues getting evaluations

### ISSUE THREAD

**Issue by hp2500** [openml/openml-python#699]
Hi there , 

I am trying to get evaluations through the python API. I am trying to work with the examples provided on the website, but they don't work at all. 

For example, if I try to do this...
![image](https://user-images.githubusercontent.com/27285925/58523626-3b810e80-8193-11e9-9547-edd931d87976.png)

I get the following error...
![image](https://user-images.githubusercontent.com/27285925/58523745-9d417880-8193-11e9-9c35-2367bd7696cd.png)

The documentation confirms, that output_format doesn't seem to exist anymore, but if I delete the argument, there is no way to access the information that is stored in the evals object...
![image](https://user-images.githubusercontent.com/27285925/58523833-e265aa80-8193-11e9-8681-002452918db6.png)

Of course I have tried more things, but I wasn't able to extract the information I am looking for. 

Am I missing something, or is the documentation outdated?

**Comment by mfeurer** [comment]
Could you please provide us with details about:

1. how you installed the library and which version you're using
2. which documentation you're using (i.e. the url)

From the issue it seems like you're using the documentation of the development branch together with the code from the latest release. However, the examples from the development branch will only work with code from the development branch.

**Comment by hp2500** [comment]
Hi Mathias,

thanks for your reply.

1) I am using version 0.8.0 installed via pip
[image: image.png]

2) the example code I am using can be found here:
https://docs.openml.org/Python-examples/

Additionally I have been looking at the docs under:
https://openml.github.io/openml-python/master/generated/openml.evaluations.list_evaluations.html#openml.evaluations.list_evaluations

But I noticed that there are contradictions. For example the output_format
argument used in the example does not seem to exist.

Best wishes,
Heinrich

**Comment by mfeurer** [comment]
Thanks a lot for the info. Indeed, docs.openml.org hosts the documentation for the development branch. Please use the docs at https://openml.github.io/openml-python/master for the version you obtained with `pip install openml`. You can install the development version (for which the docs are correct) with `pip install git+https://github.com/openml/openml-python@develop.
