### ISSUE TITLE
Add a run object

### ISSUE THREAD

**Issue by mfeurer** [openml/openml-python#7]
Add an object to represent a run:

http://openml.org/api

and the methods to download them.

**Comment by mfeurer** [comment]
Should this run object maybe contain the code provided @PG-TUe in the autorun script?

**Comment by joaquinvanschoren** [comment]
Yes, although the code of @PG-TUe is scikit-learn specific (thats why it is
not already in the core). It will need some minor refactoring, I guess.
Ideally, we have a general Python core, and scikit-learn specific wrappers.

**Comment by amueller** [comment]
we are half-way there I'd say.

**Comment by amueller** [comment]
I think relying on "fit" "predict" is fine (it's a pretty established api now, and you need to define some API). I'll try to remove the actual scikit-learn specific parts soon / now. The run object is there.

**Comment by mfeurer** [comment]
Yes, I found that we also depend on `get_params()` which I think is fine for now. I will add it to the documentation and we can generalize this later (maybe next workshop).

**Comment by amueller** [comment]
yeah we also depend on that, which I also think is fine. The main part that needs fixing is importing sklearn in the code to get the version string, I think. That should be more general.
