### ISSUE TITLE
Issues getting benchmarking suites

### ISSUE THREAD

**Issue by hp2500** [openml/openml-python#707]
Hi there, 

I am trying to access the benchmarking suites through the python API. I am sticking with the instructions form this page [](https://docs.openml.org/benchmark/) and I am using the development version. 

![image](https://user-images.githubusercontent.com/27285925/58977602-10e91400-8798-11e9-9b7f-c2dc2b025c4c.png)

However, I am getting unexpected errors. 
![image](https://user-images.githubusercontent.com/27285925/58977773-5dccea80-8798-11e9-981f-db503196393b.png)

Any Idea why this might be the case? 

Best,
Heinrich

**Comment by hp2500** [comment]
@amueller

**Comment by janvanrijn** [comment]
Can you please verify whether
* you connect to the main server (I would presume so if you did not do any effort yourself to change this in the code or config files)
* the develop branch is up to date with the latest commits (there have been relevant updates in March)

I can not reproduce this error.

**Comment by pfontana3w2** [comment]
I am getting the same error. I just pulled and installed the develop branch and checked that I have version 0.9.0.

```
benchmark_suite = openml.study.get_study('OpenML-CC18', 'tasks')
Traceback (most recent call last):
  File "/Users/pcf/.pyenv/versions/3.6.8-pcf/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3291, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-27-c79d58813998>", line 1, in <module>
    benchmark_suite = openml.study.get_study('OpenML-CC18', 'tasks')
  File "/Users/pcf/.pyenv/versions/3.6.8-pcf/lib/python3.6/site-packages/openml/study/functions.py", line 64, in get_study
    study = cast(OpenMLStudy, _get_study(study_id, entity_type='run'))
  File "/Users/pcf/.pyenv/versions/3.6.8-pcf/lib/python3.6/site-packages/openml/study/functions.py", line 83, in _get_study
    main_entity_type, entity_type,
ValueError: Unexpected entity type 'task' reported by the server, expected 'run'
```

I have also tried accessing it by study number and got the same error

```
benchmark_suite = openml.study.get_study(99)
Traceback (most recent call last):
  File "/Users/pcf/.pyenv/versions/3.6.8-pcf/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3291, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-26-9486b39bbf6b>", line 1, in <module>
    benchmark_suite = openml.study.get_study(99)
  File "/Users/pcf/.pyenv/versions/3.6.8-pcf/lib/python3.6/site-packages/openml/study/functions.py", line 64, in get_study
    study = cast(OpenMLStudy, _get_study(study_id, entity_type='run'))
  File "/Users/pcf/.pyenv/versions/3.6.8-pcf/lib/python3.6/site-packages/openml/study/functions.py", line 83, in _get_study
    main_entity_type, entity_type,
ValueError: Unexpected entity type 'task' reported by the server, expected 'run'
```

Version info:
```
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import sklearn; print("Scikit-Learn", sklearn.__version__)
import openml; print("OpenML", openml.__version__)
```
Darwin-18.6.0-x86_64-i386-64bit
Python 3.6.8 (default, Mar 20 2019, 16:36:17) 
[GCC 4.2.1 Compatible Clang 6.0.0 (tags/RELEASE_600/final)]
NumPy 1.16.2
SciPy 1.2.1
Scikit-Learn 0.20.3
OpenML 0.9.0

**Comment by amueller** [comment]
@hp2500 Said he solved the issue. Maybe he can comment here to help @pfontana3w2 and/or we can close.

**Comment by hp2500** [comment]
@pfontana3w2 @amueller My solution is basically a workaround. I used the tag argument to get an overview of all tasks associated CC18: 

```python 
# get all supervised classification tasks from CC18
tasks_all = openml.tasks.list_tasks(task_type_id=1, output_format='dataframe', tag = 'OpenML-CC18')
```
I can also iterate over the task ids and get the tasks individually whenever I want to run something on each one of them. I hope this helps.

**Comment by pfontana3w2** [comment]
@hp2500  Thank you for sharing the workaround. I still can't access the study but this lets me quickly access the task id list, which is the thing I needed most from the study API.
