### ISSUE TITLE
Can't upload run

### ISSUE THREAD

**Issue by kazeevn** [openml/openml-python#71]
Get code 450, using Python 3.5.1 on Anaconda.

[covtype.zip](https://github.com/openml/openml-python/files/174391/covtype.zip)

**Comment by amueller** [comment]
still?

**Comment by mfeurer** [comment]
I assume this is a duplicate of #186, therefore I assign this to @janvanrijn

**Comment by janvanrijn** [comment]
I would assume that this is solved, the issue comes from before the bug refactoring. Will check so when back in Freiburg.

**Comment by janvanrijn** [comment]
I think this issue can be closed, the code in the notebook is clearly from an older version of the api connector. 

@kazeevn Sorry that this took so long
