### ISSUE TITLE
Attributes are not documented?!

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#716]
It looks like none of the classes document their attributes. They really should.

**Comment by PGijsbers** [comment]
Marcos will take this up! 🎉

**Comment by LennartPurucker** [comment]
For documentation purposes, I found the following classes that are currently missing documentation as far as I can tell: 

- OpenMLRun (see PR #1194) 
- OpenMLClusteringTask
- OpenMLTask
- OpenMLLearningCurveTask
- OpenMLClassificationTask
- OpenMLClassificationTask
- OpenMLSplit

**Comment by v-parmar** [comment]
Hey @amueller @LennartPurucker, I have added the missing documentation of the remaining attributes of classes and functions. Please check my PR(#1283) and tell me if any changes are required.
