### ISSUE TITLE
website: tutorials warn about deprecations in sklearn 0.20

### ISSUE THREAD

**Issue by azrdev** [openml/openml-python#726]
#### Description
The tutorials (at least [Flows and Runs](https://openml.github.io/openml-python/develop/examples/flows_and_runs_tutorial.html) and [OpenML Run](https://openml.github.io/openml-python/develop/examples/sklearn/openml_run_example.html)) have their example output cluttered with warnings from sklearn, about deprecations in 0.20 (which will fail to work at all in the upcoming 0.22).

**Comment by mfeurer** [comment]
It seems like we need to update the examples to use the latest additions to scikit-learn. Anyone interested in working on this?
