### ISSUE TITLE
Guidelines for publishing OpenML-python extensions

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#730]
#### Description
OpenML has an extension API, and you can use it to connect other libraries to OpenML. It is however unclear how one should later up 'publish' this extension so that other people can use it.

#### Steps/Code to Reproduce
Here is an example of an extension that adds full support for Keras, MXnet, PyTorch and ONNX:
https://github.com/openml/openml-deeplearning/

It is currently a clone of the pull python API with the extension added in separate folders: https://github.com/openml/openml-deeplearning/tree/master/openml/extensions

Each folder has an extensions.py file and usually a config.py file with additional configuration functionality.

It also has documentation in the `examples` folder and test in the `tests` folder.

It is currently installable as a standalone package through pip. However, this may lead to divergence between this package and the core python API.

#### Expected Results
Clear guidelines on how extensions can be published and imported. It should allow independent testing and documentation.

If this makes sense, maybe also define a way to 'register' extensions so it is easier to find and install them.

Thanks!

**Comment by joaquinvanschoren** [comment]
Basically:

* Rip out everything except the extension class which extends the interface
* Register the extension: https://openml.github.io/openml-python/master/generated/openml.extensions.register_extension.html#openml.extensions.register_extension
* Set up openml-python extensions organization
* Unit tests: every new repo need to set up own CI
* Documentation: also local?

**Comment by janvanrijn** [comment]
> Rip out everything except the extension class which extends the interface

Except this step. It should be possible to build an extension from scratch, by including the `openml-python` package.

**Comment by mfeurer** [comment]
Added via #778.
