### ISSUE TITLE
What happened to openml_param_name_to_sklearn?

### ISSUE THREAD

**Issue by hp2500** [openml/openml-python#733]
Hi there, 

I am trying to run some functions from [https://github.com/openml/openml-python-contrib](url). 
Here is an example: 

```{python}
openmlcontrib.meta.get_task_flow_results_as_dataframe(task_id = 3, 
                                                      flow_id = runs.get_run(10229142).flow_id,
                                                      num_runs = 3,
                                                      raise_few_runs = True, 
                                                      configuration_space= cs,
                                                      evaluation_measures=['predictive_accuracy'],
                                                      per_fold = False,
                                                      cache_directory = 'xxx'
                                                     )

```
I am getting this error:
![image](https://user-images.githubusercontent.com/27285925/61072490-6a6ce000-a3e1-11e9-8058-6f60d7a74354.png)

I have checked the docs and have not found openml.flows.openml_param_name_to_sklearn . Are the contrib functions outdated or am I simply on the wrong track? 

@amueller

**Comment by mfeurer** [comment]
Please see my answer in https://github.com/openml/openml-python-contrib/issues/2
