### ISSUE TITLE
Python version requirements inconsistent

### ISSUE THREAD

**Issue by pganssle** [openml/openml-python#741]
I noticed in your `setup.py` file that you have [a requirement for Python version >= 3.5](https://github.com/openml/openml-python/blob/56fcc00cb16b102e4778c1f1dadd7d9919e9eca4/setup.py#L16), but you do not have a [`python_requires` keyword](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires), and you have the [Python 3.4 in your trove classifiers](https://github.com/openml/openml-python/blob/56fcc00cb16b102e4778c1f1dadd7d9919e9eca4/setup.py#L82).

I suggest adding `python_requires=">= 3.5"` to your `setup()` invocation and removing Python 3.4 from your trove classifiers.

(Adding this because it's relevant for `python_requires`, not because I have any evidence you don't already know it). When uploading your distributions, make sure to use [`twine`](https://pypi.org/project/twine/), instead of `setup.py upload`, since the latter is deprecated and some versions of `setuptools` have bugs that will cause problems for some users.

**Comment by amueller** [comment]
I think a PR would probably be welcome.
