### ISSUE TITLE
update scikit-learn dependency?

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#749]
The current tests fail with later scikit-learn releases in several places, because the code relies on classes and attributes that have been removed.
I would suggest using 0.20 from Sept 2018 as minimum version.
That introduced the current ColumnTransformer and SimpleImputer and OneHotEncoder and so you'd be able to write current sklearn.

**Comment by mfeurer** [comment]
>  I would suggest using 0.20 from Sept 2018 as minimum version.

We had a longer discussion at the Paris workshop on this topic and came to the conclusion that we try to allow multiple versions where possible. We should discuss how to proceed at the next workshop.

Anyway, I totally agree that we also need to test 0.21.X.

**Comment by amueller** [comment]
Ok I should really work on that CZI grant but happy to look into this soon.

**Comment by mfeurer** [comment]
Closed via #752.
