### ISSUE TITLE
Problems with get_metric_fn and sklearn.metrics for multiclass classification tasks

### ISSUE THREAD

**Issue by hp2500** [openml/openml-python#763]
Hi there, 

I am trying to produce various evaluations metrics for existing runs using get_metric_fn. I have no problem doing this for binary classification tasks, but I am running into problems for multiclass classification. Here are a few examples with regard to average_precision_score:

Binary classification (e.g. task 49) works fine:
```{python}
import openml
from sklearn.metrics import average_precision_score
run = openml.runs.get_run(10288928)
run.get_metric_fn(average_precision_score)
```

Running the same code on a multiclass classification (e.g. task 146821) run yields an error as expected:
```{python}
import openml
from sklearn.metrics import average_precision_score
run = openml.runs.get_run(10261809)
run.get_metric_fn(average_precision_score)
```
ValueError: multiclass format is not supported

When I add the 'average' argument for multiclass classification, I get another error: 
```{python}
import openml
from sklearn.metrics import average_precision_score
run = openml.runs.get_run(10261809)
run.get_metric_fn(average_precision_score(average = 'macro'))
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-151-4986f5df7345> in <module>
      3 
      4 run = openml.runs.get_run(10261809)
----> 5 run.get_metric_fn(average_precision_score(average = 'macro'))

TypeError: average_precision_score() missing 2 required positional arguments: 'y_true' and 'y_score'

My question: Is it possible to run sklearn metrics on OpenML multiclass classification tasks?

@amueller

**Comment by amueller** [comment]
This is not an OpenML issue, there is no multi-class average precision in sklearn:
https://scikit-learn.org/dev/modules/model_evaluation.html#classification-metrics

Maybe if this is not clear from the docstring you could add a note?
