### ISSUE TITLE
fix flow specification!

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#77]
It should be possible to reload a flow on a different system and rerun the model.
brownie points if it works with pipelines.
This should check that the versions of the important libs are the same and warn otherwise.

**Comment by mfeurer** [comment]
Added in b0168ade51b89552b21754391dcf5c2e3c9940af and 12a56693954751d9b0584c9e26d8b9378fc33b51. Can handle pipelines. Not sure about distribution objects for gridsearch.

**Comment by amueller** [comment]
Can you add a PR? PRs are easier to review than commits.

**Comment by amueller** [comment]
@mfeurer any progress on this? Also we need a ``list_flows`` function.

**Comment by mfeurer** [comment]
Progress can be seen in #167.

**Comment by mfeurer** [comment]
Reloading a flow is implemented in #167. Will now implement the dependency checking.

**Comment by mfeurer** [comment]
Added the respective functionality in e42ca51.
