### ISSUE TITLE
Guide on how to create and publish openml-python extensions

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#771]
* Rip out everything except the extension class which extends the interface
* Register the extension: https://openml.github.io/openml-python/master/generated/openml.extensions.register_extension.html#openml.extensions.register_extension
* Set up openml-python extensions organization
* Unit tests: every new repo need to set up own CI
* Documentation: also local?

**Comment by mfeurer** [comment]
Duplicate of #730.
