### ISSUE TITLE
Flow Equality

### ISSUE THREAD

**Issue by ArlindKadra** [openml/openml-python#775]
In my opinion, it would be better if we move the function below to the flow object and we override the '__ eq __' method.

https://github.com/openml/openml-python/blob/3d08c2d2aabbd4656740c05d34908548b6d3ace8/openml/flows/functions.py#L308-L315

**Comment by mfeurer** [comment]
The idea why this function is not part of the flow class is to not define what flow equality means in a subpackage of OpenML. Instead, the function is intended to be used only in the tests.

Also, it is unclear what flow equality would mean. For example would be two flow objects with the same values, but one published and the other not be equal?

Therefore, I'm closing this issue. If you disagree, pleas reopen this issue.
