### ISSUE TITLE
openml-python does not recognize corrupt dataset.pkl.py3 file

### ISSUE THREAD

**Issue by PGijsbers** [openml/openml-python#779]
People are experiencing issues downloading dataset `41081` [here](https://github.com/ML-course/ML-course/issues/19).
Investigation is on-going, but it looks like the Python process gets killed when pickling the dataset to disk.
Subsequent loads of the cached data fail because the `dataset.pkl.py3` file is created (and sits at 0 bytes). Because the file exists it is attempted to be loaded without further sanity checks. I think the correct behavior would to check for this faulty file and if it exists either (1) raise an error or (2) delete the file, attempt to pickle is again, and raise an error only if this fails. I would prefer option 2.

edit: to clarify, this issue is about trying to mitigate the effect of corrupt files in cache. Not about the fact that the process gets killed (possibly during pickling). That warrants a separate issue which I will open after we have some more information from the linked issue.

**Comment by PGijsbers** [comment]
If the file is corrupt, we could also just load the data from the arff file (in addition to removing the file and giving a warning)?

**Comment by mfeurer** [comment]
Yes, that would be a good first step. The question though is why the file is corrupt and whether we would try to pickle it a second time. Maybe we can add a flag for that?

**Comment by PGijsbers** [comment]
The file would be corrupt due to the process getting killed while pickling happens.
I think by default you probably don't want to retry pickling.
If you would retry it by default and the errors are as severe as the process getting killed, you'd need to first persist something to disk noting that you've tried to pickle it (that way if it does get killed next time around we can know that). I think having the (few) people that are affected by this load the dataset slightly slower from cache because they are parsing the arff file is the better solution while we work on a fix of the underlying issue.

**Comment by mfeurer** [comment]
Okay, fine by me. If we add a warning message, the user can decide on its own whether to delete the corrupt file. Will you go ahead and create a PR?

**Comment by PGijsbers** [comment]
Ok, I'll work on it tomorrow.
