### ISSUE TITLE
avoid writing to files when not necessary

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#79]
git grep `open` and remove all unnecessary uses of files.
The api call inferface now supports passing strings "as file objects".

**Comment by mfeurer** [comment]
This issue is solved by #322 and #323.

**Comment by amueller** [comment]
I'm not sure this is solved, though... does OpenMLDataset.publish write a file?

**Comment by mfeurer** [comment]
No, it doesn't: https://github.com/openml/openml-python/blob/develop/openml/datasets/dataset.py#L373

**Comment by amueller** [comment]
doesn't "file_dictionary" point to file names that are uploaded in the api call?

**Comment by mfeurer** [comment]
Okay, so the issue is actually not that data is stored automatically, but that the user has to store data before he/she can upload it?

**Comment by amueller** [comment]
Ok I'll open a new issue.
