### ISSUE TITLE
Suggestion: add function to get tasks for a dataset?

### ISSUE THREAD

**Issue by mfeurer** [openml/openml-python#797]
@janvanrijn suggested this as part of his review of PR #791 (https://github.com/openml/openml-python/pull/791#discussion_r330118731)

One possibility would be to have an independent function:

```
def get_tasks_for_dataset(
    dataset_id: int,
    task_type_id: int,
    estimation_procedure: str,
    status: str,
    check_target_attribute: bool,
) -> List:
    pass
```

alternatively, one could make this a method for the `OpenMLDataset`:
```
def get_tasks(
    self,
    task_type_id: int,
    estimation_procedure: str,
    status: str,
    check_target_attribute: bool,
) -> List:
    pass
```
what do you think?

**Comment by amueller** [comment]
How is that different from ```openml.tasks.list_tasks(data_id=did)```?

**Comment by mfeurer** [comment]
That's embarrassing, I didn't know this exists.
