### ISSUE TITLE
Wrong argument naming in method description

### ISSUE THREAD

**Issue by ArlindKadra** [openml/openml-python#799]
https://github.com/openml/openml-python/blob/5a2830cc494dbffe93fb324aa7eb98b8bf3f0b33/openml/datasets/functions.py#L450-L461

**Comment by mfeurer** [comment]
I'm failing to see the issue here, could you please be more specific?

**Comment by ArlindKadra** [comment]
This part:
` This scenario will raise an error instead if `exception_if_multiple` is `True``
