### ISSUE TITLE
Rename arguments of list_evaluations to indicate they expect lists of ids

### ISSUE THREAD

**Issue by PGijsbers** [openml/openml-python#804]
See also #796. It was a step forward, but the argument names still don't convey that we are looking for a list (i.e. argument name should be plural) or ids as opposed to OpenML objects (e.g. by a suffix `_id`).

I would argue that we also should update the type hints (to `Optional[List[Union[str, int]]]`) and add parameter descriptions in the docstring.

**Comment by mfeurer** [comment]
Added via #933
