### ISSUE TITLE
ensure examples are unit tested

### ISSUE THREAD

**Issue by janvanrijn** [openml/openml-python#805]
i think they might be, since one of the travis runs crashes when they are not properly handled. 

The travis script has several variables, including "examples". None of the travis runs invokes this variable. Is this good?

**Comment by janvanrijn** [comment]
side-question. what happens if we execute first
`pip install -e '.test'`
and subsequently
`pip install -e '.examples'`

Will that include the installation of all dependencies of both commands and keep the package as is?

**Comment by mfeurer** [comment]
> i think they might be, since one of the travis runs crashes when they are not properly handled.

Yes, they're actually executed as part of building the documentation: https://github.com/openml/openml-python/blob/develop/ci_scripts/create_doc.sh#L24

> The travis script has several variables, including "examples". None of the travis runs invokes this variable. Is this good?

This is not as bad as it sounds as there are no more "examples": https://github.com/openml/openml-python/blob/develop/ci_scripts/test.sh#L19 I'll remove those lines.

Regarding your side question: I'm not sure, but I'd expect that the installation is skipped the second time. (and therefore the dependencies will not be installed).

**Comment by mfeurer** [comment]
I just created #806 to remove these unnecessary variables.

**Comment by mfeurer** [comment]
Closing this as we test the examples (they constantly for one PR so I'm really sure about this) and removed the unused variable from the travis scripts. Please reopen if there's something else to this issue.
