### ISSUE TITLE
submodules or not?

### ISSUE THREAD

**Issue by amueller** [openml/openml-python#82]
I'm not sure if we want to keep the API split into submodules or not.
currently you can do the following:
```python
import openml
connector = openml.APIConnector()
dataset = openml.datasets.download_dataset(connector, id=0)
```
or
```python
from openml import APIConnector
from openml.datasets import download_dataset
connector = APIConnector()
dataset = download_dataset(connector, id=0)
```

One alternative would be to flatten out the ``datasets``, ``runs`` etc submodules:
```python
import openml
connector = openml.APIConnector()
dataset = openml..download_dataset(connector, id=0)
```
and
```python
from openml import APIConnector, download_datasets
connector = APIConnector()
dataset = download_dataset(connector, id=0)
```
This is only an API decision and doesn't change the layout of the files on disk.

We could also shorten by dropping the the ``dataset`` part in the function names:
```python
import openml
connector = openml.APIConnector()
dataset = openml.datasets.download(connector, id=0)
```
That doesn't work that well with the ``from`` imports, though.
lastly, we could make them static methods on the classes:
```python
from openml import APIConnector, OpenMLDataset
connector = APIConnector()
dataset = OpenMLDataset.download(connector, id=0)
```

The benefit of not flattening out the submodules is that auto-completion (which I use A LOT in the notebook) is much more explorable. The downside is more to type.
The class methods are sort of an intermediate maybe?
- note that I could also
```python
from openml import datasets
datasets.download(...)
```

I'm not saying we need to change something, I'm just saying that if we want to change something, now would be a good time.

**Comment by mfeurer** [comment]
We decided to leave it as it is now, maybe we'll make it flat in the future.
