### ISSUE TITLE
list_evaluations_setup() fails when number of evaluations not a multiple of 100

### ISSUE THREAD

**Issue by Neeratyoy** [openml/openml-python#838]
`np.split` looks to split the array into _N_ equal spaced arrays wherein N is 100 [here](https://github.com/openml/openml-python/blob/develop/openml/evaluations/functions.py#L332). As a result, it appears that for any combination of input where the number of evaluations returned is not a multiple of 100, this function will throw an error.

To recreate:

##### what works
`import openml`
`df = openml.evaluations.list_evaluations_setups(function='predictive_accuracy', flow=[8353], task=[6], output_format='dataframe', parameters_in_separate_columns=True)`

##### what fails
`df = openml.evaluations.list_evaluations_setups(function='predictive_accuracy', flow=[5891], task=[37], output_format='dataframe', parameters_in_separate_columns=True)`

##### comparison
Since `list_evaluations_setup` calls `list_evaluations` internally.

`df = openml.evaluations.list_evaluations(function='predictive_accuracy', flow=[8353], task=[6], output_format='dataframe')`
`print(len(df))  #1000` 

`df = openml.evaluations.list_evaluations(function='predictive_accuracy', flow=[5891], task=[37], output_format='dataframe')`
`print(len(df))  #2429`

**Comment by sahithyaravi1493** [comment]
Yes, just encountered this myself yesterday, will fix this

**Comment by mfeurer** [comment]
Will it be possible to use the listing helper in https://github.com/openml/openml-python/blob/develop/openml/utils.py ?

**Comment by sahithyaravi1493** [comment]
list_setups  does use the helper already, but doesnt work with large results unlike list_evaluations.

**Comment by mfeurer** [comment]
But `list_evaluations` uses the helper, too: https://github.com/openml/openml-python/blob/develop/openml/evaluations/functions.py#L79

**Comment by sahithyaravi1493** [comment]
Yes list_evalutations works with the helper, but list_setups doesnt... basically the batch_size of 10000 done by list_all doesnt work for list_setups

**Comment by mfeurer** [comment]
Got it, thanks for the explanation.
