### ISSUE TITLE
Peronne example stalls on CI sometimes

### ISSUE THREAD

**Issue by PGijsbers** [openml/openml-python#852]
The Peronne example seems to stall on CI sometimes. It could be server issues, but it would be nice to verify that. See e.g.: https://travis-ci.org/openml/openml-python/jobs/599553086

**Comment by mfeurer** [comment]
How about wrapping a context manager into this example to have some output so that it doesn't stall?

(We have to download quite a few runs with `get_runs` which iteratively calls `get_run`. Instead, we could use `list_evaluations_hyperparameters`).

**Comment by mfeurer** [comment]
Solved via #853 by using `list_evaluations_hyperparameters`.
