### ISSUE TITLE
__version__ is imported with `from openml import *`

### ISSUE THREAD

**Issue by PGijsbers** [openml/openml-python#871]
Not that you should ever really want to use `import *`, but '\_\_version\_\_' is listed in `openml\__init__.py:__all__`  which means it gets imported:
```
>>> from openml import *
>>> __version__
'0.9.0'
```
This is generally not done, so we might remove '\_\_version\_\_' from our `__all__` list.

**Comment by Rong-Inspur** [comment]
@PGijsbers  Hi, I would like to help and make my first contribution here.

**Comment by PGijsbers** [comment]
Hi, thanks for taking the step! :) The contribution guidelines can be found [here](https://openml.github.io/openml-python/master/contributing.html#contributing). If you need any further help please let us know!
