### ISSUE TITLE
OpenML package fails to import if home directory is not writable

### ISSUE THREAD

**Issue by mitar** [openml/openml-python#883]
#### Description

It looks like OpenML package is trying to write into an user home directory when it is imported. I think this is really not nice. Just importing a package should not have such a side effect. You should write only if there is a request for that.

This broke [D3M](https://gitlab.com/datadrivendiscovery/primitives/-/jobs/350149345) build process now that we added the OpenML package as a dependency to [d3m](https://gitlab.com/datadrivendiscovery/d3m) core package. :-(

#### Steps/Code to Reproduce

Create an user on your system which has `/nonexitent` as its home directory. That directory should not exist. Try `import openml` when running under such user.

#### Expected Results

Package loads.

#### Actual Results

It fails with:

```
File "/usr/local/lib/python3.6/dist-packages/openml/__init__.py", line 18, in <module>
  from . import _api_calls
File "/usr/local/lib/python3.6/dist-packages/openml/_api_calls.py", line 8, in <module>
  from . import config
File "/usr/local/lib/python3.6/dist-packages/openml/config.py", line 241, in <module>
  _setup()
File "/usr/local/lib/python3.6/dist-packages/openml/config.py", line 133, in _setup
  os.mkdir(os.path.expanduser(os.path.join('~', '.openml')))
FileNotFoundError: [Errno 2] No such file or directory: '/nonexistent/.openml'
```

#### Versions

```
>>> import platform; print(platform.platform())
Linux-5.0.0-32-generic-x86_64-with-Ubuntu-18.04-bionic
>>> import sys; print("Python", sys.version)
Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0]
>>> import numpy; print("NumPy", numpy.__version__)
NumPy 1.17.3
>>> import scipy; print("SciPy", scipy.__version__)
SciPy 1.3.1
>>> import sklearn; print("Scikit-Learn", sklearn.__version__)
Scikit-Learn 0.21.3
>>> import openml; print("OpenML", openml.__version__)
OpenML 0.10.1
```

**Comment by mitar** [comment]
If you have OpenML system wide install, try: `sudo -u nobody python3 -c 'import openml'`

**Comment by mitar** [comment]
So the problem to me here is that this happens not the first time code needs to store something into the cache, but when you import the package.

**Comment by mitar** [comment]
Even easier:

```
export HOME=/nonexistent
python3
import openml
```

**Comment by mfeurer** [comment]
Thank you very much for reporting this issue. However, to my understanding this is the [standard behavior for Unixoid systems](http://www.pathname.com/fhs/pub/fhs-2.3.html#HOMEUSERHOMEDIRECTORIES). But as that standard says, we should not rely on this directory being present and do not fail on it not existing.

**Comment by mitar** [comment]
I mean, you should not be writing at just importing the module, without calling anything. This is just not nice.

**Comment by joaquinvanschoren** [comment]
So, should we create the folder when the user first downloads/uploads something? I.e. when we need to start caching?

**Comment by mitar** [comment]
Yes.
