### ISSUE TITLE
Use standard Linux locations for config and cache

### ISSUE THREAD

**Issue by mitar** [openml/openml-python#884]
Currently OpenML package creates `.openml` in home directory. These days this is not a nice behavior, because [there is a standard where things should go](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

* Use `XDG_CONFIG_HOME` environment variable to determine base config directory.
* Use `XDG_CACHE_HOME` environment variable to determine base cache directory.

See [more practical information and details here](https://wiki.archlinux.org/index.php/XDG_Base_Directory).

So, by default, config should go into `~/.config/openml` and cache into `~/.cache/openml`.

**Comment by mfeurer** [comment]
Thank you for the pointers, this makes total sense.

So far, we have agreed to keep the config and cache consistent across languages, so I'd like to hear @giuseppec and @janvanrijn's opinion for R and Java.

**Comment by HeidiSeibold** [comment]
@mllg @berndbischl @giuseppec this is likely important for the R package as well. :point_up_2:
