### ISSUE TITLE
Introduction example missing?

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#900]
#### Description
In the user guide, the third link is broken. It points to:
http://openml.github.io/openml-python/master/examples/introduction_tutorial.html

but that example doesn't seem to exist. Is the link wrong or did the example disappear?
I also could not find an example that explains the configuration options (server, api_key,...)

#### Steps/Code to Reproduce
Go to http://openml.github.io/openml-python/master/usage.html
and click the link to the introduction example.

#### Expected Results
An example on how to configure OpenML.

#### Actual Results
Page not found

#### Versions
Irrelevant.

**Comment by maxmarketit** [comment]
I see almost all the links from 
https://openml.github.io/openml-python/master/usage.html#usage are missing...

  for example, https://openml.github.io/openml-python/master/examples/datasets_tutorial.html

**Comment by mfeurer** [comment]
We have fixed all broken links via #1048. Please open a new issue if the now available links are not what you are looking for.
