### ISSUE TITLE
The API docs should document the openml config options

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#901]
#### Description
The API Docs: http://openml.github.io/openml-python/master/api.html
do not cover the API config options, such as 'server, api_key, verbosity,...'

Could this be added?

#### Steps/Code to Reproduce
Try to look up the OpenML-Python config options on 
http://openml.github.io/openml-python/master/api.html

#### Expected Results
Maybe a section 'Configuration' next to 'Top level Classes', 'Extensions' and 'Modules'?

#### Actual Results
Nothing there.

#### Versions
Irrelevant

**Comment by PGijsbers** [comment]
I noticed that not only programmatic configuration, but also configuration through the configuration file is missing.
