### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by ArlindKadra** [openml/openml-python#909]
https://github.com/openml/openml-python/blob/249abc901c34bc87c4b283e42e754308a5a2d629/examples/30_extended/create_upload_tutorial.py#L221

No column `rnd_str` in the example dataset.

**Comment by PGijsbers** [comment]
It was originally added in f22c39360f82bd118d6b17ebff2e34ee7c174ef4. Not only is there no column named `rnd_str` in the dataset, there is no string data (other than the converted categorical columns). I think it should be corrected to 
> ... dtype while the columns 'temperature' and 'humidity' are kept as numeric columns. ...

**Comment by mfeurer** [comment]
Fixed via #914.
