### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by ArlindKadra** [openml/openml-python#910]
The code is related to removing tasks from a suite or study, however, in the argument documentation it is written as link instead of de-link.

https://github.com/openml/openml-python/blob/249abc901c34bc87c4b283e42e754308a5a2d629/openml/study/functions.py#L380-L389

https://github.com/openml/openml-python/blob/249abc901c34bc87c4b283e42e754308a5a2d629/openml/study/functions.py#L407

**Comment by mfeurer** [comment]
Fixed via #914.
