### ISSUE TITLE
What preprocessing was applied to OpenML-CC18 datasets?

### ISSUE THREAD

**Issue by pplonski** [openml/openml-python#913]
I would like to use datasets from OpenML-CC18. It will be nice to know what preprocessing was applied to the data?

**Comment by mfeurer** [comment]
Just a brief clarification question as you posted this in the python repository: do you mean what preprocessing is done by the OpenML-Python API or what preprocessing was applied to the data which is on OpenML?

**Comment by pplonski** [comment]
What preprocessing was applied to OpenML data?

**Comment by mfeurer** [comment]
That depends on the dataset itself. You would have to check either the description of the dataset on the website or the publication describing the dataset.
