### ISSUE TITLE
Data edit api for new website

### ISSUE THREAD

**Issue by sahithyaravi1493** [openml/openml-python#929]
As discussed, this api can edit some meta-features of the dataset:
List of  meta-features can  be edited/ updated via data_edit API call, see PR https://github.com/openml/OpenML/pull/1044

1. description
2. creator
3. collection_date
4. language
5. citation
6. original_data_url
7. paper_url

These meta-features/ data will just need to call create_dataset api and create a new version: **(python api)**
1. attributes
2. data - the data itself
3. default_target_attribute
4. ignore_attribute
5. row_id_attribute

After the data_edit API is ready, I can create a single **python API** to handle both of these cases.
Based on the arguments (None or otherwise). We can either create a new dataset or call the data_edit API.

**Comment by PGijsbers** [comment]
Closed through #935
