### ISSUE TITLE
Functions from classes have disappeared from the documentation

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml/openml-python#934]
#### Description
Normally we can look up the functions of OpenML classes, such as Dataset.get_data()
These have disappeared from the developer documentation:
https://openml.github.io/openml-python/develop/generated/openml.OpenMLDataset.html#openml.OpenMLDataset

They are there in the release docs:
https://openml.github.io/openml-python/master/generated/openml.OpenMLDataset.html#openml.OpenMLDataset

Maybe a problem in Sphinx?

#### Steps/Code to Reproduce
Check out 
https://openml.github.io/openml-python/develop/generated/openml.OpenMLDataset.html#openml.OpenMLDataset

#### Expected Results
Something like this
https://openml.github.io/openml-python/master/generated/openml.OpenMLDataset.html#openml.OpenMLDataset

**Comment by mfeurer** [comment]
Fixed via #1044.
