### ISSUE TITLE
Create Github issues for Advanced Topics documentation

### ISSUE THREAD

**Issue by PGijsbers** [openml/openml-python#952]
The [Advanced Topics](https://openml.github.io/openml-python/master/usage.html#advanced-topics) section has a list of "to do" items. It needs to be removed, as we now have a [Gallery](https://openml.github.io/openml-python/master/examples/index.html). The `Querying datasets` is already present in the gallery, the others are not. Please create new Github issues for those three with the `Documentation`  label.

**Comment by scratchmex** [comment]
I'd like to take this one. If I understand correctly, you need to remove the last three and create an issue as to-do list and the first one link to the existing example in the gallery, right?

**Comment by scratchmex** [comment]
That's it. Feedback welcome!

**Comment by PGijsbers** [comment]
Thanks, I'll have a look tomorrow morning!

**Comment by PGijsbers** [comment]
Thanks, I left feedback on the PR. I changed the opened issue titles and added the documentation label.
If on each of you those issues you could change the text from the standard template to simply refer to this issue and have a generic text like "Use this issue to discuss what is important to cover in this example/tutorial." that would be great 👍  
E.g. instead of:

```
Description

This follows #952.
Add "Analyzing large amounts of results" tutorial to examples on In-Depth examples of the gallery.
Steps/Code to Reproduce

Go to examples#in-depth-examples
Expected Results

Tutorial and examples on how to analize large amounts of results on examples#in-depth-examples
Actual Results

--
Versions

--

```
have
```
This follows #952.
Use this issue to discuss what is important to cover in this example/tutorial.
```

The issue template is great for reporting bugs, but perhaps not so much for documentation requests 😄
