### ISSUE TITLE
Add tutorial/example for "creating tasks"

### ISSUE THREAD

**Issue by scratchmex** [openml/openml-python#955]
### Description
Add "Creating tasks" tutorial to `examples` on In-Depth examples of the gallery.

Use this issue to discuss what is important to cover in this example/tutorial.

#### Proposed section
Go to `examples#in-depth-examples`

**Comment by PGijsbers** [comment]
Covered [here](https://openml.github.io/openml-python/master/examples/30_extended/tasks_tutorial.html#creating-tasks).
