### ISSUE TITLE
Home page example fails with 0.11

### ISSUE THREAD

**Issue by PGijsbers** [openml/openml-python#973]
The example on the [documentation homepage](https://openml.github.io/openml-python/master/) fails.
This is due to:
 - openml-python 0.11 working by dataframes by default, which means that categorical features are no longer automatically converted to a numerical representations, and
 - the example pipeline is not compatible with non-numeric input.

This behavior is intended, so we should update the example to use a task with only numeric data instead.

**Comment by a-moadel** [comment]
@PGijsbers I would like to pick this issue up
