### ISSUE TITLE
Python 2 fails with ImportError: No module named apiconnector

### ISSUE THREAD

**Issue by kazeevn** [openml/openml-python#99]
Hi!

Tried running the API on Python 2, got `ImportError: No module named apiconnector`. Docker with the environment to reproduce: https://github.com/yandexdataschool/reproducible_analysis_course/tree/py2_failure

**Comment by amueller** [comment]
@kazeevn sorry I just realized we didn't push the updated notebook to develop yet. There is some weird hickup with the continuous integration of the notebook.

The api was "stable" though ;)

**Comment by amueller** [comment]
I just merged the updated notebook. I have no idea why CI fails. @mfeurer any ideas? I added ipython...

**Comment by mfeurer** [comment]
@amueller I think I fixed it with #101, but now there is another weird error...

**Comment by NateBrune** [comment]
This does not appear to be fixed for me on python2 or 3 running commit  585e09a

**Comment by amueller** [comment]
which notebook are you running? the one from that commit? there is no apiconnector any more.
